// Auto-generated by scripts/migrate-from-prismic.ts
// To regenerate: npx tsx scripts/migrate-from-prismic.ts
// About page content

import type { PageDoc } from "content/types";

export const aboutPage: PageDoc = {
  "uid": "about",
  "data": {
    "title": "About The Grand",
    "gallery": [],
    "video_media": null,
    "video_url": null,
    "media": {},
    "slices": [
      {
        "id": "hero_detail_page_slice$a53218d4-e4d7-4e93-b090-e05ab8d620fe",
        "slice_type": "hero_detail_page_slice",
        "primary": {
          "section_id": "hero",
          "title": null,
          "headline": "LET’S MAKE A MOMENT",
          "caption": "Meet your grand team",
          "video_media": {
            "link_type": "Media"
          },
          "video_url": null,
          "media": {},
          "primary_action": "Contact Sales",
          "primary_action_link": {
            "id": "ZC5YBhAAACEA0ymB",
            "type": "inquire_page",
            "tags": [],
            "lang": "en-us",
            "slug": "inquire-page",
            "first_publication_date": "2023-04-06T05:28:37+0000",
            "last_publication_date": "2023-04-06T05:28:37+0000",
            "uid": "inquire",
            "link_type": "Document",
            "key": "4d356d89-d859-4b70-8e6b-9b38c6bf226a",
            "isBroken": false
          },
          "bottom_spacer": null
        },
        "items": [
          {}
        ]
      },
      {
        "id": "split_scroll_section$60fdb48e-39f8-4d69-92fc-82171122ddb2",
        "slice_type": "split_scroll_section",
        "primary": {
          "section_id": "about-scroll",
          "gallery": {
            "id": "ZLTXQxEAAB8Aer5a",
            "type": "fragment_gallery",
            "tags": [],
            "lang": "en-us",
            "slug": "about-gallery",
            "first_publication_date": "2023-07-17T05:53:12+0000",
            "last_publication_date": "2023-08-12T05:34:55+0000",
            "uid": "about-gallery",
            "data": {
              "gallery_items": [
                {
                  "caption": null,
                  "link": {
                    "link_type": "Any"
                  },
                  "video_media": {
                    "link_type": "Media"
                  },
                  "video_url": null,
                  "media": {
                    "dimensions": {
                      "width": 1920,
                      "height": 1280
                    },
                    "alt": null,
                    "copyright": null,
                    "url": "https://images.prismic.io/the-grand/f8cfb285-d1fd-4369-8bd8-94bb8f85adeb_team-sales.jpg?auto=compress,format",
                    "id": "ZLTXIBEAAB8Aer27",
                    "edit": {
                      "x": 0,
                      "y": 0,
                      "zoom": 1,
                      "background": "#fff"
                    }
                  }
                },
                {
                  "caption": null,
                  "link": {
                    "link_type": "Any"
                  },
                  "video_media": {
                    "link_type": "Media"
                  },
                  "video_url": null,
                  "media": {
                    "dimensions": {
                      "width": 1920,
                      "height": 1280
                    },
                    "alt": null,
                    "copyright": null,
                    "url": "https://images.prismic.io/the-grand/5b512322-d819-4000-a521-5efd3124cdcd_team-jesus.jpg?auto=compress,format",
                    "id": "ZLTXMBEAACIAer4D",
                    "edit": {
                      "x": 0,
                      "y": 0,
                      "zoom": 1,
                      "background": "#fff"
                    }
                  }
                },
                {
                  "caption": null,
                  "link": {
                    "link_type": "Any"
                  },
                  "video_media": {
                    "link_type": "Media"
                  },
                  "video_url": null,
                  "media": {
                    "dimensions": {
                      "width": 1920,
                      "height": 1280
                    },
                    "alt": null,
                    "copyright": null,
                    "url": "https://images.prismic.io/the-grand/d11221f2-3a4c-49cb-9469-330307b993f1_team-cheers.jpg?auto=compress,format",
                    "id": "ZLTXQBEAACIAer5K",
                    "edit": {
                      "x": 0,
                      "y": 0,
                      "zoom": 1,
                      "background": "#fff"
                    }
                  }
                },
                {
                  "caption": null,
                  "link": {
                    "link_type": "Any"
                  },
                  "video_media": {
                    "link_type": "Media"
                  },
                  "video_url": null,
                  "media": {
                    "dimensions": {
                      "width": 2354,
                      "height": 1786
                    },
                    "alt": null,
                    "copyright": null,
                    "url": "https://images.prismic.io/the-grand/f50f8ce8-bf13-4347-b0d7-b883d9fc4f96_glb-about-04.jpg?auto=compress,format",
                    "id": "ZNcZ1hAAACgAom7e",
                    "edit": {
                      "x": 0,
                      "y": 0,
                      "zoom": 1,
                      "background": "#fff"
                    }
                  }
                }
              ]
            },
            "link_type": "Document",
            "key": "ead4769b-2ae8-458f-a64f-6144745e7f37",
            "isBroken": false
          },
          "video_media": {
            "link_type": "Media"
          },
          "video_url": null,
          "media": {},
          "top_spacer": null,
          "bottom_spacer": null,
          "asset_position": true
        },
        "items": [
          {
            "media": {},
            "headline_size": "md",
            "headline": [
              {
                "type": "heading1",
                "text": "We’ve been doing this since 1969.",
                "spans": []
              }
            ],
            "eyebrow": null,
            "body": [
              {
                "type": "paragraph",
                "text": "We are a family-oriented team creating once in a lifetime experiences for our guests.\nOur 65+ talented, energetic, and professional team members produce over 1,000 unique events every year.",
                "spans": []
              }
            ],
            "primary_action_text": null,
            "primary_action_link": {
              "link_type": "Any"
            },
            "secondary_action_text": null,
            "secondary_action_link": {
              "link_type": "Any"
            }
          },
          {
            "media": {},
            "headline_size": "md",
            "headline": [
              {
                "type": "heading1",
                "text": "Bar-none event professionals.",
                "spans": []
              }
            ],
            "eyebrow": null,
            "body": [],
            "primary_action_text": null,
            "primary_action_link": {
              "link_type": "Any"
            },
            "secondary_action_text": null,
            "secondary_action_link": {
              "link_type": "Any"
            }
          },
          {
            "media": {},
            "headline_size": "md",
            "headline": [
              {
                "type": "heading1",
                "text": "No-nonsense kitchen staff.",
                "spans": []
              }
            ],
            "eyebrow": null,
            "body": [],
            "primary_action_text": null,
            "primary_action_link": {
              "link_type": "Any"
            },
            "secondary_action_text": null,
            "secondary_action_link": {
              "link_type": "Any"
            }
          }
        ]
      },
      {
        "id": "team_gallery$13d0e153-edcd-43e9-8c24-93c39e8ceb76",
        "slice_type": "team_gallery",
        "primary": {},
        "items": [
          {
            "name": "Jim \nChoura",
            "position": "CEO & Owner",
            "primary_media": {
              "dimensions": {
                "width": 1000,
                "height": 1000
              },
              "alt": null,
              "copyright": null,
              "url": "https://images.prismic.io/the-grand/74fde4be-581e-479e-a375-f7210e360024_jim-back.jpg?auto=format,compress",
              "id": "ZLTK0hEAAB8Aeoaz",
              "edit": {
                "x": 0,
                "y": 0,
                "zoom": 1,
                "background": "#fff"
              }
            },
            "secondary_media": {
              "dimensions": {
                "width": 1000,
                "height": 1000
              },
              "alt": null,
              "copyright": null,
              "url": "https://images.prismic.io/the-grand/6302e335-4663-4ada-8cdd-99eeeb436509_jim-front.jpg?auto=format,compress",
              "id": "ZLTK0hEAACEAeoa0",
              "edit": {
                "x": 0,
                "y": 0,
                "zoom": 1,
                "background": "#fff"
              }
            }
          },
          {
            "name": "Melanie \nChoura",
            "position": "Owner",
            "primary_media": {
              "dimensions": {
                "width": 1000,
                "height": 1000
              },
              "alt": null,
              "copyright": null,
              "url": "https://images.prismic.io/the-grand/1f552660-53f1-40ca-9488-df917c16705c_melanie.jpg?auto=format,compress",
              "id": "ZLTK1REAAB8AeobP",
              "edit": {
                "x": 0,
                "y": 0,
                "zoom": 1,
                "background": "#fff"
              }
            },
            "secondary_media": {}
          },
          {
            "name": "Dan \nD'sa",
            "position": "Director",
            "primary_media": {
              "dimensions": {
                "width": 1000,
                "height": 1000
              },
              "alt": null,
              "copyright": null,
              "url": "https://images.prismic.io/the-grand/dc18ebaa-9fcc-418d-a40c-c061cac76d16_dan-back.jpg?auto=format,compress",
              "id": "ZLTK0hEAACEAeoa1",
              "edit": {
                "x": 0,
                "y": 0,
                "zoom": 1,
                "background": "#fff"
              }
            },
            "secondary_media": {
              "dimensions": {
                "width": 1000,
                "height": 1000
              },
              "alt": null,
              "copyright": null,
              "url": "https://images.prismic.io/the-grand/a68fdfc1-a655-4a8c-8f71-b8be8da28490_dan-front.jpg?auto=format,compress",
              "id": "ZLTK0xEAAB8Aeoa4",
              "edit": {
                "x": 0,
                "y": 0,
                "zoom": 1,
                "background": "#fff"
              }
            }
          },
          {
            "name": "Rachael\nBarcza",
            "position": "Director of Administration",
            "primary_media": {
              "dimensions": {
                "width": 1000,
                "height": 1000
              },
              "alt": null,
              "copyright": null,
              "url": "https://images.prismic.io/the-grand/e3d14aab-e4a9-41ec-93b5-8b822e6de514_rachael-front.jpg?auto=format,compress",
              "id": "ZLTK0xEAAB8Aeoa9",
              "edit": {
                "x": 0,
                "y": 0,
                "zoom": 1,
                "background": "#fff"
              }
            },
            "secondary_media": {}
          },
          {
            "name": "Gilberto\nVasquez",
            "position": "Director of Operations",
            "primary_media": {
              "dimensions": {
                "width": 1175,
                "height": 1174
              },
              "alt": null,
              "copyright": null,
              "url": "https://images.prismic.io/the-grand/6c92c415-581c-47ac-880d-27de65c2127c_beto-front.jpg?auto=format,compress",
              "id": "ZLTK0xEAAB8Aeoa2",
              "edit": {
                "x": 0,
                "y": 0,
                "zoom": 1,
                "background": "#fff"
              }
            },
            "secondary_media": {
              "dimensions": {
                "width": 1000,
                "height": 1000
              },
              "alt": null,
              "copyright": null,
              "url": "https://images.prismic.io/the-grand/b7e5f84c-03ad-4c67-89af-f0dcd7224a7c_beto-back.jpg?auto=format,compress",
              "id": "ZLTK1BEAAB8AeobE",
              "edit": {
                "x": 0,
                "y": 0,
                "zoom": 1,
                "background": "#fff"
              }
            }
          },
          {
            "name": "Elexis\nWright",
            "position": "Assistant Director of Operations",
            "primary_media": {
              "dimensions": {
                "width": 1000,
                "height": 1000
              },
              "alt": null,
              "copyright": null,
              "url": "https://images.prismic.io/the-grand/ed720552-a86a-4c64-8b92-38141c2ea1a9_elexis.jpg?auto=format,compress",
              "id": "ZLTK1BEAACEAeobC",
              "edit": {
                "x": 0,
                "y": 0,
                "zoom": 1,
                "background": "#fff"
              }
            },
            "secondary_media": {}
          },
          {
            "name": "Jesus\nGonzalez",
            "position": "Executive Chef",
            "primary_media": {
              "dimensions": {
                "width": 1000,
                "height": 1000
              },
              "alt": null,
              "copyright": null,
              "url": "https://images.prismic.io/the-grand/82b3e1a4-fdd9-415e-9171-5bf6d36471e1_jesus.jpg?auto=format,compress",
              "id": "ZLTK0xEAACIAeoa8",
              "edit": {
                "x": 0,
                "y": 0,
                "zoom": 1,
                "background": "#fff"
              }
            },
            "secondary_media": {}
          },
          {
            "name": "Marissa\nHofer",
            "position": "Event Manager",
            "primary_media": {
              "dimensions": {
                "width": 2667,
                "height": 2667
              },
              "alt": null,
              "copyright": null,
              "url": "https://images.prismic.io/the-grand/fd58f8e0-e840-4f4e-920b-c8e96a3c5660_marissa-front.jpg?auto=format,compress",
              "id": "ZLTK1BEAACEAeobI",
              "edit": {
                "x": 0,
                "y": 0,
                "zoom": 1,
                "background": "#fff"
              }
            },
            "secondary_media": {}
          },
          {
            "name": "Elizabeth\nNoecker",
            "position": "Event Manager",
            "primary_media": {
              "dimensions": {
                "width": 1000,
                "height": 1000
              },
              "alt": null,
              "copyright": null,
              "url": "https://images.prismic.io/the-grand/b66dd2ed-9fc6-47fa-99a5-fd0eab336674_elizabeth-front.jpg?auto=format,compress",
              "id": "ZLTK1BEAAB8AeobK",
              "edit": {
                "x": 0,
                "y": 0,
                "zoom": 1,
                "background": "#fff"
              }
            },
            "secondary_media": {}
          },
          {
            "name": "Lisa\nDeLeon",
            "position": "Office Manager",
            "primary_media": {
              "dimensions": {
                "width": 1000,
                "height": 1000
              },
              "alt": null,
              "copyright": null,
              "url": "https://images.prismic.io/the-grand/50973021-7f76-43d3-816a-f9bbdc1bb207_lisa-front.jpg?auto=format,compress",
              "id": "ZLTK1REAACEAeobO",
              "edit": {
                "x": 0,
                "y": 0,
                "zoom": 1,
                "background": "#fff"
              }
            },
            "secondary_media": {
              "dimensions": {
                "width": 1000,
                "height": 1000
              },
              "alt": null,
              "copyright": null,
              "url": "https://images.prismic.io/the-grand/e6125962-8d0c-44f5-9fc6-6a267055e09d_lisa-back.jpg?auto=format,compress",
              "id": "ZLTK0xEAAB8Aeoa3",
              "edit": {
                "x": 0,
                "y": 0,
                "zoom": 1,
                "background": "#fff"
              }
            }
          }
        ]
      }
    ],
    "meta_title": null,
    "meta_description": null,
    "meta_image": {}
  }
};
