// Auto-generated by scripts/migrate-from-prismic.ts
// To regenerate: npx tsx scripts/migrate-from-prismic.ts
// About page content

import type { PageDoc } from "content/types";

export const aboutPage: PageDoc = {
  "uid": "about",
  "data": {
    "title": "About The Grand",
    "gallery": [],
    "video_media": null,
    "video_url": null,
    "media": {},
    "slices": [
      {
        "id": "hero_detail_page_slice$a53218d4-e4d7-4e93-b090-e05ab8d620fe",
        "slice_type": "hero_detail_page_slice",
        "primary": {
          "section_id": "hero",
          "title": null,
          "headline": "LET’S MAKE A MOMENT",
          "caption": "Meet your grand team",
          "video_media": {
            "link_type": "Media"
          },
          "video_url": null,
          "media": {},
          "primary_action": "Contact Sales",
          "primary_action_link": {
            "id": "ZC5YBhAAACEA0ymB",
            "type": "inquire_page",
            "tags": [],
            "lang": "en-us",
            "slug": "inquire-page",
            "first_publication_date": "2023-04-06T05:28:37+0000",
            "last_publication_date": "2023-04-06T05:28:37+0000",
            "uid": "inquire",
            "link_type": "Document",
            "key": "4d356d89-d859-4b70-8e6b-9b38c6bf226a",
            "isBroken": false
          },
          "bottom_spacer": null
        },
        "items": [
          {}
        ]
      },
      {
        "id": "split_scroll_section$60fdb48e-39f8-4d69-92fc-82171122ddb2",
        "slice_type": "split_scroll_section",
        "primary": {
          "section_id": "about-scroll",
          "gallery": {
            "id": "ZLTXQxEAAB8Aer5a",
            "type": "fragment_gallery",
            "tags": [],
            "lang": "en-us",
            "slug": "about-gallery",
            "first_publication_date": "2023-07-17T05:53:12+0000",
            "last_publication_date": "2023-08-12T05:34:55+0000",
            "uid": "about-gallery",
            "data": {
              "gallery_items": [
                {
                  "caption": null,
                  "link": {
                    "link_type": "Any"
                  },
                  "video_media": {
                    "link_type": "Media"
                  },
                  "video_url": null,
                  "media": {
                    "dimensions": {
                      "width": 1920,
                      "height": 1280
                    },
                    "alt": null,
                    "copyright": null,
                    "url": "https://imagedelivery.net/jq-BfOr8JDGgGxqbx8v5CA/9291de0f-7b81-40bf-3fc8-a8df9ebf2700/public",
                    "id": "ZLTXIBEAAB8Aer27",
                    "edit": {
                      "x": 0,
                      "y": 0,
                      "zoom": 1,
                      "background": "#fff"
                    }
                  }
                },
                {
                  "caption": null,
                  "link": {
                    "link_type": "Any"
                  },
                  "video_media": {
                    "link_type": "Media"
                  },
                  "video_url": null,
                  "media": {
                    "dimensions": {
                      "width": 1920,
                      "height": 1280
                    },
                    "alt": null,
                    "copyright": null,
                    "url": "https://imagedelivery.net/jq-BfOr8JDGgGxqbx8v5CA/8e96112c-b8bc-46c4-2844-5de5ad562700/public",
                    "id": "ZLTXMBEAACIAer4D",
                    "edit": {
                      "x": 0,
                      "y": 0,
                      "zoom": 1,
                      "background": "#fff"
                    }
                  }
                },
                {
                  "caption": null,
                  "link": {
                    "link_type": "Any"
                  },
                  "video_media": {
                    "link_type": "Media"
                  },
                  "video_url": null,
                  "media": {
                    "dimensions": {
                      "width": 1920,
                      "height": 1280
                    },
                    "alt": null,
                    "copyright": null,
                    "url": "https://imagedelivery.net/jq-BfOr8JDGgGxqbx8v5CA/24d9f1d6-31a6-4a42-d147-6e99ddf24500/public",
                    "id": "ZLTXQBEAACIAer5K",
                    "edit": {
                      "x": 0,
                      "y": 0,
                      "zoom": 1,
                      "background": "#fff"
                    }
                  }
                },
                {
                  "caption": null,
                  "link": {
                    "link_type": "Any"
                  },
                  "video_media": {
                    "link_type": "Media"
                  },
                  "video_url": null,
                  "media": {
                    "dimensions": {
                      "width": 2354,
                      "height": 1786
                    },
                    "alt": null,
                    "copyright": null,
                    "url": "https://imagedelivery.net/jq-BfOr8JDGgGxqbx8v5CA/dd8a664a-14f9-489f-f212-9836ba6f7800/public",
                    "id": "ZNcZ1hAAACgAom7e",
                    "edit": {
                      "x": 0,
                      "y": 0,
                      "zoom": 1,
                      "background": "#fff"
                    }
                  }
                }
              ]
            },
            "link_type": "Document",
            "key": "ead4769b-2ae8-458f-a64f-6144745e7f37",
            "isBroken": false
          },
          "video_media": {
            "link_type": "Media"
          },
          "video_url": null,
          "media": {},
          "top_spacer": null,
          "bottom_spacer": null,
          "asset_position": true
        },
        "items": [
          {
            "media": {},
            "headline_size": "md",
            "headline": [
              {
                "type": "heading1",
                "text": "We’ve been doing this since 1969.",
                "spans": []
              }
            ],
            "eyebrow": null,
            "body": [
              {
                "type": "paragraph",
                "text": "We are a family-oriented team creating once in a lifetime experiences for our guests.\nOur 65+ talented, energetic, and professional team members produce over 1,000 unique events every year.",
                "spans": []
              }
            ],
            "primary_action_text": null,
            "primary_action_link": {
              "link_type": "Any"
            },
            "secondary_action_text": null,
            "secondary_action_link": {
              "link_type": "Any"
            }
          },
          {
            "media": {},
            "headline_size": "md",
            "headline": [
              {
                "type": "heading1",
                "text": "Bar-none event professionals.",
                "spans": []
              }
            ],
            "eyebrow": null,
            "body": [],
            "primary_action_text": null,
            "primary_action_link": {
              "link_type": "Any"
            },
            "secondary_action_text": null,
            "secondary_action_link": {
              "link_type": "Any"
            }
          },
          {
            "media": {},
            "headline_size": "md",
            "headline": [
              {
                "type": "heading1",
                "text": "No-nonsense kitchen staff.",
                "spans": []
              }
            ],
            "eyebrow": null,
            "body": [],
            "primary_action_text": null,
            "primary_action_link": {
              "link_type": "Any"
            },
            "secondary_action_text": null,
            "secondary_action_link": {
              "link_type": "Any"
            }
          }
        ]
      },
      {
        "id": "team_gallery$13d0e153-edcd-43e9-8c24-93c39e8ceb76",
        "slice_type": "team_gallery",
        "primary": {},
        "items": [
          {
            "name": "Jim \nChoura",
            "position": "CEO & Owner",
            "primary_media": {
              "dimensions": {
                "width": 1000,
                "height": 1000
              },
              "alt": null,
              "copyright": null,
              "url": "https://imagedelivery.net/jq-BfOr8JDGgGxqbx8v5CA/0a830e64-16a7-4af8-f53a-1ea322919e00/public",
              "id": "ZLTK0hEAAB8Aeoaz",
              "edit": {
                "x": 0,
                "y": 0,
                "zoom": 1,
                "background": "#fff"
              }
            },
            "secondary_media": {
              "dimensions": {
                "width": 1000,
                "height": 1000
              },
              "alt": null,
              "copyright": null,
              "url": "https://imagedelivery.net/jq-BfOr8JDGgGxqbx8v5CA/22fb4442-0635-4729-391b-6a6fac7af400/public",
              "id": "ZLTK0hEAACEAeoa0",
              "edit": {
                "x": 0,
                "y": 0,
                "zoom": 1,
                "background": "#fff"
              }
            }
          },
          {
            "name": "Melanie \nChoura",
            "position": "Owner",
            "primary_media": {
              "dimensions": {
                "width": 1000,
                "height": 1000
              },
              "alt": null,
              "copyright": null,
              "url": "https://imagedelivery.net/jq-BfOr8JDGgGxqbx8v5CA/bc23dc72-1b4e-454b-9572-15465ee2a800/public",
              "id": "ZLTK1REAAB8AeobP",
              "edit": {
                "x": 0,
                "y": 0,
                "zoom": 1,
                "background": "#fff"
              }
            },
            "secondary_media": {}
          },
          {
            "name": "Dan \nD'sa",
            "position": "Director",
            "primary_media": {
              "dimensions": {
                "width": 1000,
                "height": 1000
              },
              "alt": null,
              "copyright": null,
              "url": "https://imagedelivery.net/jq-BfOr8JDGgGxqbx8v5CA/dfcae997-e4ab-43db-9b06-6b58ccbfec00/public",
              "id": "ZLTK0hEAACEAeoa1",
              "edit": {
                "x": 0,
                "y": 0,
                "zoom": 1,
                "background": "#fff"
              }
            },
            "secondary_media": {
              "dimensions": {
                "width": 1000,
                "height": 1000
              },
              "alt": null,
              "copyright": null,
              "url": "https://imagedelivery.net/jq-BfOr8JDGgGxqbx8v5CA/12712332-36fa-4d26-10c8-35f35f3c4c00/public",
              "id": "ZLTK0xEAAB8Aeoa4",
              "edit": {
                "x": 0,
                "y": 0,
                "zoom": 1,
                "background": "#fff"
              }
            }
          },
          {
            "name": "Rachael\nBarcza",
            "position": "Director of Administration",
            "primary_media": {
              "dimensions": {
                "width": 1000,
                "height": 1000
              },
              "alt": null,
              "copyright": null,
              "url": "https://imagedelivery.net/jq-BfOr8JDGgGxqbx8v5CA/2c55bfad-d55a-4464-8afe-8a622a5e0c00/public",
              "id": "ZLTK0xEAAB8Aeoa9",
              "edit": {
                "x": 0,
                "y": 0,
                "zoom": 1,
                "background": "#fff"
              }
            },
            "secondary_media": {}
          },
          {
            "name": "Gilberto\nVasquez",
            "position": "Director of Operations",
            "primary_media": {
              "dimensions": {
                "width": 1175,
                "height": 1174
              },
              "alt": null,
              "copyright": null,
              "url": "https://imagedelivery.net/jq-BfOr8JDGgGxqbx8v5CA/dc4d9630-6872-458e-7223-8e94e5fb8800/public",
              "id": "ZLTK0xEAAB8Aeoa2",
              "edit": {
                "x": 0,
                "y": 0,
                "zoom": 1,
                "background": "#fff"
              }
            },
            "secondary_media": {
              "dimensions": {
                "width": 1000,
                "height": 1000
              },
              "alt": null,
              "copyright": null,
              "url": "https://imagedelivery.net/jq-BfOr8JDGgGxqbx8v5CA/792ee76a-6878-4c90-8b77-9448f34b9b00/public",
              "id": "ZLTK1BEAAB8AeobE",
              "edit": {
                "x": 0,
                "y": 0,
                "zoom": 1,
                "background": "#fff"
              }
            }
          },
          {
            "name": "Elexis\nWright",
            "position": "Assistant Director of Operations",
            "primary_media": {
              "dimensions": {
                "width": 1000,
                "height": 1000
              },
              "alt": null,
              "copyright": null,
              "url": "https://imagedelivery.net/jq-BfOr8JDGgGxqbx8v5CA/5c5a5a88-be98-49ee-62ab-80e5f1b16a00/public",
              "id": "ZLTK1BEAACEAeobC",
              "edit": {
                "x": 0,
                "y": 0,
                "zoom": 1,
                "background": "#fff"
              }
            },
            "secondary_media": {}
          },
          {
            "name": "Jesus\nGonzalez",
            "position": "Executive Chef",
            "primary_media": {
              "dimensions": {
                "width": 1000,
                "height": 1000
              },
              "alt": null,
              "copyright": null,
              "url": "https://imagedelivery.net/jq-BfOr8JDGgGxqbx8v5CA/b6065055-4022-4fb1-948f-9285a0a87000/public",
              "id": "ZLTK0xEAACIAeoa8",
              "edit": {
                "x": 0,
                "y": 0,
                "zoom": 1,
                "background": "#fff"
              }
            },
            "secondary_media": {}
          },
          {
            "name": "Marissa\nHofer",
            "position": "Event Manager",
            "primary_media": {
              "dimensions": {
                "width": 2667,
                "height": 2667
              },
              "alt": null,
              "copyright": null,
              "url": "https://imagedelivery.net/jq-BfOr8JDGgGxqbx8v5CA/afd5ef59-c7c5-4ac7-fecf-e91d3cf00c00/public",
              "id": "ZLTK1BEAACEAeobI",
              "edit": {
                "x": 0,
                "y": 0,
                "zoom": 1,
                "background": "#fff"
              }
            },
            "secondary_media": {}
          },
          {
            "name": "Elizabeth\nNoecker",
            "position": "Event Manager",
            "primary_media": {
              "dimensions": {
                "width": 1000,
                "height": 1000
              },
              "alt": null,
              "copyright": null,
              "url": "https://imagedelivery.net/jq-BfOr8JDGgGxqbx8v5CA/9778f178-81ac-478e-a9ea-2a2f358a1e00/public",
              "id": "ZLTK1BEAAB8AeobK",
              "edit": {
                "x": 0,
                "y": 0,
                "zoom": 1,
                "background": "#fff"
              }
            },
            "secondary_media": {}
          },
          {
            "name": "Lisa\nDeLeon",
            "position": "Office Manager",
            "primary_media": {
              "dimensions": {
                "width": 1000,
                "height": 1000
              },
              "alt": null,
              "copyright": null,
              "url": "https://imagedelivery.net/jq-BfOr8JDGgGxqbx8v5CA/109ad8aa-2787-4674-e8a5-bcc3a150bc00/public",
              "id": "ZLTK1REAACEAeobO",
              "edit": {
                "x": 0,
                "y": 0,
                "zoom": 1,
                "background": "#fff"
              }
            },
            "secondary_media": {
              "dimensions": {
                "width": 1000,
                "height": 1000
              },
              "alt": null,
              "copyright": null,
              "url": "https://imagedelivery.net/jq-BfOr8JDGgGxqbx8v5CA/8ab52e5d-0104-45a8-309b-bd61686c6f00/public",
              "id": "ZLTK0xEAAB8Aeoa3",
              "edit": {
                "x": 0,
                "y": 0,
                "zoom": 1,
                "background": "#fff"
              }
            }
          }
        ]
      }
    ],
    "meta_title": null,
    "meta_description": null,
    "meta_image": {}
  }
};
