// Auto-generated by scripts/migrate-from-prismic.ts
// To regenerate: npx tsx scripts/migrate-from-prismic.ts
// Event detail pages — uid-keyed map

import type { PageDoc } from "content/types";

export const eventPages: Record<string, PageDoc> = {
  "milestones": {
    "uid": "milestones",
    "data": {
      "title": "Milestones",
      "headline": "Party in grand style",
      "caption": "Celebrate your milestones in style.",
      "gallery": [],
      "video_media": null,
      "video_url": null,
      "media": {},
      "slices": [
        {
          "id": "image_section$4d753478-61ff-4129-abfb-c979c99c863b",
          "slice_type": "image_section",
          "primary": {
            "section_id": null,
            "gallery": {
              "link_type": "Document"
            },
            "video_media": {
              "link_type": "Media"
            },
            "video_url": null,
            "media": {
              "dimensions": {
                "width": 2816,
                "height": 1826
              },
              "alt": null,
              "copyright": null,
              "url": "https://images.prismic.io/the-grand/8e0a95ab-f3a9-41c3-9a51-5a516c8156d5_cover.jpg?auto=compress,format",
              "id": "ZNcY_xAAACcAomse",
              "edit": {
                "x": 0,
                "y": 0,
                "zoom": 1,
                "background": "#fff"
              }
            },
            "top_spacer": null,
            "bottom_spacer": "None"
          },
          "items": [
            {}
          ]
        },
        {
          "id": "text_section$41013433-d085-45d2-b3b4-741dceab15cb",
          "slice_type": "text_section",
          "primary": {
            "section_id": "intro",
            "eyebrow": null,
            "body": [
              {
                "type": "paragraph",
                "text": "Celebrate your milestones at The Grand and make unforgettable memories. Our experienced event planners will help you craft a personalized celebration that fits your needs and budget. Let us make your event unforgettable.",
                "spans": []
              }
            ],
            "primary_action": "Make an inquiry",
            "primary_action_link": {
              "id": "ZC5YBhAAACEA0ymB",
              "type": "inquire_page",
              "tags": [],
              "lang": "en-us",
              "slug": "inquire-page",
              "first_publication_date": "2023-04-06T05:28:37+0000",
              "last_publication_date": "2023-04-06T05:28:37+0000",
              "uid": "inquire",
              "link_type": "Document",
              "key": "05cebaeb-c2e7-4b70-afda-9b15879db628",
              "isBroken": false
            },
            "secondary_action": null,
            "secondary_action_link": {
              "link_type": "Any"
            },
            "top_spacer": "Small",
            "top_border": null,
            "bottom_spacer": "Small",
            "bottom_border": null
          },
          "items": [
            {}
          ]
        },
        {
          "id": "numbers_section$a07514cf-3c13-4f07-8d23-193117406f80",
          "slice_type": "numbers_section",
          "primary": {
            "section_id": "features",
            "title": null,
            "description": null,
            "columns": "3 Column",
            "inset": null,
            "top_spacer": "None",
            "top_border": true,
            "bottom_spacer": "Medium",
            "bottom_border": true
          },
          "items": [
            {
              "media": {
                "dimensions": {
                  "width": 85,
                  "height": 84
                },
                "alt": null,
                "copyright": null,
                "url": "https://the-grand.cdn.prismic.io/the-grand/e36092fd-2316-42f4-b510-936b1a3d1ef2_elegant.svg",
                "id": "ZGVJpBAAACAAd5xv",
                "edit": {
                  "x": 0,
                  "y": 0,
                  "zoom": 1,
                  "background": "#fff"
                }
              },
              "number": [
                {
                  "type": "heading1",
                  "text": "",
                  "spans": []
                }
              ],
              "eyebrow": "Sophistication",
              "body": [
                {
                  "type": "paragraph",
                  "text": "Our spacious ballrooms and elegant dining rooms provide the perfect setting for your milestone or party event.",
                  "spans": []
                }
              ],
              "action_text": null,
              "action_link": {
                "link_type": "Any"
              }
            },
            {
              "media": {
                "dimensions": {
                  "width": 85,
                  "height": 84
                },
                "alt": null,
                "copyright": null,
                "url": "https://the-grand.cdn.prismic.io/the-grand/c09bb552-df46-461d-88a1-63edd8f1f7a7_flexible.svg",
                "id": "ZGVJpBAAACEAd5xw",
                "edit": {
                  "x": 0,
                  "y": 0,
                  "zoom": 1,
                  "background": "#fff"
                }
              },
              "number": [],
              "eyebrow": "Flexibility",
              "body": [
                {
                  "type": "paragraph",
                  "text": "The Grand Long Beach can accommodate events of all sizes, from intimate gatherings of 50 guests to large-scale celebrations of 1,000 guests.",
                  "spans": []
                }
              ],
              "action_text": null,
              "action_link": {
                "link_type": "Any"
              }
            },
            {
              "media": {
                "dimensions": {
                  "width": 85,
                  "height": 84
                },
                "alt": null,
                "copyright": null,
                "url": "https://the-grand.cdn.prismic.io/the-grand/c1aebc83-c2ff-40f9-9b8e-932fa8270f31_personal.svg",
                "id": "ZGVJpBAAACAAd5xx",
                "edit": {
                  "x": 0,
                  "y": 0,
                  "zoom": 1,
                  "background": "#fff"
                }
              },
              "number": [],
              "eyebrow": "Customization",
              "body": [
                {
                  "type": "paragraph",
                  "text": "Our experienced event planners will work with you to create a celebration that is tailored to your needs and reflects your unique style.",
                  "spans": []
                }
              ],
              "action_text": null,
              "action_link": {
                "link_type": "Any"
              }
            }
          ]
        },
        {
          "id": "split_scroll_section$b326e5ad-4fd5-4e84-a55b-ae63b3c1293f",
          "slice_type": "split_scroll_section",
          "primary": {
            "section_id": "list",
            "gallery": {
              "id": "ZNcRUxAAACkAokk9",
              "type": "fragment_gallery",
              "tags": [],
              "lang": "en-us",
              "slug": "events-milestones-scroll",
              "first_publication_date": "2023-08-12T05:00:31+0000",
              "last_publication_date": "2023-08-12T05:00:31+0000",
              "uid": "events-milestones-scroll",
              "data": {
                "gallery_items": [
                  {
                    "caption": null,
                    "link": {
                      "link_type": "Any"
                    },
                    "video_media": {
                      "link_type": "Media"
                    },
                    "video_url": null,
                    "media": {
                      "dimensions": {
                        "width": 2464,
                        "height": 1848
                      },
                      "alt": null,
                      "copyright": null,
                      "url": "https://images.prismic.io/the-grand/5e9c5b5d-944b-4a57-9bab-157e682c567c_glb-events-social-02.jpg?auto=compress,format",
                      "id": "ZNcRvxAAACYAoksg",
                      "edit": {
                        "x": 0,
                        "y": 0,
                        "zoom": 1,
                        "background": "#fff"
                      }
                    }
                  },
                  {
                    "caption": null,
                    "link": {
                      "link_type": "Any"
                    },
                    "video_media": {
                      "link_type": "Media"
                    },
                    "video_url": null,
                    "media": {
                      "dimensions": {
                        "width": 2464,
                        "height": 1848
                      },
                      "alt": null,
                      "copyright": null,
                      "url": "https://images.prismic.io/the-grand/acbabfac-dd9d-46e2-b0a1-59c87e1138d2_glb-broll-07.jpg?auto=compress,format",
                      "id": "ZNcRvhAAACcAoksa",
                      "edit": {
                        "x": 0,
                        "y": 0,
                        "zoom": 1,
                        "background": "#fff"
                      }
                    }
                  },
                  {
                    "caption": null,
                    "link": {
                      "link_type": "Any"
                    },
                    "video_media": {
                      "link_type": "Media"
                    },
                    "video_url": null,
                    "media": {
                      "dimensions": {
                        "width": 2464,
                        "height": 1848
                      },
                      "alt": null,
                      "copyright": null,
                      "url": "https://images.prismic.io/the-grand/95b6d827-d384-4a7c-a9c1-036a48f090a7_glb-broll-08.jpg?auto=compress,format",
                      "id": "ZNcRvBAAACgAoksU",
                      "edit": {
                        "x": 0,
                        "y": 0,
                        "zoom": 1,
                        "background": "#fff"
                      }
                    }
                  },
                  {
                    "caption": null,
                    "link": {
                      "link_type": "Any"
                    },
                    "video_media": {
                      "link_type": "Media"
                    },
                    "video_url": null,
                    "media": {
                      "dimensions": {
                        "width": 2464,
                        "height": 1848
                      },
                      "alt": null,
                      "copyright": null,
                      "url": "https://images.prismic.io/the-grand/30a664d2-af13-4062-a55f-c737f9736fd9_glb-events-social-02-1.jpg?auto=compress,format",
                      "id": "ZNcRwBAAACkAoksq",
                      "edit": {
                        "x": 0,
                        "y": 0,
                        "zoom": 1,
                        "background": "#fff"
                      }
                    }
                  },
                  {
                    "caption": null,
                    "link": {
                      "link_type": "Any"
                    },
                    "video_media": {
                      "link_type": "Media"
                    },
                    "video_url": null,
                    "media": {
                      "dimensions": {
                        "width": 1848,
                        "height": 2464
                      },
                      "alt": null,
                      "copyright": null,
                      "url": "https://images.prismic.io/the-grand/aa6fdf42-1125-4baf-b50a-2cf4d8c26d10_glb-events-social-03.jpg?auto=compress,format",
                      "id": "ZNcRvBAAACgAoksO",
                      "edit": {
                        "x": 0,
                        "y": 0,
                        "zoom": 1,
                        "background": "#fff"
                      }
                    }
                  },
                  {
                    "caption": null,
                    "link": {
                      "link_type": "Any"
                    },
                    "video_media": {
                      "link_type": "Media"
                    },
                    "video_url": null,
                    "media": {
                      "dimensions": {
                        "width": 1848,
                        "height": 2464
                      },
                      "alt": null,
                      "copyright": null,
                      "url": "https://images.prismic.io/the-grand/c73c96d3-048f-49f8-8234-fea83e991c8c_glb-broll-05.jpg?auto=compress,format",
                      "id": "ZNcRvxAAACgAoksl",
                      "edit": {
                        "x": 0,
                        "y": 0,
                        "zoom": 1,
                        "background": "#fff"
                      }
                    }
                  }
                ]
              },
              "link_type": "Document",
              "key": "69c835d1-7de6-4131-94d0-8ac481fd85c9",
              "isBroken": false
            },
            "video_media": {
              "link_type": "Media"
            },
            "video_url": null,
            "media": {},
            "top_spacer": null,
            "bottom_spacer": null,
            "asset_position": false
          },
          "items": [
            {
              "media": {},
              "headline_size": null,
              "headline": [
                {
                  "type": "heading1",
                  "text": "5",
                  "spans": []
                }
              ],
              "eyebrow": "Parties per week",
              "body": [],
              "primary_action_text": null,
              "primary_action_link": {
                "link_type": "Any"
              },
              "secondary_action_text": null,
              "secondary_action_link": {
                "link_type": "Any"
              }
            },
            {
              "media": {},
              "headline_size": null,
              "headline": [
                {
                  "type": "heading1",
                  "text": "480",
                  "spans": []
                }
              ],
              "eyebrow": "Parties last year",
              "body": [],
              "primary_action_text": null,
              "primary_action_link": {
                "link_type": "Any"
              },
              "secondary_action_text": null,
              "secondary_action_link": {
                "link_type": "Any"
              }
            },
            {
              "media": {},
              "headline_size": null,
              "headline": [
                {
                  "type": "heading1",
                  "text": "10 ",
                  "spans": []
                }
              ],
              "eyebrow": "Hours of parties per day",
              "body": [],
              "primary_action_text": null,
              "primary_action_link": {
                "link_type": "Any"
              },
              "secondary_action_text": null,
              "secondary_action_link": {
                "link_type": "Any"
              }
            },
            {
              "media": {},
              "headline_size": null,
              "headline": [
                {
                  "type": "heading1",
                  "text": "Saturday",
                  "spans": []
                }
              ],
              "eyebrow": "Most popular party day",
              "body": [],
              "primary_action_text": null,
              "primary_action_link": {
                "link_type": "Any"
              },
              "secondary_action_text": null,
              "secondary_action_link": {
                "link_type": "Any"
              }
            },
            {
              "media": {},
              "headline_size": null,
              "headline": [
                {
                  "type": "heading1",
                  "text": "115",
                  "spans": []
                }
              ],
              "eyebrow": "Average party attendance",
              "body": [],
              "primary_action_text": null,
              "primary_action_link": {
                "link_type": "Any"
              },
              "secondary_action_text": null,
              "secondary_action_link": {
                "link_type": "Any"
              }
            }
          ]
        }
      ],
      "meta_title": null,
      "meta_description": null,
      "meta_image": {}
    }
  },
  "business": {
    "uid": "business",
    "data": {
      "title": "Business",
      "headline": "Business meets pleasure",
      "caption": "Elevate your events with our professional touch.",
      "gallery": [],
      "video_media": null,
      "video_url": null,
      "media": {},
      "slices": [
        {
          "id": "image_section$a39f2568-e2b6-490e-9c0b-92c31ce21757",
          "slice_type": "image_section",
          "primary": {
            "section_id": null,
            "gallery": {
              "link_type": "Document"
            },
            "video_media": {
              "link_type": "Media"
            },
            "video_url": null,
            "media": {
              "dimensions": {
                "width": 2816,
                "height": 1826
              },
              "alt": null,
              "copyright": null,
              "url": "https://images.prismic.io/the-grand/220954ca-95d5-42ab-b253-a1b38d3bc2a2_glb-events-business-04.jpg?auto=compress,format",
              "id": "ZNcZKRAAACgAomvc",
              "edit": {
                "x": 0,
                "y": 0,
                "zoom": 1,
                "background": "#fff"
              }
            },
            "top_spacer": null,
            "bottom_spacer": "None"
          },
          "items": [
            {}
          ]
        },
        {
          "id": "text_section$505a1350-d15f-490d-ae20-fcb8c719a298",
          "slice_type": "text_section",
          "primary": {
            "section_id": "intro",
            "eyebrow": null,
            "body": [
              {
                "type": "paragraph",
                "text": "Elevate your corporate events and leave a lasting impression. Our experienced event planners will help you create a memorable and professional event tailored to your needs and budget, whether it's an executive meeting or a large conference.",
                "spans": []
              }
            ],
            "primary_action": "Plan your event",
            "primary_action_link": {
              "id": "ZC5YBhAAACEA0ymB",
              "type": "inquire_page",
              "tags": [],
              "lang": "en-us",
              "slug": "inquire-page",
              "first_publication_date": "2023-04-06T05:28:37+0000",
              "last_publication_date": "2023-04-06T05:28:37+0000",
              "uid": "inquire",
              "link_type": "Document",
              "key": "6c210487-92e1-4616-af1c-5c29820fa161",
              "isBroken": false
            },
            "secondary_action": null,
            "secondary_action_link": {
              "link_type": "Any"
            },
            "top_spacer": "Small",
            "top_border": null,
            "bottom_spacer": "Small",
            "bottom_border": null
          },
          "items": [
            {}
          ]
        },
        {
          "id": "numbers_section$73c25c95-97e6-4a7a-b728-22bcdfb6cb4d",
          "slice_type": "numbers_section",
          "primary": {
            "section_id": "features",
            "title": null,
            "description": null,
            "columns": "3 Column",
            "inset": null,
            "top_spacer": "None",
            "top_border": true,
            "bottom_spacer": "Medium",
            "bottom_border": true
          },
          "items": [
            {
              "media": {
                "dimensions": {
                  "width": 85,
                  "height": 84
                },
                "alt": null,
                "copyright": null,
                "url": "https://the-grand.cdn.prismic.io/the-grand/e36092fd-2316-42f4-b510-936b1a3d1ef2_elegant.svg",
                "id": "ZGVJpBAAACAAd5xv",
                "edit": {
                  "x": 0,
                  "y": 0,
                  "zoom": 1,
                  "background": "#fff"
                }
              },
              "number": [
                {
                  "type": "heading1",
                  "text": "",
                  "spans": []
                }
              ],
              "eyebrow": "Sophistication",
              "body": [
                {
                  "type": "paragraph",
                  "text": "Our spacious ballrooms and elegant dining rooms provide the perfect setting for your milestone or party event.",
                  "spans": []
                }
              ],
              "action_text": null,
              "action_link": {
                "link_type": "Any"
              }
            },
            {
              "media": {
                "dimensions": {
                  "width": 85,
                  "height": 84
                },
                "alt": null,
                "copyright": null,
                "url": "https://the-grand.cdn.prismic.io/the-grand/c09bb552-df46-461d-88a1-63edd8f1f7a7_flexible.svg",
                "id": "ZGVJpBAAACEAd5xw",
                "edit": {
                  "x": 0,
                  "y": 0,
                  "zoom": 1,
                  "background": "#fff"
                }
              },
              "number": [
                {
                  "type": "heading1",
                  "text": "",
                  "spans": []
                }
              ],
              "eyebrow": "Flexibility",
              "body": [
                {
                  "type": "paragraph",
                  "text": "The Grand Long Beach can accommodate events of all sizes, from intimate gatherings of 50 guests to large-scale celebrations of 1,000 guests.",
                  "spans": []
                }
              ],
              "action_text": null,
              "action_link": {
                "link_type": "Any"
              }
            },
            {
              "media": {
                "dimensions": {
                  "width": 85,
                  "height": 84
                },
                "alt": null,
                "copyright": null,
                "url": "https://the-grand.cdn.prismic.io/the-grand/c1aebc83-c2ff-40f9-9b8e-932fa8270f31_personal.svg",
                "id": "ZGVJpBAAACAAd5xx",
                "edit": {
                  "x": 0,
                  "y": 0,
                  "zoom": 1,
                  "background": "#fff"
                }
              },
              "number": [],
              "eyebrow": "Customization",
              "body": [
                {
                  "type": "paragraph",
                  "text": "Our experienced event planners will work with you to create a celebration that is tailored to your needs and reflects your unique style.",
                  "spans": []
                }
              ],
              "action_text": null,
              "action_link": {
                "link_type": "Any"
              }
            }
          ]
        },
        {
          "id": "split_scroll_section$33ed3045-cde4-41d8-920e-a032233ded3b",
          "slice_type": "split_scroll_section",
          "primary": {
            "section_id": "list",
            "gallery": {
              "id": "ZNcSMhAAACYAok0N",
              "type": "fragment_gallery",
              "tags": [],
              "lang": "en-us",
              "slug": "events-business-scroll",
              "first_publication_date": "2023-08-12T05:02:32+0000",
              "last_publication_date": "2023-08-12T05:02:32+0000",
              "uid": "events-business-scroll",
              "data": {
                "gallery_items": [
                  {
                    "caption": null,
                    "link": {
                      "link_type": "Any"
                    },
                    "video_media": {
                      "link_type": "Media"
                    },
                    "video_url": null,
                    "media": {
                      "dimensions": {
                        "width": 2464,
                        "height": 1848
                      },
                      "alt": null,
                      "copyright": null,
                      "url": "https://images.prismic.io/the-grand/a9c115b0-9df7-4c25-90e4-d8579107f45e_glb-events-business-03.jpg?auto=compress,format",
                      "id": "ZNcSWRAAACgAok29",
                      "edit": {
                        "x": 0,
                        "y": 0,
                        "zoom": 1,
                        "background": "#fff"
                      }
                    }
                  },
                  {
                    "caption": null,
                    "link": {
                      "link_type": "Any"
                    },
                    "video_media": {
                      "link_type": "Media"
                    },
                    "video_url": null,
                    "media": {
                      "dimensions": {
                        "width": 2464,
                        "height": 1848
                      },
                      "alt": null,
                      "copyright": null,
                      "url": "https://images.prismic.io/the-grand/88c4e0ad-5f0c-47ac-98ea-059b4632263d_glb-events-business-02.jpg?auto=compress,format",
                      "id": "ZNcSVxAAACYAok2z",
                      "edit": {
                        "x": 0,
                        "y": 0,
                        "zoom": 1,
                        "background": "#fff"
                      }
                    }
                  },
                  {
                    "caption": null,
                    "link": {
                      "link_type": "Any"
                    },
                    "video_media": {
                      "link_type": "Media"
                    },
                    "video_url": null,
                    "media": {
                      "dimensions": {
                        "width": 2464,
                        "height": 1848
                      },
                      "alt": null,
                      "copyright": null,
                      "url": "https://images.prismic.io/the-grand/99eadb3b-11a2-4938-bad6-bb153274b732_glb-events-business-01.jpg?auto=compress,format",
                      "id": "ZNcSVxAAACkAok2y",
                      "edit": {
                        "x": 0,
                        "y": 0,
                        "zoom": 1,
                        "background": "#fff"
                      }
                    }
                  }
                ]
              },
              "link_type": "Document",
              "key": "f2627457-8103-484d-b4ad-9b20ead75831",
              "isBroken": false
            },
            "video_media": {
              "link_type": "Media"
            },
            "video_url": null,
            "media": {},
            "top_spacer": null,
            "bottom_spacer": null,
            "asset_position": false
          },
          "items": [
            {
              "media": {},
              "headline_size": null,
              "headline": [
                {
                  "type": "heading1",
                  "text": "5",
                  "spans": []
                }
              ],
              "eyebrow": "Average meetings per week",
              "body": [],
              "primary_action_text": null,
              "primary_action_link": {
                "link_type": "Any"
              },
              "secondary_action_text": null,
              "secondary_action_link": {
                "link_type": "Any"
              }
            },
            {
              "media": {},
              "headline_size": null,
              "headline": [
                {
                  "type": "heading1",
                  "text": "780 ",
                  "spans": []
                }
              ],
              "eyebrow": "Meetings last year",
              "body": [],
              "primary_action_text": null,
              "primary_action_link": {
                "link_type": "Any"
              },
              "secondary_action_text": null,
              "secondary_action_link": {
                "link_type": "Any"
              }
            },
            {
              "media": {},
              "headline_size": null,
              "headline": [
                {
                  "type": "heading1",
                  "text": "Thursday",
                  "spans": []
                }
              ],
              "eyebrow": "Most popular meeting day",
              "body": [],
              "primary_action_text": null,
              "primary_action_link": {
                "link_type": "Any"
              },
              "secondary_action_text": null,
              "secondary_action_link": {
                "link_type": "Any"
              }
            },
            {
              "media": {},
              "headline_size": null,
              "headline": [
                {
                  "type": "heading1",
                  "text": "55",
                  "spans": []
                }
              ],
              "eyebrow": "Average meeting attendance",
              "body": [],
              "primary_action_text": null,
              "primary_action_link": {
                "link_type": "Any"
              },
              "secondary_action_text": null,
              "secondary_action_link": {
                "link_type": "Any"
              }
            }
          ]
        }
      ],
      "meta_title": null,
      "meta_description": null,
      "meta_image": {}
    }
  },
  "weddings": {
    "uid": "weddings",
    "data": {
      "title": "Weddings",
      "headline": "Let's get married",
      "caption": "Your dream wedding, made simple.",
      "gallery": [],
      "video_media": null,
      "video_url": null,
      "media": {},
      "slices": [
        {
          "id": "image_section$e3b9b633-84f0-4fcd-bb24-fefc1ac4a215",
          "slice_type": "image_section",
          "primary": {
            "section_id": null,
            "gallery": {
              "link_type": "Document"
            },
            "video_media": {
              "link_type": "Media"
            },
            "video_url": null,
            "media": {
              "dimensions": {
                "width": 2816,
                "height": 1826
              },
              "alt": null,
              "copyright": null,
              "url": "https://images.prismic.io/the-grand/57b63738-193f-4d7f-a3bb-13d37b4203ae_glb-events-wedding.jpg?auto=compress,format",
              "id": "ZNcYvBAAACYAomno",
              "edit": {
                "x": 0,
                "y": 0,
                "zoom": 1,
                "background": "#fff"
              }
            },
            "top_spacer": null,
            "bottom_spacer": "None"
          },
          "items": [
            {}
          ]
        },
        {
          "id": "text_section$e6b35027-2a66-45d4-a0ca-c9746cf31b47",
          "slice_type": "text_section",
          "primary": {
            "section_id": "intro",
            "eyebrow": null,
            "body": [
              {
                "type": "paragraph",
                "text": "A wedding is a truly amazing moment in life, and we would love to help make it special and memorable. We offer a range of wedding packages to fit any budget or style, from intimate ceremonies to elaborate ballroom receptions. Let us help make your day perfect and truly unforgettable.",
                "spans": []
              }
            ],
            "primary_action": "Plan your wedding",
            "primary_action_link": {
              "id": "ZC5YBhAAACEA0ymB",
              "type": "inquire_page",
              "tags": [],
              "lang": "en-us",
              "slug": "inquire-page",
              "first_publication_date": "2023-04-06T05:28:37+0000",
              "last_publication_date": "2023-04-06T05:28:37+0000",
              "uid": "inquire",
              "link_type": "Document",
              "key": "c01f7dda-f532-486a-a859-d9fc395e32f2",
              "isBroken": false
            },
            "secondary_action": null,
            "secondary_action_link": {
              "link_type": "Any"
            },
            "top_spacer": "Small",
            "top_border": null,
            "bottom_spacer": "Small",
            "bottom_border": null
          },
          "items": [
            {}
          ]
        },
        {
          "id": "numbers_section$de8b953e-4bbc-4080-ba41-304237b73f1e",
          "slice_type": "numbers_section",
          "primary": {
            "section_id": "features",
            "title": null,
            "description": null,
            "columns": "3 Column",
            "inset": null,
            "top_spacer": "None",
            "top_border": true,
            "bottom_spacer": "Medium",
            "bottom_border": true
          },
          "items": [
            {
              "media": {
                "dimensions": {
                  "width": 85,
                  "height": 84
                },
                "alt": null,
                "copyright": null,
                "url": "https://the-grand.cdn.prismic.io/the-grand/e36092fd-2316-42f4-b510-936b1a3d1ef2_elegant.svg",
                "id": "ZGVJpBAAACAAd5xv",
                "edit": {
                  "x": 0,
                  "y": 0,
                  "zoom": 1,
                  "background": "#fff"
                }
              },
              "number": [],
              "eyebrow": "Elegant",
              "body": [
                {
                  "type": "paragraph",
                  "text": "Our spacious ballrooms and elegant dining rooms provide the perfect setting for your wedding ceremony and reception.",
                  "spans": []
                }
              ],
              "action_text": null,
              "action_link": {
                "link_type": "Any"
              }
            },
            {
              "media": {
                "dimensions": {
                  "width": 85,
                  "height": 84
                },
                "alt": null,
                "copyright": null,
                "url": "https://the-grand.cdn.prismic.io/the-grand/c09bb552-df46-461d-88a1-63edd8f1f7a7_flexible.svg",
                "id": "ZGVJpBAAACEAd5xw",
                "edit": {
                  "x": 0,
                  "y": 0,
                  "zoom": 1,
                  "background": "#fff"
                }
              },
              "number": [],
              "eyebrow": "Versatility",
              "body": [
                {
                  "type": "paragraph",
                  "text": "Our venue is versatile enough to accommodate a variety of wedding styles, from traditional to modern.",
                  "spans": []
                }
              ],
              "action_text": null,
              "action_link": {
                "link_type": "Any"
              }
            },
            {
              "media": {
                "dimensions": {
                  "width": 85,
                  "height": 84
                },
                "alt": null,
                "copyright": null,
                "url": "https://the-grand.cdn.prismic.io/the-grand/c1aebc83-c2ff-40f9-9b8e-932fa8270f31_personal.svg",
                "id": "ZGVJpBAAACAAd5xx",
                "edit": {
                  "x": 0,
                  "y": 0,
                  "zoom": 1,
                  "background": "#fff"
                }
              },
              "number": [],
              "eyebrow": "Personal",
              "body": [
                {
                  "type": "paragraph",
                  "text": "Our experienced wedding planners will work with you to create a wedding that is truly personal and reflects your unique style.",
                  "spans": []
                }
              ],
              "action_text": null,
              "action_link": {
                "link_type": "Any"
              }
            }
          ]
        },
        {
          "id": "split_scroll_section$8e61484a-28cb-4905-93c4-7cfe094e6c42",
          "slice_type": "split_scroll_section",
          "primary": {
            "section_id": "list",
            "gallery": {
              "id": "ZNcQ5BAAACkAokdL",
              "type": "fragment_gallery",
              "tags": [],
              "lang": "en-us",
              "slug": "events-weddings-scroll",
              "first_publication_date": "2023-08-12T04:57:50+0000",
              "last_publication_date": "2023-08-12T05:01:20+0000",
              "uid": "events-weddings-scroll",
              "data": {
                "gallery_items": [
                  {
                    "caption": null,
                    "link": {
                      "link_type": "Any"
                    },
                    "video_media": {
                      "link_type": "Media"
                    },
                    "video_url": null,
                    "media": {
                      "dimensions": {
                        "width": 2466,
                        "height": 1850
                      },
                      "alt": null,
                      "copyright": null,
                      "url": "https://images.prismic.io/the-grand/21ffdf36-273b-4a0d-b43d-b4963d096f49_glb-events-wedding-01.jpg?auto=compress,format",
                      "id": "ZNcRChAAACcAokf3",
                      "edit": {
                        "x": 0,
                        "y": 0,
                        "zoom": 1,
                        "background": "#fff"
                      }
                    }
                  },
                  {
                    "caption": null,
                    "link": {
                      "link_type": "Any"
                    },
                    "video_media": {
                      "link_type": "Media"
                    },
                    "video_url": null,
                    "media": {
                      "dimensions": {
                        "width": 2464,
                        "height": 1848
                      },
                      "alt": null,
                      "copyright": null,
                      "url": "https://images.prismic.io/the-grand/92798031-cee8-4a2b-bea5-5c18a8a14424_glb-broll-07.jpg?auto=compress,format",
                      "id": "ZNcSDBAAACgAokxf",
                      "edit": {
                        "x": 0,
                        "y": 0,
                        "zoom": 1,
                        "background": "#fff"
                      }
                    }
                  },
                  {
                    "caption": null,
                    "link": {
                      "link_type": "Any"
                    },
                    "video_media": {
                      "link_type": "Media"
                    },
                    "video_url": null,
                    "media": {
                      "dimensions": {
                        "width": 2466,
                        "height": 1850
                      },
                      "alt": null,
                      "copyright": null,
                      "url": "https://images.prismic.io/the-grand/6bd76197-93b0-44a3-ac40-f47f22a5cd70_glb-events-wedding-03.jpg?auto=compress,format",
                      "id": "ZNcRChAAACkAokf2",
                      "edit": {
                        "x": 0,
                        "y": 0,
                        "zoom": 1,
                        "background": "#fff"
                      }
                    }
                  },
                  {
                    "caption": null,
                    "link": {
                      "link_type": "Any"
                    },
                    "video_media": {
                      "link_type": "Media"
                    },
                    "video_url": null,
                    "media": {
                      "dimensions": {
                        "width": 2467,
                        "height": 1850
                      },
                      "alt": null,
                      "copyright": null,
                      "url": "https://images.prismic.io/the-grand/e7017c18-9fad-4ba4-9856-4d2ce836479f_glb-events-wedding-02.jpg?auto=compress,format",
                      "id": "ZNcRCxAAACgAokf8",
                      "edit": {
                        "x": 0,
                        "y": 0,
                        "zoom": 1,
                        "background": "#fff"
                      }
                    }
                  },
                  {
                    "caption": null,
                    "link": {
                      "link_type": "Any"
                    },
                    "video_media": {
                      "link_type": "Media"
                    },
                    "video_url": null,
                    "media": {
                      "dimensions": {
                        "width": 1850,
                        "height": 2466
                      },
                      "alt": null,
                      "copyright": null,
                      "url": "https://images.prismic.io/the-grand/ed1c69c1-4367-46aa-96b7-a3d261ca78ca_glb-broll-01.jpg?auto=compress,format",
                      "id": "ZNcSDhAAACYAokxp",
                      "edit": {
                        "x": 0,
                        "y": 0,
                        "zoom": 1,
                        "background": "#fff"
                      }
                    }
                  }
                ]
              },
              "link_type": "Document",
              "key": "bb9cbe90-9bcf-4caf-8070-e2a3a6a898fe",
              "isBroken": false
            },
            "video_media": {
              "link_type": "Media"
            },
            "video_url": null,
            "media": {},
            "top_spacer": null,
            "bottom_spacer": null,
            "asset_position": false
          },
          "items": [
            {
              "media": {},
              "headline_size": null,
              "headline": [
                {
                  "type": "heading1",
                  "text": "25",
                  "spans": []
                }
              ],
              "eyebrow": "Average couple age",
              "body": [],
              "primary_action_text": null,
              "primary_action_link": {
                "link_type": "Any"
              },
              "secondary_action_text": null,
              "secondary_action_link": {
                "link_type": "Any"
              }
            },
            {
              "media": {},
              "headline_size": null,
              "headline": [
                {
                  "type": "heading1",
                  "text": "400+",
                  "spans": []
                }
              ],
              "eyebrow": "Weddings last year:",
              "body": [],
              "primary_action_text": null,
              "primary_action_link": {
                "link_type": "Any"
              },
              "secondary_action_text": null,
              "secondary_action_link": {
                "link_type": "Any"
              }
            },
            {
              "media": {},
              "headline_size": null,
              "headline": [
                {
                  "type": "heading1",
                  "text": "4 hrs",
                  "spans": []
                }
              ],
              "eyebrow": "Average wedding duration",
              "body": [],
              "primary_action_text": null,
              "primary_action_link": {
                "link_type": "Any"
              },
              "secondary_action_text": null,
              "secondary_action_link": {
                "link_type": "Any"
              }
            },
            {
              "media": {},
              "headline_size": null,
              "headline": [
                {
                  "type": "heading1",
                  "text": "Saturday",
                  "spans": []
                }
              ],
              "eyebrow": "Most popular wedding day",
              "body": [
                {
                  "type": "paragraph",
                  "text": "Talk to our sales team about discounts for other days of the week.",
                  "spans": []
                }
              ],
              "primary_action_text": null,
              "primary_action_link": {
                "link_type": "Any"
              },
              "secondary_action_text": null,
              "secondary_action_link": {
                "link_type": "Any"
              }
            },
            {
              "media": {},
              "headline_size": null,
              "headline": [
                {
                  "type": "heading1",
                  "text": "320",
                  "spans": []
                }
              ],
              "eyebrow": "Average number of wedding guests",
              "body": [],
              "primary_action_text": null,
              "primary_action_link": {
                "link_type": "Any"
              },
              "secondary_action_text": null,
              "secondary_action_link": {
                "link_type": "Any"
              }
            }
          ]
        }
      ],
      "meta_title": null,
      "meta_description": null,
      "meta_image": {}
    }
  }
};

/** UIDs for generateStaticParams */
export const eventPageUids = [
  "milestones",
  "business",
  "weddings"
];
