// Auto-generated by scripts/migrate-from-prismic.ts
// To regenerate: npx tsx scripts/migrate-from-prismic.ts
// Offsite index page content (replaces Prismic offsite_index_page uid='offsite')

import type { Content } from "@prismicio/client";

export const offsiteIndexPage = {
  "id": "ZC5XrRAAACMA0yj6",
  "uid": "offsite",
  "url": null,
  "type": "offsite_index_page",
  "href": "https://the-grand.cdn.prismic.io/api/v2/documents/search?ref=aY7e8hEAACQAAXJd&q=%5B%5B%3Ad+%3D+at%28document.id%2C+%22ZC5XrRAAACMA0yj6%22%29+%5D%5D",
  "tags": [],
  "first_publication_date": "2023-04-06T05:28:38+0000",
  "last_publication_date": "2023-04-06T05:28:38+0000",
  "slugs": [
    "offsite-index-page"
  ],
  "linked_documents": [],
  "lang": "en-us",
  "alternate_languages": [],
  "data": {
    "title": "The Grand Offsite Catering",
    "gallery": {
      "link_type": "Document"
    },
    "video_media": {
      "link_type": "Media"
    },
    "video_url": null,
    "media": {},
    "slices": [],
    "meta_title": null,
    "meta_description": null,
    "meta_image": {}
  }
} as unknown as Content.OffsiteIndexPageDocument;
