// Auto-generated by scripts/migrate-from-prismic.ts
// To regenerate: npx tsx scripts/migrate-from-prismic.ts
// Offsite index page content

import type { PageDoc } from "content/types";

export const offsiteIndexPage: PageDoc = {
  "uid": "offsite",
  "data": {
    "title": "The Grand Offsite Catering",
    "gallery": [],
    "video_media": null,
    "video_url": null,
    "media": {},
    "slices": [],
    "meta_title": null,
    "meta_description": null,
    "meta_image": {}
  }
};
