// Auto-generated by scripts/migrate-from-prismic.ts
// To regenerate: npx tsx scripts/migrate-from-prismic.ts
// Contact page content

import type { PageDoc } from "content/types";

export const contactPage: PageDoc = {
  "uid": "contact",
  "data": {
    "title": "Contact The Grand",
    "gallery": [],
    "video_media": null,
    "video_url": null,
    "media": {},
    "slices": [
      {
        "id": "hero_detail_page_slice$1144f9a4-e557-4b30-9403-4616e6a6d90c",
        "slice_type": "hero_detail_page_slice",
        "primary": {
          "section_id": "hero",
          "title": null,
          "headline": "SAY HEY",
          "caption": "However you'd like",
          "video_media": {
            "link_type": "Media"
          },
          "video_url": null,
          "media": {},
          "primary_action": null,
          "primary_action_link": {
            "link_type": "Any"
          },
          "bottom_spacer": null
        },
        "items": [
          {}
        ]
      },
      {
        "id": "tile_grid$d596563d-06a3-47ef-b0d9-90ba16ec29e3",
        "slice_type": "tile_grid",
        "primary": {
          "section_id": null,
          "headline": null,
          "body": null,
          "theme": "Cream",
          "top_spacer": null,
          "bottom_spacer": null
        },
        "items": [
          {
            "card_fragment": {
              "link_type": "Document"
            },
            "media": {},
            "eyebrow": null,
            "headline": "Submit an inquiry",
            "body": null,
            "link": {
              "id": "ZC5YBhAAACEA0ymB",
              "type": "inquire_page",
              "tags": [],
              "lang": "en-us",
              "slug": "inquire-page",
              "first_publication_date": "2023-04-06T05:28:37+0000",
              "last_publication_date": "2023-04-06T05:28:37+0000",
              "uid": "inquire",
              "link_type": "Document",
              "key": "e3dbafe7-5cd8-4e49-9c82-f8f2a80e806a",
              "isBroken": false
            },
            "theme": "Outlined",
            "size": null,
            "direction": null,
            "col_start": "Start 2",
            "col_span": "Span 10",
            "row_start": null,
            "row_span": null
          },
          {
            "card_fragment": {
              "link_type": "Document"
            },
            "media": {},
            "eyebrow": null,
            "headline": "Call us at (562) 426-0555",
            "body": null,
            "link": {
              "link_type": "Web",
              "key": "8fa0a6b0-793a-4768-b927-afb0bf2e2d4f",
              "url": "tel:+15624260555",
              "target": "_blank"
            },
            "theme": "Outlined",
            "size": null,
            "direction": null,
            "col_start": "Start 2",
            "col_span": "Span 10",
            "row_start": null,
            "row_span": null
          },
          {
            "card_fragment": {
              "link_type": "Document"
            },
            "media": {},
            "eyebrow": null,
            "headline": "Email us at dan@grandfandb.com",
            "body": null,
            "link": {
              "link_type": "Web",
              "key": "bdfeed98-67ed-474b-9138-8495116ba089",
              "url": "mailto:dan@grandfandb.com",
              "target": "_blank"
            },
            "theme": "Outlined",
            "size": null,
            "direction": null,
            "col_start": "Start 2",
            "col_span": "Span 10",
            "row_start": null,
            "row_span": null
          },
          {
            "card_fragment": {
              "link_type": "Document"
            },
            "media": {},
            "eyebrow": null,
            "headline": "Instagram",
            "body": null,
            "link": {
              "link_type": "Web",
              "key": "78d044df-0850-453b-9d87-237315cd9d1d",
              "url": "https://www.instagram.com/thegrandlb/",
              "target": "_blank"
            },
            "theme": "Outlined",
            "size": null,
            "direction": null,
            "col_start": "Start 2",
            "col_span": "Span 5",
            "row_start": null,
            "row_span": null
          },
          {
            "card_fragment": {
              "link_type": "Document"
            },
            "media": {},
            "eyebrow": null,
            "headline": "Facebook",
            "body": null,
            "link": {
              "link_type": "Web",
              "key": "1efcff06-3831-42da-a388-9c62e6a052d6",
              "url": "https://www.facebook.com/TheGrandLB/",
              "target": "_blank"
            },
            "theme": "Outlined",
            "size": null,
            "direction": null,
            "col_start": "Start 7",
            "col_span": "Span 5",
            "row_start": null,
            "row_span": null
          }
        ]
      }
    ],
    "meta_title": null,
    "meta_description": null,
    "meta_image": {}
  }
};
