// Auto-generated by scripts/migrate-from-prismic.ts
// To regenerate: npx tsx scripts/migrate-from-prismic.ts
// General pages — uid-keyed map (replaces Prismic page type with general_page tag)

import type { Content } from "@prismicio/client";

export const generalPages: Record<string, Content.PageDocument> = {
  "privacy": {
    "id": "ZKO4qxEAACkAk8oH",
    "uid": "privacy",
    "url": null,
    "type": "page",
    "href": "https://the-grand.cdn.prismic.io/api/v2/documents/search?ref=aY7e8hEAACQAAXJd&q=%5B%5B%3Ad+%3D+at%28document.id%2C+%22ZKO4qxEAACkAk8oH%22%29+%5D%5D",
    "tags": [
      "general_page"
    ],
    "first_publication_date": "2023-07-04T06:29:15+0000",
    "last_publication_date": "2023-07-05T05:54:13+0000",
    "slugs": [
      "definitions",
      "privacy-policy"
    ],
    "linked_documents": [],
    "lang": "en-us",
    "alternate_languages": [],
    "data": {
      "title": "Privacy Policy",
      "gallery": {
        "link_type": "Document"
      },
      "video_media": {
        "link_type": "Media"
      },
      "video_url": null,
      "media": {},
      "slices": [
        {
          "variation": "default",
          "version": "initial",
          "items": [
            {}
          ],
          "primary": {
            "section_id": null,
            "title": null,
            "headline": "Privacy Policy",
            "caption": null,
            "video_media": {
              "link_type": "Media"
            },
            "video_url": null,
            "media": {},
            "primary_action": null,
            "primary_action_link": {
              "link_type": "Any"
            },
            "bottom_spacer": null
          },
          "id": "hero_detail_page_slice$8233d735-2147-491b-9dfa-b8814012c151",
          "slice_type": "hero_detail_page_slice",
          "slice_label": null
        },
        {
          "variation": "default",
          "version": "initial",
          "items": [
            {}
          ],
          "primary": {
            "section_id": "legal",
            "text": [
              {
                "type": "paragraph",
                "text": "Choura Venue Services LLC (\"us\", \"we\", or \"our\") operates the https://thegrandlb.com website (hereinafter referred to as the \"Service\").",
                "spans": [
                  {
                    "start": 62,
                    "end": 84,
                    "type": "hyperlink",
                    "data": {
                      "link_type": "Web",
                      "url": "https://thegrandlb.com/",
                      "target": "_blank"
                    }
                  }
                ]
              },
              {
                "type": "paragraph",
                "text": "This page informs you of our policies regarding the collection, use and disclosure of personal data when you use our Service and the choices you have associated with that data.",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, accessible from https://thegrandlb.com.",
                "spans": [
                  {
                    "start": 316,
                    "end": 338,
                    "type": "hyperlink",
                    "data": {
                      "link_type": "Web",
                      "url": "https://thegrandlb.com/",
                      "target": "_blank"
                    }
                  }
                ]
              },
              {
                "type": "paragraph",
                "text": "",
                "spans": []
              },
              {
                "type": "heading2",
                "text": "Definitions",
                "spans": []
              },
              {
                "type": "heading3",
                "text": "Service",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "Service is the https://thegrandlb.com website operated by Choura Venue Services LLC.",
                "spans": [
                  {
                    "start": 15,
                    "end": 37,
                    "type": "hyperlink",
                    "data": {
                      "link_type": "Web",
                      "url": "https://thegrandlb.com/",
                      "target": "_blank"
                    }
                  }
                ]
              },
              {
                "type": "heading3",
                "text": "Personal Data",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).",
                "spans": []
              },
              {
                "type": "heading3",
                "text": "Usage Data",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).",
                "spans": []
              },
              {
                "type": "heading3",
                "text": "Cookies",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "Cookies are small files stored on your device (computer or mobile device).",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "",
                "spans": []
              },
              {
                "type": "heading2",
                "text": "Information Collection and Use",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "We collect several different types of information for various purposes to provide and improve our Service to you.",
                "spans": []
              },
              {
                "type": "heading3",
                "text": "Types of Data Collected",
                "spans": []
              },
              {
                "type": "heading4",
                "text": "1. Personal Data",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you (\"Personal Data\"). Personally identifiable information may include, but is not limited to:",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "- Email address",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "- First name and last name",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "- Phone number",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "- Cookies and Usage Data.",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or the instructions provided in any email we send.",
                "spans": []
              },
              {
                "type": "heading4",
                "text": "2. Usage Data",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "We may also collect information on how the Service is accessed and used (\"Usage Data\"). This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.",
                "spans": []
              },
              {
                "type": "heading4",
                "text": "3. Tracking & Cookies Data",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyze our Service.",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "Examples of Cookies we use:",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "- Session Cookies. We use Session Cookies to operate our Service.",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "- Preference Cookies. We use Preference Cookies to remember your preferences and various settings.",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "- Security Cookies. We use Security Cookies for security purposes.",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "",
                "spans": []
              },
              {
                "type": "heading2",
                "text": "Use of Data",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "Choura Venue Services LLC uses the collected data for various purposes:",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "- To provide and maintain our Service",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "- To notify you about changes to our Service",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "- To allow you to participate in interactive features of our Service when you choose to do so",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "- To provide customer support",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "- To gather analysis or valuable information so that we can improve our Service",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "- To monitor the usage of our Service",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "- To detect, prevent and address technical issues",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "- To provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "",
                "spans": []
              },
              {
                "type": "heading2",
                "text": "Transfer of Data",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "Your information, including Personal Data, may be transferred to - and maintained on - computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "If you are located outside United States and choose to provide information to us, please note that we transfer the data, including Personal Data, to United States and process it there.",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "Choura Venue Services LLC will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "",
                "spans": []
              },
              {
                "type": "heading2",
                "text": "Disclosure of Data",
                "spans": []
              },
              {
                "type": "heading4",
                "text": "1. Legal Requirements",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "Choura Venue Services LLC may disclose your Personal Data in the good faith belief that such action is necessary to:",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "- To comply with a legal obligation",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "- To protect and defend the rights or property of Choura Venue Services LLC",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "- To prevent or investigate possible wrongdoing in connection with the",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "Service",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "- To protect the personal safety of users of the Service or the public",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "- To protect against legal liability",
                "spans": []
              },
              {
                "type": "heading4",
                "text": "2. Security of Data",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "Our Policy on \"Do Not Track\" Signals under the California Online Protection Act (CalOPPA)",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "We do not support Do Not Track (\"DNT\"). Do Not Track is a preference you can set in your web browser to inform websites that you do not want to be tracked.",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "You can enable or disable Do Not Track by visiting the Preferences or Settings page of your web browser.",
                "spans": []
              },
              {
                "type": "heading4",
                "text": "3. Service Providers",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "We may employ third party companies and individuals to facilitate our Service (\"Service Providers\"), provide the Service on our behalf, perform Service- related services or assist us in analyzing how our Service is used.",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.",
                "spans": []
              },
              {
                "type": "heading4",
                "text": "4. Analytics",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "We may use third-party Service Providers to monitor and analyze the use of our Service.",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "**Google Analytics:**",
                "spans": [
                  {
                    "start": 0,
                    "end": 21,
                    "type": "strong"
                  }
                ]
              },
              {
                "type": "paragraph",
                "text": "- Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualize and personalize the ads of its own advertising network.",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "- You can opt-out of having made your activity on the Service available to Google Analytics by installing the Google Analytics opt-out browser add-on. The add-on prevents the Google Analytics JavaScript (ga.js, analytics.js and dc.js) from sharing information with Google Analytics about visits activity.",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "- For more information on the privacy practices of Google, please visit the Google Privacy & Terms web page: https://policies.google.com/privacy?hl=en",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "**Hotjar:**",
                "spans": [
                  {
                    "start": 0,
                    "end": 11,
                    "type": "strong"
                  }
                ]
              },
              {
                "type": "paragraph",
                "text": "- We also use Hotjar to understand user behavior and improve our website. Hotjar may collect information such as your device's IP address, browser type, and pages visited on our site. Hotjar may also collect feedback from you about your experience on our website. This information helps us improve our website and services for our users.",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "- For more information about Hotjar's privacy practices, please visit their Privacy Policy at https://www.hotjar.com/legal/policies/privacy/.",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "",
                "spans": []
              },
              {
                "type": "heading2",
                "text": "Links to Other Sites",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "",
                "spans": []
              },
              {
                "type": "heading2",
                "text": "Children's Privacy",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "Our Service does not address anyone under the age of 18 (\"Children\").",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "",
                "spans": []
              },
              {
                "type": "heading2",
                "text": "Changes to This Privacy Policy",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update the \"effective date\" at the top of this Privacy Policy.",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "",
                "spans": []
              },
              {
                "type": "heading2",
                "text": "Contact Us",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "If you have any questions about this Privacy Policy, please contact us:",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "- By email: dan@grandfandb.com",
                "spans": [
                  {
                    "start": 12,
                    "end": 30,
                    "type": "hyperlink",
                    "data": {
                      "link_type": "Web",
                      "url": "mailto:dan@grandfandb.com",
                      "target": "_blank"
                    }
                  }
                ]
              },
              {
                "type": "paragraph",
                "text": "- By phone number: 5624260555",
                "spans": [
                  {
                    "start": 19,
                    "end": 29,
                    "type": "hyperlink",
                    "data": {
                      "link_type": "Web",
                      "url": "tel:+15624260555",
                      "target": "_blank"
                    }
                  }
                ]
              },
              {
                "type": "paragraph",
                "text": "",
                "spans": []
              },
              {
                "type": "heading1",
                "text": "Addendum",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "",
                "spans": []
              },
              {
                "type": "heading2",
                "text": "Accessibility Statement",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "Choura Venue Services LLC (operating as The Grand Long Beach) is committed to ensuring that our website is accessible to people with disabilities. We strive to comply with Web Content Accessibility Guidelines (WCAG) 2.1 Level AA. If you encounter any accessibility issues or have suggestions for improving the accessibility of our website, please contact us at dan@grandfandb.com.",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "",
                "spans": []
              },
              {
                "type": "heading2",
                "text": "Disclaimer",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "The information provided on Choura Venue Services LLC (operating as The Grand Long Beach) website is for general informational purposes only. While we strive to keep the information up-to-date and accurate, we make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability, or availability of the information, products, services, or related graphics contained on the website for any purpose. Any reliance you place on such information is therefore strictly at your own risk.",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "",
                "spans": []
              },
              {
                "type": "heading2",
                "text": "Copyright Notice",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "All content on this website, including text, graphics, logos, images, and software, is the property of Choura Venue Services LLC (operating as The Grand Long Beach) or its content suppliers and is protected by international copyright laws. Unauthorized use, copying, or distribution of any content from this website is strictly prohibited.",
                "spans": []
              }
            ],
            "top_spacer": null,
            "top_border": null,
            "bottom_spacer": null,
            "bottom_border": null
          },
          "id": "longform_text_section$68f7b494-543d-4893-b522-e5377c72cd25",
          "slice_type": "longform_text_section",
          "slice_label": null
        }
      ],
      "meta_title": null,
      "meta_description": null,
      "meta_image": {}
    }
  },
  "rich-text": {
    "id": "ZKUF5hEAACIAGMLS",
    "uid": "rich-text",
    "url": null,
    "type": "page",
    "href": "https://the-grand.cdn.prismic.io/api/v2/documents/search?ref=aY7e8hEAACQAAXJd&q=%5B%5B%3Ad+%3D+at%28document.id%2C+%22ZKUF5hEAACIAGMLS%22%29+%5D%5D",
    "tags": [
      "general_page"
    ],
    "first_publication_date": "2023-07-05T05:55:53+0000",
    "last_publication_date": "2023-07-05T05:57:43+0000",
    "slugs": [
      "headline-1"
    ],
    "linked_documents": [],
    "lang": "en-us",
    "alternate_languages": [],
    "data": {
      "title": "Rich Text",
      "gallery": {
        "link_type": "Document"
      },
      "video_media": {
        "link_type": "Media"
      },
      "video_url": null,
      "media": {},
      "slices": [
        {
          "variation": "default",
          "version": "initial",
          "items": [
            {}
          ],
          "primary": {
            "section_id": null,
            "title": null,
            "headline": "Rich Text",
            "caption": null,
            "video_media": {
              "link_type": "Media"
            },
            "video_url": null,
            "media": {},
            "primary_action": null,
            "primary_action_link": {
              "link_type": "Any"
            },
            "bottom_spacer": null
          },
          "id": "hero_detail_page_slice$e68abc82-a7d1-4095-a4b0-e3fec95eceb7",
          "slice_type": "hero_detail_page_slice",
          "slice_label": null
        },
        {
          "variation": "default",
          "version": "initial",
          "items": [
            {}
          ],
          "primary": {
            "section_id": null,
            "text": [
              {
                "type": "heading1",
                "text": "Headline 1",
                "spans": []
              },
              {
                "type": "heading2",
                "text": "Headline 2",
                "spans": []
              },
              {
                "type": "heading3",
                "text": "Headline 3",
                "spans": []
              },
              {
                "type": "heading4",
                "text": "Headline 4",
                "spans": []
              },
              {
                "type": "heading5",
                "text": "Headline 5",
                "spans": []
              },
              {
                "type": "heading6",
                "text": "Headline 6",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "Cras justo odio, dapibus ac facilisis in, egestas eget quam. Maecenas sed diam eget risus varius blandit sit amet non magna. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla vitae elit libero, a pharetra augue. Maecenas faucibus mollis interdum.",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper.",
                "spans": []
              },
              {
                "type": "paragraph",
                "text": "Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec ullamcorper nulla non metus auctor fringilla. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Curabitur blandit tempus porttitor.",
                "spans": []
              }
            ],
            "top_spacer": null,
            "top_border": null,
            "bottom_spacer": null,
            "bottom_border": null
          },
          "id": "longform_text_section$3f59a207-fd2f-46b0-a944-78bcaea89a5d",
          "slice_type": "longform_text_section",
          "slice_label": null
        }
      ],
      "meta_title": null,
      "meta_description": null,
      "meta_image": {}
    }
  },
  "footer": {
    "id": "ZKUIIhEAACEAGMzf",
    "uid": "footer",
    "url": null,
    "type": "page",
    "href": "https://the-grand.cdn.prismic.io/api/v2/documents/search?ref=aY7e8hEAACQAAXJd&q=%5B%5B%3Ad+%3D+at%28document.id%2C+%22ZKUIIhEAACEAGMzf%22%29+%5D%5D",
    "tags": [
      "general_page"
    ],
    "first_publication_date": "2023-07-05T06:05:26+0000",
    "last_publication_date": "2023-07-05T06:05:26+0000",
    "slugs": [
      "footer"
    ],
    "linked_documents": [],
    "lang": "en-us",
    "alternate_languages": [],
    "data": {
      "title": "Footer",
      "gallery": {
        "link_type": "Document"
      },
      "video_media": {
        "link_type": "Media"
      },
      "video_url": null,
      "media": {},
      "slices": [],
      "meta_title": null,
      "meta_description": null,
      "meta_image": {}
    }
  },
  "map": {
    "id": "ZD9uPxAAACMAn2so",
    "uid": "map",
    "url": null,
    "type": "page",
    "href": "https://the-grand.cdn.prismic.io/api/v2/documents/search?ref=aY7e8hEAACQAAXJd&q=%5B%5B%3Ad+%3D+at%28document.id%2C+%22ZD9uPxAAACMAn2so%22%29+%5D%5D",
    "tags": [],
    "first_publication_date": "2023-04-19T04:30:14+0000",
    "last_publication_date": "2023-04-19T04:30:14+0000",
    "slugs": [
      "interactive-map"
    ],
    "linked_documents": [],
    "lang": "en-us",
    "alternate_languages": [],
    "data": {
      "title": "Interactive Map",
      "gallery": {
        "link_type": "Document"
      },
      "video_media": {
        "link_type": "Media"
      },
      "video_url": null,
      "media": {},
      "slices": [],
      "meta_title": null,
      "meta_description": null,
      "meta_image": {}
    }
  }
} as unknown as Record<string, Content.PageDocument>;

/** Sorted UIDs for generateStaticParams */
export const generalPageUids = [
  "privacy",
  "rich-text",
  "footer",
  "map"
];
