// Code generated by Slice Machine. DO NOT EDIT.

import ColumnSection from './ColumnSection';
import FaqSection from './FaqSection';
import HomepageLocation from './HomepageLocation';
import HomepageNumbers from './HomepageNumbers';
import MainHero from './MainHero';
import MomentsScrollSection from './MomentsScrollSection';
import ScrollText from './ScrollText';
import SplitGallery from './SplitGallery';
import SplitScrollSection from './SplitScrollSection';
import StarSection from './StarSection';
import TextSection from './TextSection';
import TileGrid from './TileGrid';

export {
	ColumnSection,
	FaqSection,
	HomepageLocation,
	HomepageNumbers,
	MainHero,
	MomentsScrollSection,
	ScrollText,
	SplitGallery,
	SplitScrollSection,
	StarSection,
	TextSection,
	TileGrid,
};

export const components = {
	numbers_section: ColumnSection,
	faq_section: FaqSection,
	homepage_location: HomepageLocation,
	homepage_numbers: HomepageNumbers,
	page_hero: MainHero,
	moments_scroll_section: MomentsScrollSection,
	scroll_text: ScrollText,
	split_gallery: SplitGallery,
	split_scroll_section: SplitScrollSection,
	star_section: StarSection,
	text_section: TextSection,
	tile_grid: TileGrid,
};
