// Code generated by Slice Machine. DO NOT EDIT.

import NavLinkTree from './NavLinkTree';
import PageHero from './PageHero';

export {
	NavLinkTree,
	PageHero,
};

export const components = {
	nav_link_tree: NavLinkTree,
	page_hero: PageHero,
};
