// Auto-generated by scripts/migrate-from-prismic.ts
// To regenerate: npx tsx scripts/migrate-from-prismic.ts
// Tour index page content

import type { PageDoc } from "content/types";

export const tourIndexPage: PageDoc = {
  "uid": "tour",
  "data": {
    "title": "The Grand Tour",
    "gallery": [],
    "video_media": null,
    "video_url": "https://cdn.thegrandlb.com/2ff5529b-ae2d-4706-9e14-2e9215729acf-tour-index-15s-final.mp4",
    "media": {
      "dimensions": {
        "width": 3840,
        "height": 2160
      },
      "alt": null,
      "copyright": null,
      "url": "https://images.prismic.io/the-grand/62739841-30e8-45b6-b49e-61692eb5b1ab_Tour+Index+15s--final.jpg?auto=compress,format",
      "id": "ZNR5aBAAACgAlxpE",
      "edit": {
        "x": 0,
        "y": 0,
        "zoom": 1,
        "background": "#fff"
      }
    },
    "icon_media": {
      "dimensions": {
        "width": 217,
        "height": 216
      },
      "alt": "Couple walking hand in hand",
      "copyright": null,
      "url": "https://the-grand.cdn.prismic.io/the-grand/433265db-fc1a-4a81-977d-7821a31ee0c8_lovely+couple.svg",
      "id": "ZD9snBAAACIAn2PT",
      "edit": {
        "x": 0,
        "y": 0,
        "zoom": 1,
        "background": "#fff"
      }
    },
    "headline": "Welcome to 40,000 square feet of grand.",
    "body": "We believe that every occasion is deserving of a personalized touch. Each of our unique spaces is flexible to suit the range of need for any event or gathering.",
    "spaces": [
      {
        "page_media": {
          "dimensions": {
            "width": 1814,
            "height": 2416
          },
          "alt": null,
          "copyright": null,
          "url": "https://images.prismic.io/the-grand/c2092984-f2c9-4c17-a901-a3adb110ccb5_glb-index-ballroom.jpg?auto=compress,format",
          "id": "ZM3b9BIAACkAQ8CB",
          "edit": {
            "x": 0,
            "y": 0,
            "zoom": 1,
            "background": "#fff"
          }
        },
        "page": {
          "uid": "grand-ballroom",
          "data": {
            "headline": "Grand \nBallroom",
            "max_capacity": 675,
            "features": [
              {
                "feature": "Indoor"
              },
              {
                "feature": "Large Stage"
              },
              {
                "feature": "Large Dance Floor"
              }
            ],
            "square_feet": 6000,
            "title": "Grand Ballroom"
          }
        }
      },
      {
        "page_media": {
          "dimensions": {
            "width": 2422,
            "height": 1818
          },
          "alt": null,
          "copyright": null,
          "url": "https://images.prismic.io/the-grand/ff23859d-1c3f-4479-8295-1199f4ee1e65_glb-index-terrace.jpg?auto=compress,format",
          "id": "ZM3b9hIAACcAQ8CL",
          "edit": {
            "x": 0,
            "y": 0,
            "zoom": 1,
            "background": "#fff"
          }
        },
        "page": {
          "uid": "palm-terrace",
          "data": {
            "headline": "The Palm \nTerrace",
            "max_capacity": 400,
            "features": [
              {
                "feature": "Outdoor"
              },
              {
                "feature": "Perfect for Medium to Large Gatherings"
              }
            ],
            "square_feet": 3400,
            "title": "The Palm Terrace"
          }
        }
      },
      {
        "page_media": {
          "dimensions": {
            "width": 2426,
            "height": 1787
          },
          "alt": null,
          "copyright": null,
          "url": "https://images.prismic.io/the-grand/881c9d97-c13b-4b23-9057-7172022fce3b_glb-index-monarch.jpg?auto=compress,format",
          "id": "ZM3b9RIAACcAQ8CG",
          "edit": {
            "x": 0,
            "y": 0,
            "zoom": 1,
            "background": "#fff"
          }
        },
        "page": {
          "uid": "monarch-room",
          "data": {
            "headline": "Monarch \nRoom",
            "max_capacity": 280,
            "features": [
              {
                "feature": "Indoor"
              },
              {
                "feature": "Large Attached Bar"
              },
              {
                "feature": "Large Dance Floor"
              },
              {
                "feature": "Natural Sunlight"
              },
              {
                "feature": "View of Palm Terrace"
              }
            ],
            "square_feet": 3400,
            "title": "Monarch Room"
          }
        }
      },
      {
        "page_media": {
          "dimensions": {
            "width": 2422,
            "height": 1818
          },
          "alt": null,
          "copyright": null,
          "url": "https://images.prismic.io/the-grand/f252a9b2-264c-44bc-ba49-22dfd45f4e3d_glb-index-catalina.jpg?auto=compress,format",
          "id": "ZM3b9BIAACgAQ8B-",
          "edit": {
            "x": 0,
            "y": 0,
            "zoom": 1,
            "background": "#fff"
          }
        },
        "page": {
          "uid": "catalina-room",
          "data": {
            "headline": "Catalina \nRoom",
            "max_capacity": 400,
            "features": [
              {
                "feature": "Indoor"
              },
              {
                "feature": "Large Stage"
              },
              {
                "feature": "Built-in Dance Floor"
              },
              {
                "feature": "Catalina Island Artwork"
              },
              {
                "feature": "Stylish Chandelier"
              },
              {
                "feature": "Perfect for Medium to Large Gatherings"
              }
            ],
            "square_feet": 3340,
            "title": "Catalina Room"
          }
        }
      },
      {
        "page_media": {
          "dimensions": {
            "width": 2426,
            "height": 1820
          },
          "alt": null,
          "copyright": null,
          "url": "https://images.prismic.io/the-grand/995e70a1-b757-4b03-a1ce-dc6b8ff95781_glb-index-garden.jpg?auto=compress,format",
          "id": "ZM3b9BIAACgAQ8CA",
          "edit": {
            "x": 0,
            "y": 0,
            "zoom": 1,
            "background": "#fff"
          }
        },
        "page": {
          "uid": "garden-room",
          "data": {
            "headline": "Garden \nRoom",
            "max_capacity": 140,
            "features": [
              {
                "feature": "Indoor"
              },
              {
                "feature": "Large Attached Bar"
              },
              {
                "feature": "Large Dance Floor"
              },
              {
                "feature": "Natural Sunlight"
              },
              {
                "feature": "View of Palm Terrace"
              }
            ],
            "square_feet": 2757,
            "title": "Garden Room"
          }
        }
      },
      {
        "page_media": {
          "dimensions": {
            "width": 2424,
            "height": 1820
          },
          "alt": null,
          "copyright": null,
          "url": "https://images.prismic.io/the-grand/389847bc-c1c2-4f59-9d0d-b2b4bd734724_glb-index-pacific.jpg?auto=compress,format",
          "id": "ZM3b9xIAACgAQ8CQ",
          "edit": {
            "x": 0,
            "y": 0,
            "zoom": 1,
            "background": "#fff"
          }
        },
        "page": {
          "uid": "pacific-room",
          "data": {
            "headline": "Pacific \nRoom",
            "max_capacity": 90,
            "features": [
              {
                "feature": "Indoor"
              },
              {
                "feature": "Built-in Dance Floor"
              },
              {
                "feature": "Adjacent of Palm Terrace"
              },
              {
                "feature": "Stylish columns"
              },
              {
                "feature": "Perfect for Small Gatherings"
              }
            ],
            "square_feet": 1557,
            "title": "Pacific Room"
          }
        }
      },
      {
        "page_media": {
          "dimensions": {
            "width": 2800,
            "height": 1868
          },
          "alt": null,
          "copyright": null,
          "url": "https://images.prismic.io/the-grand/a18b9bf7-7071-4ff5-be33-fc749535a0c9_glb-index-board.jpg?auto=compress,format",
          "id": "ZM3c2BIAACUAQ8Rq",
          "edit": {
            "x": 0,
            "y": 0,
            "zoom": 1,
            "background": "#fff"
          }
        },
        "page": {
          "uid": "board-room",
          "data": {
            "headline": "Board \nRoom",
            "max_capacity": 40,
            "features": [
              {
                "feature": "Indoor"
              },
              {
                "feature": "Large Mahogany Table"
              },
              {
                "feature": "Access to Monarch Room"
              }
            ],
            "square_feet": 570,
            "title": "Board Room"
          }
        }
      },
      {
        "page_media": {},
        "page": {
          "uid": "map",
          "data": {
            "title": "Interactive Map"
          }
        }
      }
    ],
    "slices": [
      {
        "id": "scroll_text$c7e67538-aa9e-4e5b-8cf2-2c5df3b87a9b",
        "slice_type": "scroll_text",
        "primary": {
          "section_id": "scroll",
          "top_title": null,
          "line_one": "Quince’s & Birthdays & Engagements & Weddings & Banquets",
          "line_two": "Conferences & Church Services & Pageants & Fundraisers",
          "bottom_title": null,
          "primary_action": null,
          "primary_action_link": {
            "link_type": "Any"
          },
          "top_spacer": "Large",
          "bottom_spacer": "None"
        },
        "items": [
          {}
        ]
      },
      {
        "id": "split_scroll_section$03f455cc-fc27-492b-addc-b4e8d23e675b",
        "slice_type": "split_scroll_section",
        "primary": {
          "section_id": "scroll-numbers",
          "gallery": {
            "id": "ZMn0DRAAACEASHh7",
            "type": "fragment_gallery",
            "tags": [],
            "lang": "en-us",
            "slug": "tour-lifestyle",
            "first_publication_date": "2023-08-02T06:14:30+0000",
            "last_publication_date": "2023-08-07T05:51:37+0000",
            "uid": "tour-lifestyle",
            "data": {
              "gallery_items": [
                {
                  "caption": null,
                  "link": {
                    "link_type": "Any"
                  },
                  "video_media": {
                    "link_type": "Media"
                  },
                  "video_url": null,
                  "media": {
                    "dimensions": {
                      "width": 2464,
                      "height": 1848
                    },
                    "alt": null,
                    "copyright": null,
                    "url": "https://images.prismic.io/the-grand/67de966f-f1f7-442e-b27c-92f98bd22985_glb-tour-lifestyle-01.jpg?auto=compress,format",
                    "id": "ZNCGUBIAACUAT5rt",
                    "edit": {
                      "x": 0,
                      "y": 0,
                      "zoom": 1,
                      "background": "#fff"
                    }
                  }
                },
                {
                  "caption": null,
                  "link": {
                    "link_type": "Any"
                  },
                  "video_media": {
                    "link_type": "Media"
                  },
                  "video_url": null,
                  "media": {
                    "dimensions": {
                      "width": 1849,
                      "height": 2464
                    },
                    "alt": null,
                    "copyright": null,
                    "url": "https://images.prismic.io/the-grand/67f892ca-b85e-4b9f-a129-d5baf0ca1e31_glb-tour-lifestyle-02.jpg?auto=compress,format",
                    "id": "ZNCGTBIAACcAT5rZ",
                    "edit": {
                      "x": 0,
                      "y": 0,
                      "zoom": 1,
                      "background": "#fff"
                    }
                  }
                },
                {
                  "caption": null,
                  "link": {
                    "link_type": "Any"
                  },
                  "video_media": {
                    "link_type": "Media"
                  },
                  "video_url": null,
                  "media": {
                    "dimensions": {
                      "width": 2465,
                      "height": 1848
                    },
                    "alt": null,
                    "copyright": null,
                    "url": "https://images.prismic.io/the-grand/33c40290-2eeb-4ec3-820c-92da1547a312_glb-tour-lifestyle-03.jpg?auto=compress,format",
                    "id": "ZNCGTxIAACgAT5ro",
                    "edit": {
                      "x": 0,
                      "y": 0,
                      "zoom": 1,
                      "background": "#fff"
                    }
                  }
                },
                {
                  "caption": null,
                  "link": {
                    "link_type": "Any"
                  },
                  "video_media": {
                    "link_type": "Media"
                  },
                  "video_url": null,
                  "media": {
                    "dimensions": {
                      "width": 2464,
                      "height": 1849
                    },
                    "alt": null,
                    "copyright": null,
                    "url": "https://images.prismic.io/the-grand/65673693-4452-47cc-8ac4-d2f233625807_glb-tour-lifestyle-04.jpg?auto=compress,format",
                    "id": "ZNCGSxIAACgAT5rU",
                    "edit": {
                      "x": 0,
                      "y": 0,
                      "zoom": 1,
                      "background": "#fff"
                    }
                  }
                }
              ]
            },
            "link_type": "Document",
            "key": "3ffef6f7-0456-4c0d-be97-c0b71c812126",
            "isBroken": false
          },
          "video_media": {
            "link_type": "Media"
          },
          "video_url": null,
          "media": {},
          "top_spacer": "Large",
          "bottom_spacer": "None",
          "asset_position": true
        },
        "items": [
          {
            "media": {},
            "headline_size": null,
            "headline": [
              {
                "type": "paragraph",
                "text": "11",
                "spans": []
              }
            ],
            "eyebrow": "Acres",
            "body": [
              {
                "type": "paragraph",
                "text": "Elevate your event to new heights with 11 spacious acres of customizable event space.",
                "spans": []
              }
            ],
            "primary_action_text": "See Facility Map",
            "primary_action_link": {
              "id": "ZD9uPxAAACMAn2so",
              "type": "page",
              "tags": [],
              "lang": "en-us",
              "slug": "interactive-map",
              "first_publication_date": "2023-04-19T04:30:14+0000",
              "last_publication_date": "2023-04-19T04:30:14+0000",
              "uid": "map",
              "data": {
                "title": "Interactive Map"
              },
              "link_type": "Document",
              "key": "333737ce-2f48-4148-b0f2-9ffec2807a99",
              "isBroken": false
            },
            "secondary_action_text": null,
            "secondary_action_link": {
              "link_type": "Any"
            }
          },
          {
            "media": {},
            "headline_size": null,
            "headline": [
              {
                "type": "paragraph",
                "text": "7",
                "spans": []
              }
            ],
            "eyebrow": "Spaces",
            "body": [
              {
                "type": "paragraph",
                "text": "Be it a wedding, a corporate event, or a private celebration, our spaces can be tailored to fit your specific needs.",
                "spans": []
              }
            ],
            "primary_action_text": "See All Spaces",
            "primary_action_link": {
              "id": "ZC5XThAAAB8A0yhs",
              "type": "tour_index_page",
              "tags": [],
              "lang": "en-us",
              "slug": "tour-index-page",
              "first_publication_date": "2023-04-06T05:28:38+0000",
              "last_publication_date": "2026-02-13T08:15:11+0000",
              "uid": "tour",
              "link_type": "Document",
              "key": "b68b1d21-7a93-48a4-853d-404e94812223",
              "isBroken": false
            },
            "secondary_action_text": null,
            "secondary_action_link": {
              "link_type": "Any"
            }
          },
          {
            "media": {},
            "headline_size": null,
            "headline": [
              {
                "type": "heading1",
                "text": "2",
                "spans": []
              }
            ],
            "eyebrow": "Outdoor Terraces",
            "body": [
              {
                "type": "paragraph",
                "text": "Take full advantage of Southern California's sunny skies and fair weather year round.",
                "spans": []
              }
            ],
            "primary_action_text": "Palm Terrace",
            "primary_action_link": {
              "id": "Y-3N9xAAACcA4RZN",
              "type": "tour_page",
              "tags": [],
              "lang": "en-us",
              "slug": "400",
              "first_publication_date": "2023-02-16T06:33:06+0000",
              "last_publication_date": "2026-02-13T08:18:39+0000",
              "uid": "palm-terrace",
              "data": {
                "headline": "The Palm \nTerrace",
                "max_capacity": 400,
                "features": [
                  {
                    "feature": "Outdoor"
                  },
                  {
                    "feature": "Perfect for Medium to Large Gatherings"
                  }
                ],
                "square_feet": 3400,
                "title": "The Palm Terrace"
              },
              "link_type": "Document",
              "key": "264ab059-ce7f-4e9b-97f8-8e8c8d9f3ab0",
              "isBroken": false
            },
            "secondary_action_text": "Monarch Terrace",
            "secondary_action_link": {
              "id": "Y-3NzBAAACgA4RV8",
              "type": "tour_page",
              "tags": [],
              "lang": "en-us",
              "slug": "280",
              "first_publication_date": "2023-02-16T06:33:07+0000",
              "last_publication_date": "2026-02-13T08:18:05+0000",
              "uid": "monarch-room",
              "data": {
                "headline": "Monarch \nRoom",
                "max_capacity": 280,
                "features": [
                  {
                    "feature": "Indoor"
                  },
                  {
                    "feature": "Large Attached Bar"
                  },
                  {
                    "feature": "Large Dance Floor"
                  },
                  {
                    "feature": "Natural Sunlight"
                  },
                  {
                    "feature": "View of Palm Terrace"
                  }
                ],
                "square_feet": 3400,
                "title": "Monarch Room"
              },
              "link_type": "Document",
              "key": "35e60eaf-b298-42a3-81a5-3b582efc090c",
              "isBroken": false
            }
          }
        ]
      },
      {
        "id": "split_scroll_section$821c82ea-8066-413f-9365-62e3ff4bbc99",
        "slice_type": "split_scroll_section",
        "primary": {
          "section_id": "scroll-numbers-2",
          "gallery": {
            "id": "ZMn0ThAAACIASHmn",
            "type": "fragment_gallery",
            "tags": [],
            "lang": "en-us",
            "slug": "tour-interior",
            "first_publication_date": "2023-08-02T06:15:20+0000",
            "last_publication_date": "2023-08-07T05:50:49+0000",
            "uid": "tour-interior",
            "data": {
              "gallery_items": [
                {
                  "caption": null,
                  "link": {
                    "link_type": "Any"
                  },
                  "video_media": {
                    "link_type": "Media"
                  },
                  "video_url": null,
                  "media": {
                    "dimensions": {
                      "width": 2464,
                      "height": 1848
                    },
                    "alt": null,
                    "copyright": null,
                    "url": "https://images.prismic.io/the-grand/f3133888-dec6-4954-89e5-f47c6acc4b59_glb-tour-ext-01.jpg?auto=compress,format",
                    "id": "ZNCGHhIAACkAT5oF",
                    "edit": {
                      "x": 0,
                      "y": 0,
                      "zoom": 1,
                      "background": "#fff"
                    }
                  }
                },
                {
                  "caption": null,
                  "link": {
                    "link_type": "Any"
                  },
                  "video_media": {
                    "link_type": "Media"
                  },
                  "video_url": null,
                  "media": {
                    "dimensions": {
                      "width": 2465,
                      "height": 1848
                    },
                    "alt": null,
                    "copyright": null,
                    "url": "https://images.prismic.io/the-grand/adb5508b-00cc-410d-b4df-018597e58e6e_glb-tour-ext-02.jpg?auto=compress,format",
                    "id": "ZNCGHxIAACUAT5oH",
                    "edit": {
                      "x": 0,
                      "y": 0,
                      "zoom": 1,
                      "background": "#fff"
                    }
                  }
                },
                {
                  "caption": null,
                  "link": {
                    "link_type": "Any"
                  },
                  "video_media": {
                    "link_type": "Media"
                  },
                  "video_url": null,
                  "media": {
                    "dimensions": {
                      "width": 2464,
                      "height": 1849
                    },
                    "alt": null,
                    "copyright": null,
                    "url": "https://images.prismic.io/the-grand/330b00a5-dcf9-4b47-b022-1137fcd29f71_glb-tour-ext-03.jpg?auto=compress,format",
                    "id": "ZNCGHhIAACgAT5oG",
                    "edit": {
                      "x": 0,
                      "y": 0,
                      "zoom": 1,
                      "background": "#fff"
                    }
                  }
                },
                {
                  "caption": null,
                  "link": {
                    "link_type": "Any"
                  },
                  "video_media": {
                    "link_type": "Media"
                  },
                  "video_url": null,
                  "media": {
                    "dimensions": {
                      "width": 2465,
                      "height": 1849
                    },
                    "alt": null,
                    "copyright": null,
                    "url": "https://images.prismic.io/the-grand/b21d93f3-661c-4430-95da-290a1e07b761_glb-tour-ext-04.jpg?auto=compress,format",
                    "id": "ZNCGIBIAACgAT5oS",
                    "edit": {
                      "x": 0,
                      "y": 0,
                      "zoom": 1,
                      "background": "#fff"
                    }
                  }
                }
              ]
            },
            "link_type": "Document",
            "key": "e2174130-7b73-4bd1-a584-7f5311efb929",
            "isBroken": false
          },
          "video_media": {
            "link_type": "Media"
          },
          "video_url": null,
          "media": {},
          "top_spacer": "Large",
          "bottom_spacer": "None",
          "asset_position": false
        },
        "items": [
          {
            "media": {},
            "headline_size": null,
            "headline": [
              {
                "type": "heading1",
                "text": "2K",
                "spans": []
              }
            ],
            "eyebrow": "Total number of guests",
            "body": [
              {
                "type": "paragraph",
                "text": "When you’re here, one of the largest family-owned facilities in the area, you’re in good company.",
                "spans": []
              }
            ],
            "primary_action_text": "See Our Largest Space",
            "primary_action_link": {
              "id": "Y-3NlBAAACgA4RR5",
              "type": "tour_page",
              "tags": [],
              "lang": "en-us",
              "slug": "675",
              "first_publication_date": "2023-02-16T06:31:13+0000",
              "last_publication_date": "2026-02-13T08:13:35+0000",
              "uid": "grand-ballroom",
              "data": {
                "headline": "Grand \nBallroom",
                "max_capacity": 675,
                "features": [
                  {
                    "feature": "Indoor"
                  },
                  {
                    "feature": "Large Stage"
                  },
                  {
                    "feature": "Large Dance Floor"
                  }
                ],
                "square_feet": 6000,
                "title": "Grand Ballroom"
              },
              "link_type": "Document",
              "key": "4e385305-f318-4a0a-909f-3980032b4174",
              "isBroken": false
            },
            "secondary_action_text": null,
            "secondary_action_link": {
              "link_type": "Any"
            }
          },
          {
            "media": {},
            "headline_size": null,
            "headline": [
              {
                "type": "heading1",
                "text": "400",
                "spans": []
              }
            ],
            "eyebrow": "Complimentary Parking Spots",
            "body": [
              {
                "type": "paragraph",
                "text": "Your guests will arrive with ease and convenience, making the event experience even more enjoyable.",
                "spans": []
              }
            ],
            "primary_action_text": null,
            "primary_action_link": {
              "link_type": "Any"
            },
            "secondary_action_text": null,
            "secondary_action_link": {
              "link_type": "Any"
            }
          },
          {
            "media": {},
            "headline_size": null,
            "headline": [
              {
                "type": "heading1",
                "text": "1",
                "spans": []
              }
            ],
            "eyebrow": "World Class Kitchen",
            "body": [
              {
                "type": "paragraph",
                "text": "Indulge in the freshest cuisine with our one-of-a-kind, in-house world-class kitchen.",
                "spans": []
              }
            ],
            "primary_action_text": "View Our Menu",
            "primary_action_link": {
              "id": "ZC5eyBAAAB8A0zOo",
              "type": "page",
              "tags": [],
              "lang": "en-us",
              "slug": "menus-at-the-grand",
              "first_publication_date": "2023-04-06T05:55:45+0000",
              "last_publication_date": "2026-02-13T08:13:17+0000",
              "uid": "menus",
              "data": {
                "title": "Menus at The Grand"
              },
              "link_type": "Document",
              "key": "8af2eef5-dc11-4900-88ac-ad32bad94329",
              "isBroken": false
            },
            "secondary_action_text": null,
            "secondary_action_link": {
              "link_type": "Any"
            }
          }
        ]
      }
    ],
    "meta_title": null,
    "meta_description": null,
    "meta_image": {}
  }
};
