// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  faq_section: dynamic(() => import("./FaqSection")),
  hero_detail_page_slice: dynamic(() => import("./HeroDetailPageSlice")),
  homepage_location: dynamic(() => import("./HomepageLocation")),
  homepage_numbers: dynamic(() => import("./HomepageNumbers")),
  image_section: dynamic(() => import("./ImageSection")),
  longform_text_section: dynamic(() => import("./LongformTextSection")),
  moments_scroll_section: dynamic(() => import("./MomentsScrollSection")),
  numbers_section: dynamic(() => import("./NumbersSection")),
  page_hero: dynamic(() => import("./MainHero")),
  scroll_text: dynamic(() => import("./ScrollText")),
  split_gallery: dynamic(() => import("./SplitGallery")),
  split_scroll_section: dynamic(() => import("./SplitScrollSection")),
  star_section: dynamic(() => import("./StarSection")),
  team_gallery: dynamic(() => import("./TeamGallery")),
  text_section: dynamic(() => import("./TextSection")),
  tile_grid: dynamic(() => import("./TileGrid")),
};
