// Auto-generated by scripts/migrate-from-prismic.ts
// To regenerate: npx tsx scripts/migrate-from-prismic.ts
// Menus index page content

import type { PageDoc } from "content/types";

export const menuIndexPage: PageDoc = {
  "uid": "menus",
  "data": {
    "title": "Menus at The Grand",
    "gallery": [],
    "video_media": null,
    "video_url": "https://cdn.thegrandlb.com/ea3bc056-e211-4f3b-8ccd-cb66fcc14a3c-menu-index-final.mp4",
    "media": {
      "dimensions": {
        "width": 3840,
        "height": 2160
      },
      "alt": null,
      "copyright": null,
      "url": "https://imagedelivery.net/jq-BfOr8JDGgGxqbx8v5CA/8c590e41-1860-402a-44a1-767881408e00/public",
      "id": "ZNcQARAAACgAokNI",
      "edit": {
        "x": 0,
        "y": 0,
        "zoom": 1,
        "background": "#fff"
      }
    },
    "slices": [
      {
        "id": "text_section$f538f95f-e777-4e95-a395-bf7ade848a54",
        "slice_type": "text_section",
        "primary": {
          "section_id": "intro",
          "eyebrow": null,
          "body": [
            {
              "type": "paragraph",
              "text": "We know that food brings people together. That's why we've created menus with a variety of offerings to elevate your event experience. Our culinary team takes great care to prepare each dish to perfection and tailor it to meet the diverse tastes and dietary needs of your guests. ",
              "spans": []
            }
          ],
          "primary_action": null,
          "primary_action_link": {
            "link_type": "Any"
          },
          "secondary_action": null,
          "secondary_action_link": {
            "link_type": "Any"
          },
          "top_spacer": "None",
          "top_border": false,
          "bottom_spacer": "None",
          "bottom_border": true
        },
        "items": [
          {}
        ]
      },
      {
        "id": "tile_grid$e7c79303-70aa-4836-b00a-3402d4e0b0b7",
        "slice_type": "tile_grid",
        "primary": {
          "section_id": "grid",
          "headline": null,
          "body": null,
          "theme": "Cream",
          "top_spacer": "Medium",
          "bottom_spacer": null
        },
        "items": [
          {
            "card_fragment": {
              "link_type": "Document"
            },
            "media": {},
            "eyebrow": null,
            "headline": "Classic Menu",
            "body": "Experience timeless elegance with our classic menu packages, featuring elevated versions of your favorite dishes.",
            "link": {
              "id": "ZC-oOxAAAB8A1WRA",
              "type": "menu_page",
              "tags": [],
              "lang": "en-us",
              "slug": "classic-menu",
              "first_publication_date": "2023-04-07T05:24:37+0000",
              "last_publication_date": "2023-04-07T05:24:37+0000",
              "uid": "classic",
              "link_type": "Document",
              "key": "8612a8aa-b957-4f30-9b28-987f653ce39e",
              "isBroken": false
            },
            "theme": "White/Black",
            "size": "Default",
            "direction": "Col",
            "col_start": "Start 2",
            "col_span": "Span 5",
            "row_start": "Start 1",
            "row_span": "Span 2"
          },
          {
            "card_fragment": {
              "link_type": "Document"
            },
            "media": {},
            "eyebrow": null,
            "headline": "Wedding Packages Menu",
            "body": "Make your special day even more memorable with our exquisite wedding menu packages, customizable to your tastes and preferences.",
            "link": {
              "id": "ZC-oKBAAACEA1WQc",
              "type": "menu_page",
              "tags": [],
              "lang": "en-us",
              "slug": "weddings-menu",
              "first_publication_date": "2023-04-07T05:24:37+0000",
              "last_publication_date": "2023-04-07T05:24:37+0000",
              "uid": "weddings",
              "link_type": "Document",
              "key": "036af0c2-69cd-4b71-aa57-3186710ac04b",
              "isBroken": false
            },
            "theme": "White/Black",
            "size": "Default",
            "direction": "Col",
            "col_start": "Start 7",
            "col_span": "Span 5",
            "row_start": "Start 1",
            "row_span": "Span 2"
          },
          {
            "card_fragment": {
              "link_type": "Document"
            },
            "media": {},
            "eyebrow": null,
            "headline": "Business Packages Menu",
            "body": "Impress your colleagues and clients with our sophisticated corporate menu packages, designed to elevate any business event.",
            "link": {
              "id": "ZC-ovhAAACEA1WUK",
              "type": "menu_page",
              "tags": [],
              "lang": "en-us",
              "slug": "business-menu",
              "first_publication_date": "2023-04-07T05:24:36+0000",
              "last_publication_date": "2023-05-18T06:26:34+0000",
              "uid": "corporate",
              "link_type": "Document",
              "key": "ca72aca1-1cf0-458e-8ec4-48f36b174696",
              "isBroken": false
            },
            "theme": "White/Black",
            "size": "Default",
            "direction": "Col",
            "col_start": "Start 2",
            "col_span": "Span 5",
            "row_start": "Start 3",
            "row_span": "Span 2"
          },
          {
            "card_fragment": {
              "link_type": "Document"
            },
            "media": {},
            "eyebrow": null,
            "headline": "Milestone Packages Menu",
            "body": "Celebrate life's big moments with a variety of delicious and customizable options for any occasion.",
            "link": {
              "id": "ZC-o2RAAAB8A1WU0",
              "type": "menu_page",
              "tags": [],
              "lang": "en-us",
              "slug": "milestones-menu",
              "first_publication_date": "2023-04-07T05:24:36+0000",
              "last_publication_date": "2023-04-07T05:24:36+0000",
              "uid": "milestones",
              "link_type": "Document",
              "key": "bbdf758a-5617-495d-b4a6-74f48c0c7e5f",
              "isBroken": false
            },
            "theme": "White/Black",
            "size": "Default",
            "direction": "Col",
            "col_start": "Start 7",
            "col_span": "Span 5",
            "row_start": "Start 3",
            "row_span": "Span 2"
          }
        ]
      },
      {
        "id": "numbers_section$991a0d57-461f-4985-b4fa-33c93198fd5b",
        "slice_type": "numbers_section",
        "primary": {
          "section_id": "offsite-menus",
          "title": "Offsite Catering Menus",
          "description": null,
          "columns": "3 Column",
          "inset": true,
          "top_spacer": null,
          "top_border": false,
          "bottom_spacer": "Medium",
          "bottom_border": false
        },
        "items": [
          {
            "media": {},
            "number": [],
            "eyebrow": "Classic \nCatering Menu",
            "body": [
              {
                "type": "paragraph",
                "text": "Download PDF ↘ ",
                "spans": [
                  {
                    "start": 0,
                    "end": 12,
                    "type": "hyperlink",
                    "data": {
                      "link_type": "Web",
                      "url": "https://the-grand.cdn.prismic.io/the-grand/2a30777c-f307-483b-ae6a-226e2340dad6_2023+Classic+Menu.pdf",
                      "target": "_blank"
                    }
                  }
                ]
              }
            ],
            "action_text": null,
            "action_link": {
              "link_type": "Any"
            }
          },
          {
            "media": {},
            "number": [],
            "eyebrow": "Milestones \nCatering Menu",
            "body": [
              {
                "type": "paragraph",
                "text": "Download PDF ↘",
                "spans": [
                  {
                    "start": 0,
                    "end": 12,
                    "type": "hyperlink",
                    "data": {
                      "link_type": "Web",
                      "url": "https://the-grand.cdn.prismic.io/the-grand/e83e9d22-3b52-4279-ac60-b45732faecdb_2023+Milestone+Menu.pdf",
                      "target": "_blank"
                    }
                  }
                ]
              }
            ],
            "action_text": null,
            "action_link": {
              "link_type": "Any"
            }
          },
          {
            "media": {},
            "number": [],
            "eyebrow": "Wedding \nCatering Menu",
            "body": [
              {
                "type": "paragraph",
                "text": "Download PDF ↘",
                "spans": [
                  {
                    "start": 0,
                    "end": 12,
                    "type": "hyperlink",
                    "data": {
                      "link_type": "Web",
                      "url": "https://the-grand.cdn.prismic.io/the-grand/544aaf05-3862-47a4-9c26-92627959005b_2023+Wedding+Menu.pdf",
                      "target": "_blank"
                    }
                  }
                ]
              }
            ],
            "action_text": null,
            "action_link": {
              "link_type": "Any"
            }
          }
        ]
      },
      {
        "id": "faq_section$f45bf944-2a3b-45a0-82ef-0e27532f9da2",
        "slice_type": "faq_section",
        "primary": {
          "section_id": "faq",
          "title": "All the answers",
          "gallery": {
            "id": "ZNcQNhAAACYAokQ3",
            "type": "fragment_gallery",
            "tags": [],
            "lang": "en-us",
            "slug": "menu-scroll",
            "first_publication_date": "2023-08-12T04:54:40+0000",
            "last_publication_date": "2023-08-12T04:54:40+0000",
            "uid": "menu-scroll",
            "data": {
              "gallery_items": [
                {
                  "caption": null,
                  "link": {
                    "link_type": "Any"
                  },
                  "video_media": {
                    "link_type": "Media"
                  },
                  "video_url": null,
                  "media": {
                    "dimensions": {
                      "width": 1850,
                      "height": 2466
                    },
                    "alt": null,
                    "copyright": null,
                    "url": "https://imagedelivery.net/jq-BfOr8JDGgGxqbx8v5CA/72908b93-f2c2-44c4-ccb0-b3294d921400/public",
                    "id": "ZNcQXRAAACYAokTw",
                    "edit": {
                      "x": 0,
                      "y": 0,
                      "zoom": 1,
                      "background": "#fff"
                    }
                  }
                },
                {
                  "caption": null,
                  "link": {
                    "link_type": "Any"
                  },
                  "video_media": {
                    "link_type": "Media"
                  },
                  "video_url": null,
                  "media": {
                    "dimensions": {
                      "width": 1850,
                      "height": 2466
                    },
                    "alt": null,
                    "copyright": null,
                    "url": "https://imagedelivery.net/jq-BfOr8JDGgGxqbx8v5CA/34a92d62-a25b-4a27-422f-2e8777714600/public",
                    "id": "ZNcQXBAAACgAokTj",
                    "edit": {
                      "x": 0,
                      "y": 0,
                      "zoom": 1,
                      "background": "#fff"
                    }
                  }
                },
                {
                  "caption": null,
                  "link": {
                    "link_type": "Any"
                  },
                  "video_media": {
                    "link_type": "Media"
                  },
                  "video_url": null,
                  "media": {
                    "dimensions": {
                      "width": 2466,
                      "height": 1850
                    },
                    "alt": null,
                    "copyright": null,
                    "url": "https://imagedelivery.net/jq-BfOr8JDGgGxqbx8v5CA/f8325240-f0c7-4319-7703-026e3d803000/public",
                    "id": "ZNcQXhAAACkAokTx",
                    "edit": {
                      "x": 0,
                      "y": 0,
                      "zoom": 1,
                      "background": "#fff"
                    }
                  }
                },
                {
                  "caption": null,
                  "link": {
                    "link_type": "Any"
                  },
                  "video_media": {
                    "link_type": "Media"
                  },
                  "video_url": null,
                  "media": {
                    "dimensions": {
                      "width": 2467,
                      "height": 1850
                    },
                    "alt": null,
                    "copyright": null,
                    "url": "https://imagedelivery.net/jq-BfOr8JDGgGxqbx8v5CA/45e64cf1-7202-4c5e-634b-1965815d2400/public",
                    "id": "ZNcQXxAAACgAokT4",
                    "edit": {
                      "x": 0,
                      "y": 0,
                      "zoom": 1,
                      "background": "#fff"
                    }
                  }
                },
                {
                  "caption": null,
                  "link": {
                    "link_type": "Any"
                  },
                  "video_media": {
                    "link_type": "Media"
                  },
                  "video_url": null,
                  "media": {
                    "dimensions": {
                      "width": 1850,
                      "height": 2466
                    },
                    "alt": null,
                    "copyright": null,
                    "url": "https://imagedelivery.net/jq-BfOr8JDGgGxqbx8v5CA/c86282c4-c74f-46ed-b93e-f618390c0e00/public",
                    "id": "ZNcQWxAAACkAokTi",
                    "edit": {
                      "x": 0,
                      "y": 0,
                      "zoom": 1,
                      "background": "#fff"
                    }
                  }
                },
                {
                  "caption": null,
                  "link": {
                    "link_type": "Any"
                  },
                  "video_media": {
                    "link_type": "Media"
                  },
                  "video_url": null,
                  "media": {
                    "dimensions": {
                      "width": 2467,
                      "height": 1850
                    },
                    "alt": null,
                    "copyright": null,
                    "url": "https://imagedelivery.net/jq-BfOr8JDGgGxqbx8v5CA/98e95b5f-8018-45cb-e8e2-c26b9c68bd00/public",
                    "id": "ZNcQXRAAACcAokTq",
                    "edit": {
                      "x": 0,
                      "y": 0,
                      "zoom": 1,
                      "background": "#fff"
                    }
                  }
                }
              ]
            },
            "link_type": "Document",
            "key": "51da51d9-c821-4947-b33f-2ef2b9322d74",
            "isBroken": false
          },
          "video_media": {
            "link_type": "Media"
          },
          "video_url": null,
          "media": {},
          "asset_position": true
        },
        "items": [
          {
            "question": [
              {
                "type": "paragraph",
                "text": "What type of cuisine does The Grand offer on its menus?",
                "spans": []
              }
            ],
            "answer": [
              {
                "type": "paragraph",
                "text": "The Grand offers a variety of cuisine styles to cater to different tastes and preferences. Our menus range from classic American fare to international dishes and can be customized to meet your specific needs.",
                "spans": []
              }
            ]
          },
          {
            "question": [
              {
                "type": "paragraph",
                "text": "Can The Grand accommodate dietary restrictions and allergies? ",
                "spans": []
              }
            ],
            "answer": [
              {
                "type": "paragraph",
                "text": "Yes, The Grand can accommodate dietary restrictions and allergies. We work closely with our clients to ensure that all guests are able to enjoy the event and have a memorable experience. Please inform us of any dietary restrictions or allergies in advance so that we can plan accordingly.",
                "spans": []
              }
            ]
          },
          {
            "question": [
              {
                "type": "paragraph",
                "text": "How are the menus priced at The Grand? ",
                "spans": []
              }
            ],
            "answer": [
              {
                "type": "paragraph",
                "text": "The menus at The Grand are priced per person and vary depending on the selected menu items and service style. We offer a range of options to fit different budgets and can work with you to create a menu that meets your needs.",
                "spans": []
              }
            ]
          },
          {
            "question": [
              {
                "type": "paragraph",
                "text": "Can The Grand provide bar services for events? ",
                "spans": []
              }
            ],
            "answer": [
              {
                "type": "paragraph",
                "text": "Yes, The Grand can provide bar services for events. We offer a variety of beverage packages and can create custom cocktails to complement your menu.",
                "spans": []
              }
            ]
          },
          {
            "question": [
              {
                "type": "paragraph",
                "text": "Can we do a tasting before finalizing our menu? ",
                "spans": []
              }
            ],
            "answer": [
              {
                "type": "paragraph",
                "text": "Yes, The Grand offers tastings for events. We can schedule a tasting to help you select the perfect menu items for your event. Please contact our events team to schedule a tasting.",
                "spans": []
              }
            ]
          },
          {
            "question": [
              {
                "type": "paragraph",
                "text": "How far in advance do we need to finalize our menu? ",
                "spans": []
              }
            ],
            "answer": [
              {
                "type": "paragraph",
                "text": "We recommend finalizing your menu at least four weeks prior to your event to ensure that we have enough time to source ingredients and prepare the dishes to our high standards. However, we can often accommodate last-minute menu changes if necessary. Please contact our events team to discuss your needs.",
                "spans": []
              }
            ]
          }
        ]
      }
    ],
    "meta_title": null,
    "meta_description": null,
    "meta_image": {}
  }
};
