const fetchLinks = [
  "fragment_number_list.numberlist",
  "fragment_number_list.bullet_list",
  "fragment_number_list.primary_action",
  "fragment_number_list.primary_action_link",
  "fragment_gallery.gallery_items",
  "fragment_media.video_media",
  "fragment_media.media",
  "fragment_media.caption",
  "fragment_textblock.media",
  "fragment_textblock.eyebrow",
  "fragment_textblock.number",
  "fragment_textblock.body",
  "fragment_textblock.action_text",
  "fragment_textblock.action_link",
  "fragment_card.media",
  "fragment_card.eyebrow",
  "fragment_card.headline",
  "fragment_card.body",
  "fragment_card.link",
  "fragment_card.theme",
  "fragment_card.size",
  "fragment_card.direction",
  "fragment_card.col_start",
  "fragment_card.col_span",
  "fragment_card.row_start",
  "fragment_card.row_span",
  "fragment_cta_footer.headline",
  "fragment_cta_footer.media",
  "fragment_cta_footer.inquire_card",
  "fragment_cta_footer.top_spacer",
  "fragment_cta_footer.bottom_spacer",
];

export default fetchLinks;
