// Auto-generated by scripts/migrate-from-prismic.ts
// To regenerate: npx tsx scripts/migrate-from-prismic.ts
// Offsite detail pages — uid-keyed map (replaces Prismic offsite_page per uid)

import type { Content } from "@prismicio/client";

export const offsitePages: Record<string, Content.OffsitePageDocument> = {} as unknown as Record<string, Content.OffsitePageDocument>;

/** Sorted UIDs for generateStaticParams */
export const offsitePageUids = [];
