// Auto-generated by scripts/migrate-from-prismic.ts
// To regenerate: npx tsx scripts/migrate-from-prismic.ts
// Offsite detail pages — uid-keyed map

import type { PageDoc } from "content/types";

export const offsitePages: Record<string, PageDoc> = {};

/** UIDs for generateStaticParams */
export const offsitePageUids = [];
