/**
 * Prismic → Static Content Migration Script
 *
 * Fetches all content from the Prismic CMS and writes TypeScript
 * content files colocated with each route. After running this script,
 * the page components can be updated to import from the generated
 * content files instead of querying Prismic at request time.
 *
 * Run: npx tsx scripts/migrate-from-prismic.ts
 *
 * NOTE: Menus (grandmenus) are intentionally excluded — they stay on Prismic.
 */

import * as prismic from "@prismicio/client";
import * as fs from "fs";
import * as path from "path";

// ─── Config ────────────────────────────────────────────────────────────────

const REPO = "the-grand";

const FETCH_LINKS = [
  "fragment_number_list.numberlist",
  "fragment_number_list.bullet_list",
  "fragment_number_list.primary_action",
  "fragment_number_list.primary_action_link",
  "fragment_gallery.gallery_items",
  "fragment_media.media",
  "fragment_media.caption",
  "fragment_textblock.media",
  "fragment_textblock.eyebrow",
  "fragment_textblock.number",
  "fragment_textblock.body",
  "fragment_textblock.action_text",
  "fragment_textblock.action_link",
  "fragment_card.media",
  "fragment_card.eyebrow",
  "fragment_card.headline",
  "fragment_card.body",
  "fragment_card.link",
  "fragment_card.theme",
  "fragment_card.size",
  "fragment_card.direction",
  "fragment_card.col_start",
  "fragment_card.col_span",
  "fragment_card.row_start",
  "fragment_card.row_span",
  "fragment_cta_footer.headline",
  "fragment_cta_footer.media",
  "fragment_cta_footer.inquire_card",
  "fragment_cta_footer.top_spacer",
  "fragment_cta_footer.bottom_spacer",
  "tour_page.title",
  "tour_page.headline",
  "tour_page.max_capacity",
  "tour_page.square_feet",
  "tour_page.features",
  "event_page.title",
  "event_page.headline",
  "event_page.caption",
  "page.title",
];

const ROOT = path.resolve(process.cwd());
const SRC_SITE = path.join(ROOT, "src/app/(site)");
const CONTENT_DIR = path.join(ROOT, "content");

// ─── Helpers ───────────────────────────────────────────────────────────────

function ensureDir(dir: string) {
  fs.mkdirSync(dir, { recursive: true });
}

function writeTs(filePath: string, content: string) {
  ensureDir(path.dirname(filePath));
  fs.writeFileSync(filePath, content, "utf-8");
  console.log(`  ✓  ${path.relative(ROOT, filePath)}`);
}

function serialize(data: unknown): string {
  // U+2028 (LINE SEPARATOR) and U+2029 (PARAGRAPH SEPARATOR) are valid in JSON
  // but TypeScript treats them as line terminators inside string literals.
  return JSON.stringify(data, null, 2)
    .replace(/\u2028/g, "\\u2028")
    .replace(/\u2029/g, "\\u2029");
}

function header(note?: string) {
  return [
    "// Auto-generated by scripts/migrate-from-prismic.ts",
    "// To regenerate: npx tsx scripts/migrate-from-prismic.ts",
    note ? `// ${note}` : "",
    "",
  ]
    .filter((l, i) => l !== "" || i === 3)
    .join("\n");
}

// ─── Main ──────────────────────────────────────────────────────────────────

async function main() {
  console.log("\n🚀  Starting Prismic migration...\n");

  const client = prismic.createClient(REPO);

  // ── Fetch everything in parallel ──────────────────────────────────────────

  console.log("  Fetching from Prismic...");

  const [
    navigationResult,
    settings,
    ctaResult,
    tourCard,
    eventsCard,
    menusCard,
    homePage,
    aboutPage,
    contactPage,
    menuIndexPage,
    tourIndexPage,
    eventIndexPage,
    offsiteIndexPage,
    tourPages,
    eventPages,
    offsitePages,
    generalPages,
  ] = await Promise.all([
    client.getByType("nav_links"),
    client.getByUID("settings", "settings"),
    client.getByType("fragment_cta_footer", { fetchLinks: FETCH_LINKS }),
    client.getByUID("fragment_card", "tour-card", { fetchLinks: FETCH_LINKS }),
    client.getByUID("fragment_card", "events-card", { fetchLinks: FETCH_LINKS }),
    client.getByUID("fragment_card", "menus-card", { fetchLinks: FETCH_LINKS }),
    client.getByUID("page", "home", { fetchLinks: FETCH_LINKS }),
    client.getByUID("page", "about", { fetchLinks: FETCH_LINKS }),
    client.getByUID("page", "contact", { fetchLinks: FETCH_LINKS }),
    client.getByUID("page", "menus", { fetchLinks: FETCH_LINKS }),
    client.getByUID("tour_index_page", "tour", { fetchLinks: FETCH_LINKS }),
    client.getByUID("event_index_page", "events", { fetchLinks: FETCH_LINKS }),
    client.getByUID("offsite_index_page", "offsite", { fetchLinks: FETCH_LINKS }),
    client.getAllByType("tour_page", { fetchLinks: FETCH_LINKS }),
    client.getAllByType("event_page", { fetchLinks: FETCH_LINKS }),
    client.getAllByType("offsite_page", { fetchLinks: FETCH_LINKS }),
    client.getAllByType("page", { fetchLinks: FETCH_LINKS }),
  ]);

  const navigation = navigationResult.results[0] ?? null;
  const cta = ctaResult.results[0] ?? null;

  console.log("\n  Writing content files...\n");

  // ── 1. content/shared.constants.ts ──────────────────────────────────────

  ensureDir(CONTENT_DIR);

  writeTs(
    path.join(CONTENT_DIR, "shared.constants.ts"),
    `${header("Global data shared across all routes (replaces getExtra)")}
import type { Content } from "@prismicio/client";

/** Global site settings (favicon, SEO defaults, etc.) */
export const settings = ${serialize(settings)} as unknown as Content.SettingsDocument;

/** Primary navigation links */
export const navigation = ${serialize(navigation)} as unknown as Content.NavLinksDocument | null;

/** CTA footer fragment (bottom-of-page call-to-action) */
export const ctaFooter = ${serialize(cta)} as unknown as Content.FragmentCtaFooterDocument | null;

/** Footer tile cards — tour, events, menus */
export const footerCards = ${serialize([tourCard, eventsCard, menusCard])} as unknown as Content.FragmentCardDocument[];
`
  );

  // ── 2. Home page ──────────────────────────────────────────────────────────

  writeTs(
    path.join(SRC_SITE, "content.ts"),
    `${header("Home page content (replaces Prismic page uid='home')")}
import type { Content } from "@prismicio/client";

export const homePage = ${serialize(homePage)} as unknown as Content.PageDocument;
`
  );

  // ── 3. About page ─────────────────────────────────────────────────────────

  writeTs(
    path.join(SRC_SITE, "about/content.ts"),
    `${header("About page content (replaces Prismic page uid='about')")}
import type { Content } from "@prismicio/client";

export const aboutPage = ${serialize(aboutPage)} as unknown as Content.PageDocument;
`
  );

  // ── 4. Contact page ───────────────────────────────────────────────────────

  writeTs(
    path.join(SRC_SITE, "contact/content.ts"),
    `${header("Contact page content (replaces Prismic page uid='contact')")}
import type { Content } from "@prismicio/client";

export const contactPage = ${serialize(contactPage)} as unknown as Content.PageDocument;
`
  );

  // ── 5. Menus index page ───────────────────────────────────────────────────

  writeTs(
    path.join(SRC_SITE, "menus/content.ts"),
    `${header("Menus index page content (replaces Prismic page uid='menus')")}
import type { Content } from "@prismicio/client";

export const menuIndexPage = ${serialize(menuIndexPage)} as unknown as Content.PageDocument;
`
  );

  // ── 6. Tour index page ────────────────────────────────────────────────────

  writeTs(
    path.join(SRC_SITE, "tour/content.ts"),
    `${header("Tour index page content (replaces Prismic tour_index_page uid='tour')")}
import type { Content } from "@prismicio/client";

export const tourIndexPage = ${serialize(tourIndexPage)} as unknown as Content.TourIndexPageDocument;
`
  );

  // ── 7. Events index page ──────────────────────────────────────────────────

  writeTs(
    path.join(SRC_SITE, "events/content.ts"),
    `${header("Events index page content (replaces Prismic event_index_page uid='events')")}
import type { Content } from "@prismicio/client";

export const eventIndexPage = ${serialize(eventIndexPage)} as unknown as Content.EventIndexPageDocument;
`
  );

  // ── 8. Offsite index page ─────────────────────────────────────────────────

  writeTs(
    path.join(SRC_SITE, "offsite/content.ts"),
    `${header("Offsite index page content (replaces Prismic offsite_index_page uid='offsite')")}
import type { Content } from "@prismicio/client";

export const offsiteIndexPage = ${serialize(offsiteIndexPage)} as unknown as Content.OffsiteIndexPageDocument;
`
  );

  // ── 9. Tour detail pages (uid-keyed map) ──────────────────────────────────

  const tourPageMap: Record<string, unknown> = {};
  for (const p of tourPages) {
    tourPageMap[p.uid] = p;
  }

  writeTs(
    path.join(SRC_SITE, "tour/[uid]/content.ts"),
    `${header("Tour detail pages — uid-keyed map (replaces Prismic tour_page per uid)")}
import type { Content } from "@prismicio/client";

export const tourPages: Record<string, Content.TourPageDocument> = ${serialize(tourPageMap)} as unknown as Record<string, Content.TourPageDocument>;

/** Sorted UIDs for generateStaticParams */
export const tourPageUids = ${serialize(tourPages.map((p) => p.uid))};
`
  );

  // ── 10. Event detail pages (uid-keyed map) ────────────────────────────────

  const eventPageMap: Record<string, unknown> = {};
  for (const p of eventPages) {
    eventPageMap[p.uid] = p;
  }

  writeTs(
    path.join(SRC_SITE, "events/[uid]/content.ts"),
    `${header("Event detail pages — uid-keyed map (replaces Prismic event_page per uid)")}
import type { Content } from "@prismicio/client";

export const eventPages: Record<string, Content.EventPageDocument> = ${serialize(eventPageMap)} as unknown as Record<string, Content.EventPageDocument>;

/** Sorted UIDs for generateStaticParams */
export const eventPageUids = ${serialize(eventPages.map((p) => p.uid))};
`
  );

  // ── 11. Offsite detail pages (uid-keyed map) ──────────────────────────────

  const offsitePageMap: Record<string, unknown> = {};
  for (const p of offsitePages) {
    offsitePageMap[p.uid] = p;
  }

  writeTs(
    path.join(SRC_SITE, "offsite/[uid]/content.ts"),
    `${header("Offsite detail pages — uid-keyed map (replaces Prismic offsite_page per uid)")}
import type { Content } from "@prismicio/client";

export const offsitePages: Record<string, Content.OffsitePageDocument> = ${serialize(offsitePageMap)} as unknown as Record<string, Content.OffsitePageDocument>;

/** Sorted UIDs for generateStaticParams */
export const offsitePageUids = ${serialize(offsitePages.map((p) => p.uid))};
`
  );

  // ── 12. General pages (uid-keyed map for /:uid catch-all) ─────────────────

  // Exclude special pages already handled above
  const EXCLUDED = new Set(["home", "about", "contact", "menus"]);
  const generalPageMap: Record<string, unknown> = {};
  for (const p of generalPages) {
    if (!EXCLUDED.has(p.uid)) {
      generalPageMap[p.uid] = p;
    }
  }

  ensureDir(path.join(SRC_SITE, "[uid]"));
  writeTs(
    path.join(SRC_SITE, "[uid]/content.ts"),
    `${header("General pages — uid-keyed map (replaces Prismic page type with general_page tag)")}
import type { Content } from "@prismicio/client";

export const generalPages: Record<string, Content.PageDocument> = ${serialize(generalPageMap)} as unknown as Record<string, Content.PageDocument>;

/** Sorted UIDs for generateStaticParams */
export const generalPageUids = ${serialize(Object.keys(generalPageMap))};
`
  );

  // ── Summary ───────────────────────────────────────────────────────────────

  console.log("\n✅  Migration complete!\n");
  console.log("  Content files written:");
  console.log(`    • content/shared.constants.ts (navigation, settings, cta, footerCards)`);
  console.log(`    • src/app/(site)/content.ts (home)`);
  console.log(`    • src/app/(site)/about/content.ts`);
  console.log(`    • src/app/(site)/contact/content.ts`);
  console.log(`    • src/app/(site)/menus/content.ts`);
  console.log(`    • src/app/(site)/tour/content.ts`);
  console.log(`    • src/app/(site)/events/content.ts`);
  console.log(`    • src/app/(site)/offsite/content.ts`);
  console.log(`    • src/app/(site)/tour/[uid]/content.ts  (${tourPages.length} spaces)`);
  console.log(`    • src/app/(site)/events/[uid]/content.ts  (${eventPages.length} events)`);
  console.log(`    • src/app/(site)/offsite/[uid]/content.ts  (${offsitePages.length} offsites)`);
  console.log(`    • src/app/(site)/[uid]/content.ts  (${Object.keys(generalPageMap).length} general pages)`);
  console.log("\n  Next: update page components to import from these files.");
  console.log("  See docs/migration-tracker.md for the full checklist.\n");
}

main().catch((err) => {
  console.error("\n❌  Migration failed:", err);
  process.exit(1);
});
