// Auto-generated by scripts/migrate-from-prismic.ts
// To regenerate: npx tsx scripts/migrate-from-prismic.ts
// Events index page content (replaces Prismic event_index_page uid='events')

import type { Content } from "@prismicio/client";

export const eventIndexPage = {
  "id": "ZC5XgxAAACEA0yi9",
  "uid": "events",
  "url": null,
  "type": "event_index_page",
  "href": "https://the-grand.cdn.prismic.io/api/v2/documents/search?ref=aY7e8hEAACQAAXJd&q=%5B%5B%3Ad+%3D+at%28document.id%2C+%22ZC5XgxAAACEA0yi9%22%29+%5D%5D",
  "tags": [],
  "first_publication_date": "2023-04-06T05:28:38+0000",
  "last_publication_date": "2026-02-13T08:21:06+0000",
  "slugs": [
    "event-index-page"
  ],
  "linked_documents": [],
  "lang": "en-us",
  "alternate_languages": [],
  "data": {
    "title": "Your Grand Moment",
    "gallery": {
      "link_type": "Document"
    },
    "video_media": {
      "link_type": "Media"
    },
    "video_url": "https://cdn.thegrandlb.com/9e5d872e-81ca-46e2-93e4-7d952055014c-events-index-15s-final.mp4",
    "media": {
      "dimensions": {
        "width": 3840,
        "height": 2160
      },
      "alt": null,
      "copyright": null,
      "url": "https://images.prismic.io/the-grand/1ed340c1-6cd2-4eff-b69c-b888e7622284_Events+Index+15s--final.jpg?auto=format,compress",
      "id": "ZNR7JxAAACYAlyJK",
      "edit": {
        "x": 0,
        "y": 0,
        "zoom": 1,
        "background": "#fff"
      }
    },
    "headline": "No matter your thing, we’re here for you.",
    "body": "We believe that every occasion is deserving of a personalized touch. Each of our unique spaces is flexible to suit the range of need for any event or gathering.",
    "event_pages": [
      {
        "page_media": {
          "dimensions": {
            "width": 2464,
            "height": 1849
          },
          "alt": null,
          "copyright": null,
          "url": "https://images.prismic.io/the-grand/c38c4ba5-aef7-4dde-9856-9af82d548ca2_events-index-weddings.jpg?auto=format,compress",
          "id": "ZNR68xAAACkAlyFZ",
          "edit": {
            "x": 0,
            "y": 0,
            "zoom": 1,
            "background": "#fff"
          }
        },
        "page": {
          "id": "Y-s-8BEAACIATheH",
          "type": "event_page",
          "tags": [],
          "lang": "en-us",
          "slug": "25",
          "first_publication_date": "2023-02-14T07:58:00+0000",
          "last_publication_date": "2023-08-12T05:30:08+0000",
          "uid": "weddings",
          "data": {
            "caption": "Your dream wedding, made simple.",
            "title": "Weddings",
            "headline": "Let's get married"
          },
          "link_type": "Document",
          "key": "be583240-1ce4-4317-a59a-9e9f14522bdb",
          "isBroken": false
        }
      },
      {
        "page_media": {
          "dimensions": {
            "width": 2464,
            "height": 1849
          },
          "alt": null,
          "copyright": null,
          "url": "https://images.prismic.io/the-grand/5e940a57-d197-4326-919c-9073fcb27c39_events-index-social.jpg?auto=format,compress",
          "id": "ZNR69RAAACkAlyFj",
          "edit": {
            "x": 0,
            "y": 0,
            "zoom": 1,
            "background": "#fff"
          }
        },
        "page": {
          "id": "Y-s-0BEAACEAThbj",
          "type": "event_page",
          "tags": [],
          "lang": "en-us",
          "slug": "5",
          "first_publication_date": "2023-02-14T07:57:29+0000",
          "last_publication_date": "2023-08-12T05:30:56+0000",
          "uid": "milestones",
          "data": {
            "caption": "Celebrate your milestones in style.",
            "title": "Milestones",
            "headline": "Party in grand style"
          },
          "link_type": "Document",
          "key": "ea5ebcf3-1bd0-4494-9678-d6dd44596334",
          "isBroken": false
        }
      },
      {
        "page_media": {
          "dimensions": {
            "width": 2464,
            "height": 1849
          },
          "alt": null,
          "copyright": null,
          "url": "https://images.prismic.io/the-grand/0aba2005-07bc-491a-b49a-34e760e3fcf2_events-index-business.jpg?auto=format,compress",
          "id": "ZNR69BAAACkAlyFe",
          "edit": {
            "x": 0,
            "y": 0,
            "zoom": 1,
            "background": "#fff"
          }
        },
        "page": {
          "id": "Y-s-xREAACAAThao",
          "type": "event_page",
          "tags": [],
          "lang": "en-us",
          "slug": "5",
          "first_publication_date": "2023-02-14T07:56:59+0000",
          "last_publication_date": "2023-08-12T05:31:41+0000",
          "uid": "business",
          "data": {
            "caption": "Elevate your events with our professional touch.",
            "title": "Business",
            "headline": "Business meets pleasure"
          },
          "link_type": "Document",
          "key": "c337c78d-6c8e-402e-89b1-5bcef0393f18",
          "isBroken": false
        }
      },
      {
        "page_media": {},
        "page": {
          "id": "ZC5XThAAAB8A0yhs",
          "type": "tour_index_page",
          "tags": [],
          "lang": "en-us",
          "slug": "tour-index-page",
          "first_publication_date": "2023-04-06T05:28:38+0000",
          "last_publication_date": "2026-02-13T08:15:11+0000",
          "uid": "tour",
          "link_type": "Document",
          "key": "19e0573f-f277-4068-8595-d07f32c24717",
          "isBroken": false
        }
      }
    ],
    "slices": [
      {
        "variation": "default",
        "version": "sktwi1xtmkfgx8626",
        "items": [
          {
            "media": {
              "dimensions": {
                "width": 56,
                "height": 56
              },
              "alt": null,
              "copyright": null,
              "url": "https://the-grand.cdn.prismic.io/the-grand/b42d2e10-44c0-4d07-bbd2-e55d843862c4_elegant.svg?auto=compress,format",
              "id": "ZFiYuhEAACMAsKH2",
              "edit": {
                "x": 0,
                "y": 0,
                "zoom": 1,
                "background": "#fff"
              }
            },
            "number": [
              {
                "type": "heading1",
                "text": "",
                "spans": []
              }
            ],
            "eyebrow": "Elegant",
            "body": [
              {
                "type": "paragraph",
                "text": "Sophisticated spaces and stunning decor for your special occasion.",
                "spans": []
              }
            ],
            "action_text": null,
            "action_link": {
              "link_type": "Any"
            }
          },
          {
            "media": {
              "dimensions": {
                "width": 56,
                "height": 56
              },
              "alt": null,
              "copyright": null,
              "url": "https://the-grand.cdn.prismic.io/the-grand/aee6d307-213a-433b-bd4b-716283adb258_flexible.svg?auto=compress,format",
              "id": "ZFiYuhEAACEAsKIH",
              "edit": {
                "x": 0,
                "y": 0,
                "zoom": 1,
                "background": "#fff"
              }
            },
            "number": [
              {
                "type": "heading1",
                "text": "",
                "spans": []
              }
            ],
            "eyebrow": "Versatile",
            "body": [
              {
                "type": "paragraph",
                "text": "Spaces for weddings, conferences, trade shows, and more.",
                "spans": []
              }
            ],
            "action_text": null,
            "action_link": {
              "link_type": "Any"
            }
          },
          {
            "media": {
              "dimensions": {
                "width": 56,
                "height": 56
              },
              "alt": null,
              "copyright": null,
              "url": "https://the-grand.cdn.prismic.io/the-grand/de8c70ba-a037-4013-8fa6-4e10fb524c34_personal.svg?auto=compress,format",
              "id": "ZFiYuhEAACIAsKH_",
              "edit": {
                "x": 0,
                "y": 0,
                "zoom": 1,
                "background": "#fff"
              }
            },
            "number": [
              {
                "type": "heading1",
                "text": "",
                "spans": []
              }
            ],
            "eyebrow": "Personal",
            "body": [
              {
                "type": "paragraph",
                "text": "Experienced team for personalized service and tailored events.",
                "spans": []
              }
            ],
            "action_text": null,
            "action_link": {
              "link_type": "Any"
            }
          }
        ],
        "primary": {
          "section_id": "features",
          "title": null,
          "description": null,
          "columns": "3 Column",
          "inset": false,
          "top_spacer": "None",
          "top_border": false,
          "bottom_spacer": "None",
          "bottom_border": false
        },
        "id": "numbers_section$d02fdc29-4d57-40af-9691-dd40b09dda9a",
        "slice_type": "numbers_section",
        "slice_label": null
      },
      {
        "variation": "default",
        "version": "sktwi1xtmkfgx8626",
        "items": [
          {}
        ],
        "primary": {
          "section_id": "moments",
          "eyebrow": null,
          "body": [
            {
              "type": "paragraph",
              "text": "We are here for all of life's moments, from intimate family celebrations to large-scale corporate conferences and everything in between. Our team of professionals can help make your wedding, baby shower, anniversary, birthday party, quinceañera, gala, sports banquet, trade show, fundraiser, church service, memorial service, or any event a lasting memory.",
              "spans": []
            }
          ],
          "primary_action": "Make an Inquiry",
          "primary_action_link": {
            "id": "ZC5YBhAAACEA0ymB",
            "type": "inquire_page",
            "tags": [],
            "lang": "en-us",
            "slug": "inquire-page",
            "first_publication_date": "2023-04-06T05:28:37+0000",
            "last_publication_date": "2023-04-06T05:28:37+0000",
            "uid": "inquire",
            "link_type": "Document",
            "key": "d5ee6582-27ff-4002-9607-38219ab1dfb5",
            "isBroken": false
          },
          "secondary_action": null,
          "secondary_action_link": {
            "link_type": "Any"
          },
          "top_spacer": "Small",
          "top_border": true,
          "bottom_spacer": "Medium",
          "bottom_border": true
        },
        "id": "text_section$80197962-4618-4cef-8095-1e3c2d4bb9a8",
        "slice_type": "text_section",
        "slice_label": null
      },
      {
        "variation": "default",
        "version": "sktwi1xtmkfgx8626",
        "items": [
          {
            "question": [
              {
                "type": "paragraph",
                "text": "What types of events are possible?",
                "spans": []
              }
            ],
            "answer": [
              {
                "type": "paragraph",
                "text": "The Grand Long Beach is a versatile event venue that can accommodate a wide range of events, including weddings, corporate meetings, banquets, private parties, fundraisers, conferences, trade shows, product launches, galas, awards ceremonies, concerts, plays, dance recitals, bar mitzvahs, bat mitzvahs, sweet 16 parties, graduation parties, retirement parties, anniversaries, birthday parties, and more. ",
                "spans": []
              }
            ]
          },
          {
            "question": [
              {
                "type": "paragraph",
                "text": "What are the catering options available?",
                "spans": []
              }
            ],
            "answer": [
              {
                "type": "paragraph",
                "text": "The Grand Long Beach offers a variety of menus prepared by the full-service on-site kitchen and a team of experienced chefs. If you prefer outside catering vendors, please discuss with our sales team.",
                "spans": []
              }
            ]
          },
          {
            "question": [
              {
                "type": "paragraph",
                "text": "What are the parking options available?",
                "spans": []
              }
            ],
            "answer": [
              {
                "type": "paragraph",
                "text": "The Grand Long Beach has a large parking lot that can accommodate up to 500 cars. The venue also has a valet parking service available for an additional fee.",
                "spans": []
              }
            ]
          }
        ],
        "primary": {
          "section_id": "faq",
          "title": "All the answers",
          "gallery": {
            "id": "ZNR7zBAAACYAlyUr",
            "type": "fragment_gallery",
            "tags": [],
            "lang": "en-us",
            "slug": "the-palm-terrace",
            "first_publication_date": "2023-08-10T05:57:29+0000",
            "last_publication_date": "2023-08-18T05:46:06+0000",
            "uid": "events-index",
            "data": {
              "gallery_items": [
                {
                  "caption": "The Palm Terrace",
                  "link": {
                    "link_type": "Any"
                  },
                  "video_media": {
                    "link_type": "Media"
                  },
                  "video_url": null,
                  "media": {
                    "dimensions": {
                      "width": 2464,
                      "height": 1848
                    },
                    "alt": null,
                    "copyright": null,
                    "url": "https://images.prismic.io/the-grand/4e5da9ea-5102-4733-a6f6-bdeaf11f9000_glb-events-01.jpg?auto=compress,format",
                    "id": "ZNR65BAAACkAlyEW",
                    "edit": {
                      "x": 0,
                      "y": 0,
                      "zoom": 1,
                      "background": "#fff"
                    }
                  }
                },
                {
                  "caption": "The Palm Terrace",
                  "link": {
                    "link_type": "Any"
                  },
                  "video_media": {
                    "link_type": "Media"
                  },
                  "video_url": null,
                  "media": {
                    "dimensions": {
                      "width": 2464,
                      "height": 1848
                    },
                    "alt": null,
                    "copyright": null,
                    "url": "https://images.prismic.io/the-grand/b2424da6-f04e-4c13-bbd4-8dd886d8af5a_glb-events-index-08.jpg?auto=compress,format",
                    "id": "ZN22XxAAACYAwG_v",
                    "edit": {
                      "x": 0,
                      "y": 0,
                      "zoom": 1,
                      "background": "#fff"
                    }
                  }
                },
                {
                  "caption": "The Grand Ballroom",
                  "link": {
                    "link_type": "Any"
                  },
                  "video_media": {
                    "link_type": "Media"
                  },
                  "video_url": null,
                  "media": {
                    "dimensions": {
                      "width": 2464,
                      "height": 1848
                    },
                    "alt": null,
                    "copyright": null,
                    "url": "https://images.prismic.io/the-grand/698f27a2-826f-423e-ad0b-015a588c99ef_glb-events-index-04.jpg?auto=compress,format",
                    "id": "ZN22YRAAACkAwG_4",
                    "edit": {
                      "x": 0,
                      "y": 0,
                      "zoom": 1,
                      "background": "#fff"
                    }
                  }
                },
                {
                  "caption": "The Palm Terrace",
                  "link": {
                    "link_type": "Any"
                  },
                  "video_media": {
                    "link_type": "Media"
                  },
                  "video_url": null,
                  "media": {
                    "dimensions": {
                      "width": 2464,
                      "height": 1848
                    },
                    "alt": null,
                    "copyright": null,
                    "url": "https://images.prismic.io/the-grand/88768009-a7ce-4fcf-a9a2-254b74eebfe5_glb-events-index-03.jpg?auto=compress,format",
                    "id": "ZN22XxAAACYAwG_w",
                    "edit": {
                      "x": 0,
                      "y": 0,
                      "zoom": 1,
                      "background": "#fff"
                    }
                  }
                },
                {
                  "caption": "The Monarch Patio",
                  "link": {
                    "link_type": "Any"
                  },
                  "video_media": {
                    "link_type": "Media"
                  },
                  "video_url": null,
                  "media": {
                    "dimensions": {
                      "width": 2464,
                      "height": 1848
                    },
                    "alt": null,
                    "copyright": null,
                    "url": "https://images.prismic.io/the-grand/1def0af8-87c9-4159-9fbb-2c2a45f0ad55_glb-events-index-07.jpg?auto=compress,format",
                    "id": "ZN22XxAAACYAwG_y",
                    "edit": {
                      "x": 0,
                      "y": 0,
                      "zoom": 1,
                      "background": "#fff"
                    }
                  }
                },
                {
                  "caption": "The Grand Ballroom",
                  "link": {
                    "link_type": "Any"
                  },
                  "video_media": {
                    "link_type": "Media"
                  },
                  "video_url": null,
                  "media": {
                    "dimensions": {
                      "width": 1848,
                      "height": 2464
                    },
                    "alt": null,
                    "copyright": null,
                    "url": "https://images.prismic.io/the-grand/57c08adf-ad1f-4128-af28-6e3eb99288ef_glb-events-index-02.jpg?auto=compress,format",
                    "id": "ZN22XxAAACgAwG_x",
                    "edit": {
                      "x": 0,
                      "y": 0,
                      "zoom": 1,
                      "background": "#fff"
                    }
                  }
                },
                {
                  "caption": "The Garden Room",
                  "link": {
                    "link_type": "Any"
                  },
                  "video_media": {
                    "link_type": "Media"
                  },
                  "video_url": null,
                  "media": {
                    "dimensions": {
                      "width": 1848,
                      "height": 2464
                    },
                    "alt": null,
                    "copyright": null,
                    "url": "https://images.prismic.io/the-grand/253f1a9a-60f9-4f10-8ed3-fc19ffed1a36_glb-events-index-01.jpg?auto=compress,format",
                    "id": "ZN22YhAAACkAwHAD",
                    "edit": {
                      "x": 0,
                      "y": 0,
                      "zoom": 1,
                      "background": "#fff"
                    }
                  }
                },
                {
                  "caption": "The Palm Terrace",
                  "link": {
                    "link_type": "Any"
                  },
                  "video_media": {
                    "link_type": "Media"
                  },
                  "video_url": null,
                  "media": {
                    "dimensions": {
                      "width": 2464,
                      "height": 1848
                    },
                    "alt": null,
                    "copyright": null,
                    "url": "https://images.prismic.io/the-grand/f49722e7-50f2-4bfb-b421-7ab784f19983_glb-events-index-06.jpg?auto=compress,format",
                    "id": "ZN22YRAAACkAwG_3",
                    "edit": {
                      "x": 0,
                      "y": 0,
                      "zoom": 1,
                      "background": "#fff"
                    }
                  }
                }
              ]
            },
            "link_type": "Document",
            "key": "21a90530-39d7-4306-bb4d-cdc8e2d8e6db",
            "isBroken": false
          },
          "video_media": {
            "link_type": "Media"
          },
          "video_url": null,
          "media": {},
          "asset_position": true
        },
        "id": "faq_section$210ccbd6-8604-4ab0-9bf4-e9b1f9a33609",
        "slice_type": "faq_section",
        "slice_label": null
      }
    ],
    "meta_title": null,
    "meta_description": null,
    "meta_image": {}
  }
} as unknown as Content.EventIndexPageDocument;
