// Auto-generated by scripts/migrate-from-prismic.ts
// To regenerate: npx tsx scripts/migrate-from-prismic.ts
// Events index page content

import type { PageDoc } from "content/types";

export const eventIndexPage: PageDoc = {
  "uid": "events",
  "data": {
    "title": "Your Grand Moment",
    "gallery": [],
    "video_media": null,
    "video_url": "https://cdn.thegrandlb.com/9e5d872e-81ca-46e2-93e4-7d952055014c-events-index-15s-final.mp4",
    "media": {
      "dimensions": {
        "width": 3840,
        "height": 2160
      },
      "alt": null,
      "copyright": null,
      "url": "https://imagedelivery.net/jq-BfOr8JDGgGxqbx8v5CA/cfe41bb3-f218-430d-868d-99feb6668300/public",
      "id": "ZNR7JxAAACYAlyJK",
      "edit": {
        "x": 0,
        "y": 0,
        "zoom": 1,
        "background": "#fff"
      }
    },
    "headline": "No matter your thing, we’re here for you.",
    "body": "We believe that every occasion is deserving of a personalized touch. Each of our unique spaces is flexible to suit the range of need for any event or gathering.",
    "event_pages": [
      {
        "page_media": {
          "dimensions": {
            "width": 2464,
            "height": 1849
          },
          "alt": null,
          "copyright": null,
          "url": "https://imagedelivery.net/jq-BfOr8JDGgGxqbx8v5CA/17986f96-43c9-44bb-705c-10d3e326b600/public",
          "id": "ZNR68xAAACkAlyFZ",
          "edit": {
            "x": 0,
            "y": 0,
            "zoom": 1,
            "background": "#fff"
          }
        },
        "page": {
          "uid": "weddings",
          "data": {
            "caption": "Your dream wedding, made simple.",
            "title": "Weddings",
            "headline": "Let's get married"
          }
        }
      },
      {
        "page_media": {
          "dimensions": {
            "width": 2464,
            "height": 1849
          },
          "alt": null,
          "copyright": null,
          "url": "https://imagedelivery.net/jq-BfOr8JDGgGxqbx8v5CA/f7ffd2cf-564c-4fd8-006e-ff1219868b00/public",
          "id": "ZNR69RAAACkAlyFj",
          "edit": {
            "x": 0,
            "y": 0,
            "zoom": 1,
            "background": "#fff"
          }
        },
        "page": {
          "uid": "milestones",
          "data": {
            "caption": "Celebrate your milestones in style.",
            "title": "Milestones",
            "headline": "Party in grand style"
          }
        }
      },
      {
        "page_media": {
          "dimensions": {
            "width": 2464,
            "height": 1849
          },
          "alt": null,
          "copyright": null,
          "url": "https://imagedelivery.net/jq-BfOr8JDGgGxqbx8v5CA/d3737cc7-41a3-499b-cca7-9269111c0b00/public",
          "id": "ZNR69BAAACkAlyFe",
          "edit": {
            "x": 0,
            "y": 0,
            "zoom": 1,
            "background": "#fff"
          }
        },
        "page": {
          "uid": "business",
          "data": {
            "caption": "Elevate your events with our professional touch.",
            "title": "Business",
            "headline": "Business meets pleasure"
          }
        }
      },
      {
        "page_media": {},
        "page": {
          "uid": "tour",
          "data": {}
        }
      }
    ],
    "slices": [
      {
        "id": "numbers_section$d02fdc29-4d57-40af-9691-dd40b09dda9a",
        "slice_type": "numbers_section",
        "primary": {
          "section_id": "features",
          "title": null,
          "description": null,
          "columns": "3 Column",
          "inset": false,
          "top_spacer": "None",
          "top_border": false,
          "bottom_spacer": "None",
          "bottom_border": false
        },
        "items": [
          {
            "media": {
              "dimensions": {
                "width": 56,
                "height": 56
              },
              "alt": null,
              "copyright": null,
              "url": "https://cdn.thegrandlb.com/elegant.svg",
              "id": "ZFiYuhEAACMAsKH2",
              "edit": {
                "x": 0,
                "y": 0,
                "zoom": 1,
                "background": "#fff"
              }
            },
            "number": [
              {
                "type": "heading1",
                "text": "",
                "spans": []
              }
            ],
            "eyebrow": "Elegant",
            "body": [
              {
                "type": "paragraph",
                "text": "Sophisticated spaces and stunning decor for your special occasion.",
                "spans": []
              }
            ],
            "action_text": null,
            "action_link": {
              "link_type": "Any"
            }
          },
          {
            "media": {
              "dimensions": {
                "width": 56,
                "height": 56
              },
              "alt": null,
              "copyright": null,
              "url": "https://cdn.thegrandlb.com/flexible.svg",
              "id": "ZFiYuhEAACEAsKIH",
              "edit": {
                "x": 0,
                "y": 0,
                "zoom": 1,
                "background": "#fff"
              }
            },
            "number": [
              {
                "type": "heading1",
                "text": "",
                "spans": []
              }
            ],
            "eyebrow": "Versatile",
            "body": [
              {
                "type": "paragraph",
                "text": "Spaces for weddings, conferences, trade shows, and more.",
                "spans": []
              }
            ],
            "action_text": null,
            "action_link": {
              "link_type": "Any"
            }
          },
          {
            "media": {
              "dimensions": {
                "width": 56,
                "height": 56
              },
              "alt": null,
              "copyright": null,
              "url": "https://cdn.thegrandlb.com/personal.svg",
              "id": "ZFiYuhEAACIAsKH_",
              "edit": {
                "x": 0,
                "y": 0,
                "zoom": 1,
                "background": "#fff"
              }
            },
            "number": [
              {
                "type": "heading1",
                "text": "",
                "spans": []
              }
            ],
            "eyebrow": "Personal",
            "body": [
              {
                "type": "paragraph",
                "text": "Experienced team for personalized service and tailored events.",
                "spans": []
              }
            ],
            "action_text": null,
            "action_link": {
              "link_type": "Any"
            }
          }
        ]
      },
      {
        "id": "text_section$80197962-4618-4cef-8095-1e3c2d4bb9a8",
        "slice_type": "text_section",
        "primary": {
          "section_id": "moments",
          "eyebrow": null,
          "body": [
            {
              "type": "paragraph",
              "text": "We are here for all of life's moments, from intimate family celebrations to large-scale corporate conferences and everything in between. Our team of professionals can help make your wedding, baby shower, anniversary, birthday party, quinceañera, gala, sports banquet, trade show, fundraiser, church service, memorial service, or any event a lasting memory.",
              "spans": []
            }
          ],
          "primary_action": "Make an Inquiry",
          "primary_action_link": {
            "id": "ZC5YBhAAACEA0ymB",
            "type": "inquire_page",
            "tags": [],
            "lang": "en-us",
            "slug": "inquire-page",
            "first_publication_date": "2023-04-06T05:28:37+0000",
            "last_publication_date": "2023-04-06T05:28:37+0000",
            "uid": "inquire",
            "link_type": "Document",
            "key": "d5ee6582-27ff-4002-9607-38219ab1dfb5",
            "isBroken": false
          },
          "secondary_action": null,
          "secondary_action_link": {
            "link_type": "Any"
          },
          "top_spacer": "Small",
          "top_border": true,
          "bottom_spacer": "Medium",
          "bottom_border": true
        },
        "items": [
          {}
        ]
      },
      {
        "id": "faq_section$210ccbd6-8604-4ab0-9bf4-e9b1f9a33609",
        "slice_type": "faq_section",
        "primary": {
          "section_id": "faq",
          "title": "All the answers",
          "gallery": {
            "id": "ZNR7zBAAACYAlyUr",
            "type": "fragment_gallery",
            "tags": [],
            "lang": "en-us",
            "slug": "the-palm-terrace",
            "first_publication_date": "2023-08-10T05:57:29+0000",
            "last_publication_date": "2023-08-18T05:46:06+0000",
            "uid": "events-index",
            "data": {
              "gallery_items": [
                {
                  "caption": "The Palm Terrace",
                  "link": {
                    "link_type": "Any"
                  },
                  "video_media": {
                    "link_type": "Media"
                  },
                  "video_url": null,
                  "media": {
                    "dimensions": {
                      "width": 2464,
                      "height": 1848
                    },
                    "alt": null,
                    "copyright": null,
                    "url": "https://imagedelivery.net/jq-BfOr8JDGgGxqbx8v5CA/9d0dccc6-cc37-4965-8019-d351ad9f3700/public",
                    "id": "ZNR65BAAACkAlyEW",
                    "edit": {
                      "x": 0,
                      "y": 0,
                      "zoom": 1,
                      "background": "#fff"
                    }
                  }
                },
                {
                  "caption": "The Palm Terrace",
                  "link": {
                    "link_type": "Any"
                  },
                  "video_media": {
                    "link_type": "Media"
                  },
                  "video_url": null,
                  "media": {
                    "dimensions": {
                      "width": 2464,
                      "height": 1848
                    },
                    "alt": null,
                    "copyright": null,
                    "url": "https://imagedelivery.net/jq-BfOr8JDGgGxqbx8v5CA/45647c84-beeb-4396-f30c-dd2846eec100/public",
                    "id": "ZN22XxAAACYAwG_v",
                    "edit": {
                      "x": 0,
                      "y": 0,
                      "zoom": 1,
                      "background": "#fff"
                    }
                  }
                },
                {
                  "caption": "The Grand Ballroom",
                  "link": {
                    "link_type": "Any"
                  },
                  "video_media": {
                    "link_type": "Media"
                  },
                  "video_url": null,
                  "media": {
                    "dimensions": {
                      "width": 2464,
                      "height": 1848
                    },
                    "alt": null,
                    "copyright": null,
                    "url": "https://imagedelivery.net/jq-BfOr8JDGgGxqbx8v5CA/ba00e56c-e108-4405-26e1-f16ba5b35c00/public",
                    "id": "ZN22YRAAACkAwG_4",
                    "edit": {
                      "x": 0,
                      "y": 0,
                      "zoom": 1,
                      "background": "#fff"
                    }
                  }
                },
                {
                  "caption": "The Palm Terrace",
                  "link": {
                    "link_type": "Any"
                  },
                  "video_media": {
                    "link_type": "Media"
                  },
                  "video_url": null,
                  "media": {
                    "dimensions": {
                      "width": 2464,
                      "height": 1848
                    },
                    "alt": null,
                    "copyright": null,
                    "url": "https://imagedelivery.net/jq-BfOr8JDGgGxqbx8v5CA/166c57dc-8df9-4af7-b71d-1acd17872100/public",
                    "id": "ZN22XxAAACYAwG_w",
                    "edit": {
                      "x": 0,
                      "y": 0,
                      "zoom": 1,
                      "background": "#fff"
                    }
                  }
                },
                {
                  "caption": "The Monarch Patio",
                  "link": {
                    "link_type": "Any"
                  },
                  "video_media": {
                    "link_type": "Media"
                  },
                  "video_url": null,
                  "media": {
                    "dimensions": {
                      "width": 2464,
                      "height": 1848
                    },
                    "alt": null,
                    "copyright": null,
                    "url": "https://imagedelivery.net/jq-BfOr8JDGgGxqbx8v5CA/07acd8a1-873a-46a9-2481-8b8de3197b00/public",
                    "id": "ZN22XxAAACYAwG_y",
                    "edit": {
                      "x": 0,
                      "y": 0,
                      "zoom": 1,
                      "background": "#fff"
                    }
                  }
                },
                {
                  "caption": "The Grand Ballroom",
                  "link": {
                    "link_type": "Any"
                  },
                  "video_media": {
                    "link_type": "Media"
                  },
                  "video_url": null,
                  "media": {
                    "dimensions": {
                      "width": 1848,
                      "height": 2464
                    },
                    "alt": null,
                    "copyright": null,
                    "url": "https://imagedelivery.net/jq-BfOr8JDGgGxqbx8v5CA/0061dc98-91d8-48c7-a03c-391748748a00/public",
                    "id": "ZN22XxAAACgAwG_x",
                    "edit": {
                      "x": 0,
                      "y": 0,
                      "zoom": 1,
                      "background": "#fff"
                    }
                  }
                },
                {
                  "caption": "The Garden Room",
                  "link": {
                    "link_type": "Any"
                  },
                  "video_media": {
                    "link_type": "Media"
                  },
                  "video_url": null,
                  "media": {
                    "dimensions": {
                      "width": 1848,
                      "height": 2464
                    },
                    "alt": null,
                    "copyright": null,
                    "url": "https://imagedelivery.net/jq-BfOr8JDGgGxqbx8v5CA/889f2c5d-d996-4f19-c5c3-6da3daa08b00/public",
                    "id": "ZN22YhAAACkAwHAD",
                    "edit": {
                      "x": 0,
                      "y": 0,
                      "zoom": 1,
                      "background": "#fff"
                    }
                  }
                },
                {
                  "caption": "The Palm Terrace",
                  "link": {
                    "link_type": "Any"
                  },
                  "video_media": {
                    "link_type": "Media"
                  },
                  "video_url": null,
                  "media": {
                    "dimensions": {
                      "width": 2464,
                      "height": 1848
                    },
                    "alt": null,
                    "copyright": null,
                    "url": "https://imagedelivery.net/jq-BfOr8JDGgGxqbx8v5CA/bc27becf-bed9-4be0-7e8d-125bfa267200/public",
                    "id": "ZN22YRAAACkAwG_3",
                    "edit": {
                      "x": 0,
                      "y": 0,
                      "zoom": 1,
                      "background": "#fff"
                    }
                  }
                }
              ]
            },
            "link_type": "Document",
            "key": "21a90530-39d7-4306-bb4d-cdc8e2d8e6db",
            "isBroken": false
          },
          "video_media": {
            "link_type": "Media"
          },
          "video_url": null,
          "media": {},
          "asset_position": true
        },
        "items": [
          {
            "question": [
              {
                "type": "paragraph",
                "text": "What types of events are possible?",
                "spans": []
              }
            ],
            "answer": [
              {
                "type": "paragraph",
                "text": "The Grand Long Beach is a versatile event venue that can accommodate a wide range of events, including weddings, corporate meetings, banquets, private parties, fundraisers, conferences, trade shows, product launches, galas, awards ceremonies, concerts, plays, dance recitals, bar mitzvahs, bat mitzvahs, sweet 16 parties, graduation parties, retirement parties, anniversaries, birthday parties, and more. ",
                "spans": []
              }
            ]
          },
          {
            "question": [
              {
                "type": "paragraph",
                "text": "What are the catering options available?",
                "spans": []
              }
            ],
            "answer": [
              {
                "type": "paragraph",
                "text": "The Grand Long Beach offers a variety of menus prepared by the full-service on-site kitchen and a team of experienced chefs. If you prefer outside catering vendors, please discuss with our sales team.",
                "spans": []
              }
            ]
          },
          {
            "question": [
              {
                "type": "paragraph",
                "text": "What are the parking options available?",
                "spans": []
              }
            ],
            "answer": [
              {
                "type": "paragraph",
                "text": "The Grand Long Beach has a large parking lot that can accommodate up to 500 cars. The venue also has a valet parking service available for an additional fee.",
                "spans": []
              }
            ]
          }
        ]
      }
    ],
    "meta_title": null,
    "meta_description": null,
    "meta_image": {}
  }
};
