// Auto-generated by scripts/migrate-from-prismic.ts
// To regenerate: npx tsx scripts/migrate-from-prismic.ts
// Home page content (replaces Prismic page uid='home')

import type { Content } from "@prismicio/client";

export const homePage = {
  "id": "ZC5Z5xAAAB8A0yxX",
  "uid": "home",
  "url": null,
  "type": "page",
  "href": "https://the-grand.cdn.prismic.io/api/v2/documents/search?ref=aY7e8hEAACQAAXJd&q=%5B%5B%3Ad+%3D+at%28document.id%2C+%22ZC5Z5xAAAB8A0yxX%22%29+%5D%5D",
  "tags": [],
  "first_publication_date": "2023-04-06T05:55:46+0000",
  "last_publication_date": "2026-02-13T08:20:19+0000",
  "slugs": [
    "where-moments-become-memories"
  ],
  "linked_documents": [],
  "lang": "en-us",
  "alternate_languages": [],
  "data": {
    "title": "The Grand Long Beach Event Center",
    "gallery": {
      "link_type": "Document"
    },
    "video_media": {
      "link_type": "Media"
    },
    "video_url": null,
    "media": {},
    "slices": [
      {
        "variation": "default",
        "version": "sktwi1xtmkfgx8626",
        "items": [
          {}
        ],
        "primary": {
          "section_id": "hero",
          "headline": [
            {
              "type": "heading1",
              "text": "Where Moments Become Memories",
              "spans": []
            }
          ],
          "video_media": {
            "link_type": "Media"
          },
          "video_url": "https://cdn.thegrandlb.com/7cff637b-d646-493b-9e81-06266373f84c-homepage-60s-final.mp4",
          "media": {
            "dimensions": {
              "width": 3840,
              "height": 2160
            },
            "alt": null,
            "copyright": null,
            "url": "https://images.prismic.io/the-grand/6eb09764-1687-4954-8f3e-40103c73cf8f_Homepage+60s--final.jpg?auto=compress,format",
            "id": "ZNMofxAAACkAkYES",
            "edit": {
              "x": 0,
              "y": 0,
              "zoom": 1,
              "background": "#fff"
            }
          },
          "primary_action": "Make an inquiry",
          "primary_action_link": {
            "id": "ZC5YBhAAACEA0ymB",
            "type": "inquire_page",
            "tags": [],
            "lang": "en-us",
            "slug": "inquire-page",
            "first_publication_date": "2023-04-06T05:28:37+0000",
            "last_publication_date": "2023-04-06T05:28:37+0000",
            "uid": "inquire",
            "link_type": "Document",
            "key": "028af117-9f75-4b48-8504-72c8c3276200",
            "isBroken": false
          },
          "secondary_action": "Take a tour",
          "secondary_action_link": {
            "id": "ZC5XThAAAB8A0yhs",
            "type": "tour_index_page",
            "tags": [],
            "lang": "en-us",
            "slug": "tour-index-page",
            "first_publication_date": "2023-04-06T05:28:38+0000",
            "last_publication_date": "2026-02-13T08:15:11+0000",
            "uid": "tour",
            "link_type": "Document",
            "key": "ce80cff8-0983-4085-bc1c-f6407c70b5ea",
            "isBroken": false
          },
          "bottom_spacer": "None"
        },
        "id": "page_hero$2b6c6f33-9b66-48f5-b7eb-69abc1366b66",
        "slice_type": "page_hero",
        "slice_label": null
      },
      {
        "variation": "default",
        "version": "sktwi1xtmkfgx8626",
        "items": [
          {
            "card_fragment": {
              "link_type": "Document"
            },
            "media": {
              "dimensions": {
                "width": 217,
                "height": 216
              },
              "alt": null,
              "copyright": null,
              "url": "https://the-grand.cdn.prismic.io/the-grand/433265db-fc1a-4a81-977d-7821a31ee0c8_lovely+couple.svg",
              "id": "ZD9snBAAACIAn2PT",
              "edit": {
                "x": 0,
                "y": 0,
                "zoom": 1,
                "background": "#fff"
              }
            },
            "eyebrow": null,
            "headline": "Tour the spaces",
            "body": "Explore our venue virtually and discover the grand possibilities for your next event.",
            "link": {
              "id": "ZC5XThAAAB8A0yhs",
              "type": "tour_index_page",
              "tags": [],
              "lang": "en-us",
              "slug": "tour-index-page",
              "first_publication_date": "2023-04-06T05:28:38+0000",
              "last_publication_date": "2026-02-13T08:15:11+0000",
              "uid": "tour",
              "link_type": "Document",
              "key": "8ba6f275-6e3e-4b60-982f-7f787e6a8e24",
              "isBroken": false
            },
            "theme": "White/Black",
            "size": null,
            "direction": null,
            "col_start": "Start 1",
            "col_span": "Span 4",
            "row_start": "Start 1",
            "row_span": "Span 2"
          },
          {
            "card_fragment": {
              "link_type": "Document"
            },
            "media": {
              "dimensions": {
                "width": 216,
                "height": 216
              },
              "alt": "The grand entrance",
              "copyright": null,
              "url": "https://the-grand.cdn.prismic.io/the-grand/30740f21-efad-45cf-bd5a-28bbc9115a2f_entry.svg",
              "id": "ZD9idRAAACIAnzXg",
              "edit": {
                "x": 0,
                "y": 0,
                "zoom": 1,
                "background": "#fff"
              }
            },
            "eyebrow": null,
            "headline": "See what we do",
            "body": "Experience our exceptional events and services first-hand through our gallery and client testimonials.",
            "link": {
              "id": "ZC5XgxAAACEA0yi9",
              "type": "event_index_page",
              "tags": [],
              "lang": "en-us",
              "slug": "event-index-page",
              "first_publication_date": "2023-04-06T05:28:38+0000",
              "last_publication_date": "2026-02-13T08:21:06+0000",
              "uid": "events",
              "link_type": "Document",
              "key": "2444a26c-fae4-45d6-8966-ede831df7171",
              "isBroken": false
            },
            "theme": "White/Black",
            "size": null,
            "direction": null,
            "col_start": "Start 5",
            "col_span": "Span 4",
            "row_start": "Start 2",
            "row_span": "Span 2"
          },
          {
            "card_fragment": {
              "id": "ZD-HIhAAACAAn9vx",
              "type": "fragment_card",
              "tags": [],
              "lang": "en-us",
              "slug": "lets-talk",
              "first_publication_date": "2023-04-19T06:20:08+0000",
              "last_publication_date": "2023-06-07T05:54:46+0000",
              "uid": "inquire-card",
              "data": {
                "headline": "Inquire Today",
                "direction": "Col Reverse",
                "col_start": "Start 9",
                "media": {
                  "dimensions": {
                    "width": 216,
                    "height": 216
                  },
                  "alt": null,
                  "copyright": null,
                  "url": "https://the-grand.cdn.prismic.io/the-grand/a3b80527-1022-4545-b910-1bb9f3bc6486_invert%3Dtrue-2.svg",
                  "id": "ZIAbnhUAACoAzXOm",
                  "edit": {
                    "x": 0,
                    "y": 0,
                    "zoom": 1,
                    "background": "#fff"
                  }
                },
                "row_start": "Start 1",
                "theme": "Gold/Black",
                "row_span": "Span 3",
                "size": "Large",
                "col_span": "Span 4",
                "link": {
                  "id": "ZC5YBhAAACEA0ymB",
                  "type": "inquire_page",
                  "tags": [],
                  "lang": "en-us",
                  "slug": "inquire-page",
                  "first_publication_date": "2023-04-06T05:28:37+0000",
                  "last_publication_date": "2023-04-06T05:28:37+0000",
                  "uid": "inquire",
                  "link_type": "Document",
                  "key": "eaadd44d-2b7e-4173-a955-df46fd16e15b",
                  "isBroken": false
                },
                "eyebrow": "Let's Talk"
              },
              "link_type": "Document",
              "key": "013cc499-511e-42d0-a16d-1cddcabe3f9d",
              "isBroken": false
            },
            "media": {
              "dimensions": {
                "width": 217,
                "height": 216
              },
              "alt": "A phone ringing off the hook",
              "copyright": null,
              "url": "https://the-grand.cdn.prismic.io/the-grand/54dd64e5-9127-4b67-8c6d-141d9aebc976_ring.svg",
              "id": "ZD9idRAAACIAnzXf",
              "edit": {
                "x": 0,
                "y": 0,
                "zoom": 1,
                "background": "#fff"
              }
            },
            "eyebrow": "Let's talk",
            "headline": "Inquire today",
            "body": null,
            "link": {
              "id": "ZC5YBhAAACEA0ymB",
              "type": "inquire_page",
              "tags": [],
              "lang": "en-us",
              "slug": "inquire-page",
              "first_publication_date": "2023-04-06T05:28:37+0000",
              "last_publication_date": "2023-04-06T05:28:37+0000",
              "uid": "inquire",
              "link_type": "Document",
              "key": "0d7b3d11-bdbd-4277-af28-767d110df2c5",
              "isBroken": false
            },
            "theme": "Gold/Black",
            "size": "Large",
            "direction": "Col Reverse",
            "col_start": "Start 9",
            "col_span": "Span 4",
            "row_start": "Start 1",
            "row_span": "Span 3"
          },
          {
            "card_fragment": {
              "link_type": "Document"
            },
            "media": {},
            "eyebrow": null,
            "headline": "See our menus",
            "body": null,
            "link": {
              "id": "ZC5eyBAAAB8A0zOo",
              "type": "page",
              "tags": [],
              "lang": "en-us",
              "slug": "menus-at-the-grand",
              "first_publication_date": "2023-04-06T05:55:45+0000",
              "last_publication_date": "2026-02-13T08:13:17+0000",
              "uid": "menus",
              "data": {
                "title": "Menus at The Grand"
              },
              "link_type": "Document",
              "key": "54e6038b-06ec-4f9f-946c-391b1f85546a",
              "isBroken": false
            },
            "theme": "Outlined",
            "size": null,
            "direction": null,
            "col_start": "Start 5",
            "col_span": "Span 4",
            "row_start": "Start 1",
            "row_span": "Span 1"
          },
          {
            "card_fragment": {
              "link_type": "Document"
            },
            "media": {},
            "eyebrow": null,
            "headline": "Meet the team",
            "body": null,
            "link": {
              "id": "ZC5aJhAAACMA0yy1",
              "type": "page",
              "tags": [],
              "lang": "en-us",
              "slug": "weve-been-doing-this-since-1969.",
              "first_publication_date": "2023-04-06T05:55:45+0000",
              "last_publication_date": "2026-02-13T08:08:01+0000",
              "uid": "about",
              "data": {
                "title": "About The Grand"
              },
              "link_type": "Document",
              "key": "350b369d-aba9-4523-a49c-785fc606053e",
              "isBroken": false
            },
            "theme": "Outlined",
            "size": null,
            "direction": null,
            "col_start": "Start 1",
            "col_span": "Span 4",
            "row_start": "Start 3",
            "row_span": "Span 1"
          }
        ],
        "primary": {
          "section_id": "home-tiles",
          "headline": null,
          "body": null,
          "theme": null,
          "top_spacer": "None",
          "bottom_spacer": "Small"
        },
        "id": "tile_grid$19be95eb-b319-4432-9403-8de9ca967d00",
        "slice_type": "tile_grid",
        "slice_label": null
      },
      {
        "variation": "default",
        "version": "sktwi1xtmkfgx8626",
        "items": [
          {}
        ],
        "primary": {
          "section_id": "scroller",
          "top_title": "Your Grand",
          "line_one": "Quince’s & Birthdays & Engagements & Weddings & Banquets &",
          "line_two": "Conferences & Church Services & Pageants & Fundraisers &",
          "bottom_title": "Start here.",
          "primary_action": "See the possibilities",
          "primary_action_link": {
            "id": "ZC5XgxAAACEA0yi9",
            "type": "event_index_page",
            "tags": [],
            "lang": "en-us",
            "slug": "event-index-page",
            "first_publication_date": "2023-04-06T05:28:38+0000",
            "last_publication_date": "2026-02-13T08:21:06+0000",
            "uid": "events",
            "link_type": "Document",
            "key": "ecd0b793-9d98-4060-b064-01ea28d57a6c",
            "isBroken": false
          },
          "top_spacer": "Large",
          "bottom_spacer": "Small"
        },
        "id": "scroll_text$8042575a-5f82-4413-8dc0-dfc1fcb3ba5a",
        "slice_type": "scroll_text",
        "slice_label": null
      },
      {
        "variation": "default",
        "version": "sktwi1xtmkfgx8626",
        "items": [
          {}
        ],
        "primary": {
          "section_id": "gallery",
          "gallery_left": {
            "id": "ZMnw-xAAACMASGo3",
            "type": "fragment_gallery",
            "tags": [],
            "lang": "en-us",
            "slug": "grand-exterior",
            "first_publication_date": "2023-08-02T06:00:30+0000",
            "last_publication_date": "2023-08-07T05:42:42+0000",
            "uid": "home-exterior",
            "data": {
              "gallery_items": [
                {
                  "caption": "Grand Exterior",
                  "link": {
                    "link_type": "Any"
                  },
                  "video_media": {
                    "link_type": "Media"
                  },
                  "video_url": null,
                  "media": {
                    "dimensions": {
                      "width": 2464,
                      "height": 1849
                    },
                    "alt": null,
                    "copyright": null,
                    "url": "https://images.prismic.io/the-grand/79e9f49e-82b0-454b-b1e6-fcb092e5cb6b_glb-home-ext-01-new.jpg?auto=compress,format",
                    "id": "ZNCEAhIAACgAT5Br",
                    "edit": {
                      "x": 0,
                      "y": 0,
                      "zoom": 1,
                      "background": "#fff"
                    }
                  }
                },
                {
                  "caption": "Grand Walkway",
                  "link": {
                    "link_type": "Any"
                  },
                  "video_media": {
                    "link_type": "Media"
                  },
                  "video_url": null,
                  "media": {
                    "dimensions": {
                      "width": 2465,
                      "height": 1849
                    },
                    "alt": null,
                    "copyright": null,
                    "url": "https://images.prismic.io/the-grand/6d40ed6a-df2b-4c71-a92f-00fc97ec7c70_glb-home-ext-02-new.jpg?auto=compress,format",
                    "id": "ZNCEAxIAACgAT5By",
                    "edit": {
                      "x": 0,
                      "y": 0,
                      "zoom": 1,
                      "background": "#fff"
                    }
                  }
                },
                {
                  "caption": "Grand Entrance",
                  "link": {
                    "link_type": "Any"
                  },
                  "video_media": {
                    "link_type": "Media"
                  },
                  "video_url": null,
                  "media": {
                    "dimensions": {
                      "width": 2465,
                      "height": 1849
                    },
                    "alt": null,
                    "copyright": null,
                    "url": "https://images.prismic.io/the-grand/e8f2beb1-45e4-47e6-b2dc-4107563261b1_glb-home-ext-03-new.jpg?auto=compress,format",
                    "id": "ZNCEARIAACgAT5Bk",
                    "edit": {
                      "x": 0,
                      "y": 0,
                      "zoom": 1,
                      "background": "#fff"
                    }
                  }
                },
                {
                  "caption": null,
                  "link": {
                    "link_type": "Any"
                  },
                  "video_media": {
                    "link_type": "Media"
                  },
                  "video_url": null,
                  "media": {
                    "dimensions": {
                      "width": 1849,
                      "height": 2464
                    },
                    "alt": null,
                    "copyright": null,
                    "url": "https://images.prismic.io/the-grand/5b7e51e4-ccc3-4b80-92a3-29cea8daec8e_glb-ext-new-03-new.jpg?auto=compress,format",
                    "id": "ZNCEAxIAACkAT5Bx",
                    "edit": {
                      "x": 0,
                      "y": 0,
                      "zoom": 1,
                      "background": "#fff"
                    }
                  }
                }
              ]
            },
            "link_type": "Document",
            "key": "82aeabc2-ec03-4213-880c-a13bb13e2784",
            "isBroken": false
          },
          "gallery_right": {
            "id": "ZMnxVBAAACMASGvi",
            "type": "fragment_gallery",
            "tags": [],
            "lang": "en-us",
            "slug": "home-exterior1",
            "first_publication_date": "2023-08-02T06:02:37+0000",
            "last_publication_date": "2023-08-07T05:46:55+0000",
            "uid": "home-exterior1",
            "data": {
              "gallery_items": [
                {
                  "caption": null,
                  "link": {
                    "link_type": "Any"
                  },
                  "video_media": {
                    "link_type": "Media"
                  },
                  "video_url": null,
                  "media": {
                    "dimensions": {
                      "width": 1847,
                      "height": 2464
                    },
                    "alt": null,
                    "copyright": null,
                    "url": "https://images.prismic.io/the-grand/16e6da46-cbbc-47d8-82f4-f2cda632696c_glb-home-02-new.jpg?auto=compress,format&rect=2,0,1847,2464&w=1847&h=2464",
                    "id": "ZNCEABIAACcAT5BY",
                    "edit": {
                      "x": -2,
                      "y": 0,
                      "zoom": 1,
                      "background": "#fff"
                    }
                  }
                },
                {
                  "caption": null,
                  "link": {
                    "link_type": "Any"
                  },
                  "video_media": {
                    "link_type": "Media"
                  },
                  "video_url": null,
                  "media": {
                    "dimensions": {
                      "width": 2465,
                      "height": 1848
                    },
                    "alt": null,
                    "copyright": null,
                    "url": "https://images.prismic.io/the-grand/2ac56ab4-7864-4548-8a34-3d80642798c8_glb-home-01-new.jpg?auto=compress,format",
                    "id": "ZNCEARIAACcAT5Be",
                    "edit": {
                      "x": 0,
                      "y": 0,
                      "zoom": 1,
                      "background": "#fff"
                    }
                  }
                },
                {
                  "caption": null,
                  "link": {
                    "link_type": "Any"
                  },
                  "video_media": {
                    "link_type": "Media"
                  },
                  "video_url": null,
                  "media": {
                    "dimensions": {
                      "width": 1845,
                      "height": 2464
                    },
                    "alt": null,
                    "copyright": null,
                    "url": "https://images.prismic.io/the-grand/93c6b063-8ed6-44be-adc7-05d960bacfb7_glb-home-04-new.jpg?auto=compress,format&rect=4,0,1845,2464&w=1845&h=2464",
                    "id": "ZNCEAxIAACcAT5Bs",
                    "edit": {
                      "x": -4,
                      "y": 0,
                      "zoom": 1,
                      "background": "#fff"
                    }
                  }
                },
                {
                  "caption": null,
                  "link": {
                    "link_type": "Any"
                  },
                  "video_media": {
                    "link_type": "Media"
                  },
                  "video_url": null,
                  "media": {
                    "dimensions": {
                      "width": 2464,
                      "height": 1848
                    },
                    "alt": null,
                    "copyright": null,
                    "url": "https://images.prismic.io/the-grand/84f53dd5-f857-4e08-99d5-337b1ca87cda_glb-home-03-new.jpg?auto=compress,format",
                    "id": "ZNCEAhIAACkAT5Bm",
                    "edit": {
                      "x": 0,
                      "y": 0,
                      "zoom": 1,
                      "background": "#fff"
                    }
                  }
                },
                {
                  "caption": null,
                  "link": {
                    "link_type": "Any"
                  },
                  "video_media": {
                    "link_type": "Media"
                  },
                  "video_url": null,
                  "media": {
                    "dimensions": {
                      "width": 1848,
                      "height": 2464
                    },
                    "alt": null,
                    "copyright": null,
                    "url": "https://images.prismic.io/the-grand/9fe1f864-bbfa-4ac6-ada4-949c3c0dc15a_glb-key-01-new.jpg?auto=compress,format",
                    "id": "ZNCEABIAACUAT5Bd",
                    "edit": {
                      "x": 0,
                      "y": 0,
                      "zoom": 1,
                      "background": "#fff"
                    }
                  }
                }
              ]
            },
            "link_type": "Document",
            "key": "fe9c8dc5-6c31-4c59-9fb7-480089d93c04",
            "isBroken": false
          },
          "offset_reverse": true,
          "top_spacer": "Large",
          "bottom_spacer": "Medium"
        },
        "id": "split_gallery$7dcc8ebd-1573-4b3e-9740-02095f7a6990",
        "slice_type": "split_gallery",
        "slice_label": null
      },
      {
        "variation": "default",
        "version": "sktwi1xtmkfgx8626",
        "items": [
          {}
        ],
        "primary": {
          "section_id": "numbers",
          "title": "Numeros",
          "description": [],
          "top_spacer": "Large",
          "bottom_spacer": "None",
          "number_list": {
            "id": "ZD97khAAACMAn6dh",
            "type": "fragment_number_list",
            "tags": [],
            "lang": "en-us",
            "slug": "11",
            "first_publication_date": "2023-04-19T05:28:47+0000",
            "last_publication_date": "2023-04-19T05:28:47+0000",
            "uid": "homepage-numbers",
            "data": {
              "primary_action_link": {
                "id": "ZC5XThAAAB8A0yhs",
                "type": "tour_index_page",
                "tags": [],
                "lang": "en-us",
                "slug": "tour-index-page",
                "first_publication_date": "2023-04-06T05:28:38+0000",
                "last_publication_date": "2026-02-13T08:15:11+0000",
                "uid": "tour",
                "link_type": "Document",
                "key": "43ceda05-b0f6-460b-a544-ca64b0f69052",
                "isBroken": false
              },
              "bullet_list": [
                {
                  "media": {
                    "dimensions": {
                      "width": 71,
                      "height": 70
                    },
                    "alt": null,
                    "copyright": null,
                    "url": "https://the-grand.cdn.prismic.io/the-grand/6aa6633c-be9e-4342-acbd-a09451a43ee9_car.svg",
                    "id": "ZD972xAAACEAn6iu",
                    "edit": {
                      "x": 0,
                      "y": 0,
                      "zoom": 1,
                      "background": "#fff"
                    }
                  },
                  "eyebrow": null,
                  "body": [
                    {
                      "type": "paragraph",
                      "text": "Dedicated Parking Structure",
                      "spans": []
                    }
                  ],
                  "action_text": null,
                  "action_link": {
                    "link_type": "Any"
                  }
                },
                {
                  "media": {
                    "dimensions": {
                      "width": 70,
                      "height": 70
                    },
                    "alt": null,
                    "copyright": null,
                    "url": "https://the-grand.cdn.prismic.io/the-grand/11522fbd-102f-4a84-b916-2afb2a35cdfa_wifi.svg",
                    "id": "ZD972xAAACAAn6it",
                    "edit": {
                      "x": 0,
                      "y": 0,
                      "zoom": 1,
                      "background": "#fff"
                    }
                  },
                  "eyebrow": null,
                  "body": [
                    {
                      "type": "paragraph",
                      "text": "Complimentary Wi-Fi",
                      "spans": []
                    }
                  ],
                  "action_text": null,
                  "action_link": {
                    "link_type": "Any"
                  }
                },
                {
                  "media": {
                    "dimensions": {
                      "width": 71,
                      "height": 70
                    },
                    "alt": null,
                    "copyright": null,
                    "url": "https://the-grand.cdn.prismic.io/the-grand/25942ca4-42e2-44d3-818a-f7545af87c5d_food.svg",
                    "id": "ZD972xAAACAAn6iv",
                    "edit": {
                      "x": 0,
                      "y": 0,
                      "zoom": 1,
                      "background": "#fff"
                    }
                  },
                  "eyebrow": null,
                  "body": [
                    {
                      "type": "paragraph",
                      "text": "World Class Kitchen",
                      "spans": []
                    }
                  ],
                  "action_text": null,
                  "action_link": {
                    "link_type": "Any"
                  }
                }
              ],
              "numberlist": [
                {
                  "number": [
                    {
                      "type": "heading1",
                      "text": "11",
                      "spans": []
                    }
                  ],
                  "eyebrow": "Acres",
                  "body": [],
                  "action_text": null,
                  "action_link": {
                    "link_type": "Any"
                  }
                },
                {
                  "number": [
                    {
                      "type": "heading1",
                      "text": "40K",
                      "spans": []
                    }
                  ],
                  "eyebrow": "Square Feet",
                  "body": [],
                  "action_text": null,
                  "action_link": {
                    "link_type": "Any"
                  }
                },
                {
                  "number": [
                    {
                      "type": "heading1",
                      "text": "7",
                      "spans": []
                    }
                  ],
                  "eyebrow": "Spaces",
                  "body": [],
                  "action_text": null,
                  "action_link": {
                    "link_type": "Any"
                  }
                }
              ],
              "primary_action": "Take a tour"
            },
            "link_type": "Document",
            "key": "c77fed1a-9405-4566-8e68-ca5c6558ac92",
            "isBroken": false
          }
        },
        "id": "homepage_numbers$2cf65ee7-d5db-4238-94d9-443a3448b528",
        "slice_type": "homepage_numbers",
        "slice_label": null
      },
      {
        "variation": "default",
        "version": "sktwi1xtmkfgx8626",
        "items": [
          {}
        ],
        "primary": {
          "section_id": "locale",
          "gallery": {
            "link_type": "Document"
          },
          "video_media": {
            "link_type": "Media"
          },
          "video_url": "https://cdn.thegrandlb.com/2a63ded8-77f1-4838-ab41-da32d6e887df-community-section-30s-final.mp4",
          "media": {
            "dimensions": {
              "width": 3840,
              "height": 2160
            },
            "alt": null,
            "copyright": null,
            "url": "https://images.prismic.io/the-grand/023e7124-6e68-4c95-b62c-c4029947ddaa_Community+Section+30s--final.jpg?auto=compress,format",
            "id": "ZNMpBxAAACgAkYNw",
            "edit": {
              "x": 0,
              "y": 0,
              "zoom": 1,
              "background": "#fff"
            }
          },
          "caption": null,
          "title": [
            {
              "type": "heading1",
              "text": "Family-owned and rooted.",
              "spans": []
            }
          ],
          "description": [
            {
              "type": "paragraph",
              "text": "This place is more than just a venue, it's a hub of social activity that sits at the center of the Long Beach community, where people from all walks of life can come together to celebrate, network, and make memories that last a lifetime. Our 40+ years of expertise and local roots make us the premier event venue for all your So Cal events. ",
              "spans": []
            }
          ],
          "top_spacer": "Large",
          "bottom_spacer": "Large",
          "address_label": "Find Us",
          "address": [
            {
              "type": "paragraph",
              "text": "4101 E. Willow St.\n\u2028Long Beach, CA 90815",
              "spans": []
            }
          ],
          "action_text": "Get Directions",
          "action_link": {
            "link_type": "Web",
            "key": "fb8398a3-9c66-4403-aef5-b8906621f0a4",
            "url": "https://www.google.com/maps/place/4101-e-willow-st,+long-beach-ca-90815/",
            "target": "_blank"
          },
          "bullet_list": {
            "id": "ZD98rRAAACIAn6xj",
            "type": "fragment_number_list",
            "tags": [],
            "lang": "en-us",
            "slug": "20-minutes-from-lax-airport",
            "first_publication_date": "2023-04-19T05:31:42+0000",
            "last_publication_date": "2023-04-19T05:31:42+0000",
            "uid": "location-list",
            "data": {
              "bullet_list": [
                {
                  "media": {
                    "dimensions": {
                      "width": 71,
                      "height": 70
                    },
                    "alt": null,
                    "copyright": null,
                    "url": "https://the-grand.cdn.prismic.io/the-grand/c882adbd-8b70-461d-acfc-9e385d625642_map.svg",
                    "id": "ZD98ixAAACAAn6vG",
                    "edit": {
                      "x": 0,
                      "y": 0,
                      "zoom": 1,
                      "background": "#fff"
                    }
                  },
                  "eyebrow": null,
                  "body": [
                    {
                      "type": "paragraph",
                      "text": "20 Minutes from \u2028\nLAX Airport",
                      "spans": []
                    }
                  ],
                  "action_text": null,
                  "action_link": {
                    "link_type": "Any"
                  }
                },
                {
                  "media": {
                    "dimensions": {
                      "width": 70,
                      "height": 70
                    },
                    "alt": null,
                    "copyright": null,
                    "url": "https://the-grand.cdn.prismic.io/the-grand/48bc45c3-8a4c-4baa-8877-da1d3be1c970_walkin.svg",
                    "id": "ZD98ixAAACAAn6vH",
                    "edit": {
                      "x": 0,
                      "y": 0,
                      "zoom": 1,
                      "background": "#fff"
                    }
                  },
                  "eyebrow": null,
                  "body": [
                    {
                      "type": "paragraph",
                      "text": "Walking Distance to \n\u2028Hotel Accommodations",
                      "spans": []
                    }
                  ],
                  "action_text": null,
                  "action_link": {
                    "link_type": "Any"
                  }
                },
                {
                  "media": {
                    "dimensions": {
                      "width": 71,
                      "height": 70
                    },
                    "alt": null,
                    "copyright": null,
                    "url": "https://the-grand.cdn.prismic.io/the-grand/a8428e0b-980c-4f3b-ad6b-e9b6d7b040df_fly.svg",
                    "id": "ZD98ixAAACIAn6vI",
                    "edit": {
                      "x": 0,
                      "y": 0,
                      "zoom": 1,
                      "background": "#fff"
                    }
                  },
                  "eyebrow": null,
                  "body": [
                    {
                      "type": "paragraph",
                      "text": "5 Minutes from \u2028\nLong Beach Airport",
                      "spans": []
                    }
                  ],
                  "action_text": null,
                  "action_link": {
                    "link_type": "Any"
                  }
                }
              ],
              "numberlist": []
            },
            "link_type": "Document",
            "key": "a158e21b-e54f-4174-9a4e-878adc0fa690",
            "isBroken": false
          }
        },
        "id": "homepage_location$85a16ed5-5892-4a16-8902-1ee1aab9cd81",
        "slice_type": "homepage_location",
        "slice_label": null
      },
      {
        "variation": "default",
        "version": "sktwi1xtmkfgx8626",
        "items": [
          {
            "logo": {
              "dimensions": {
                "width": 118,
                "height": 59
              },
              "alt": "Yelp Logo",
              "copyright": null,
              "url": "https://the-grand.cdn.prismic.io/the-grand/c204d73d-8a8f-4696-ad41-20116bb2ebcb_yelp.svg",
              "id": "ZD9oDBAAACAAn09d",
              "edit": {
                "x": 0,
                "y": 0,
                "zoom": 1,
                "background": "#fff"
              }
            },
            "name": "Yelp",
            "stars": 4.5,
            "reviews": "200+",
            "link": {
              "link_type": "Web",
              "key": "405eaa2b-d40b-4879-a825-c1d593ac1939",
              "url": "https://www.yelp.com/biz/the-grand-long-beach-long-beach",
              "target": "_blank"
            }
          },
          {
            "logo": {},
            "name": "The Knot",
            "stars": 4.9,
            "reviews": "15+",
            "link": {
              "link_type": "Web",
              "key": "5ab57b6b-2918-4a8e-b5d8-a55adad182f0",
              "url": "https://www.theknot.com/marketplace/the-grand-long-beach-long-beach-ca-620906",
              "target": "_blank"
            }
          },
          {
            "logo": {},
            "name": "Wedding Wire",
            "stars": 4.4,
            "reviews": "50+",
            "link": {
              "link_type": "Web",
              "key": "6036351b-aeb5-41cf-b53e-8512352a9aab",
              "url": "https://www.weddingwire.com/biz/the-grand-long-beach-long-beach/05b58faf6174714e.html",
              "target": "_blank"
            }
          }
        ],
        "primary": {
          "section_id": "ratings",
          "title": [
            {
              "type": "heading1",
              "text": "The proof is in the pudding",
              "spans": []
            }
          ],
          "top_spacer": "Large",
          "bottom_spacer": "None",
          "show_customer_reviews": true
        },
        "id": "star_section$a8f5939c-899e-430d-aaae-95a08fd86635",
        "slice_type": "star_section",
        "slice_label": null
      },
      {
        "variation": "default",
        "version": "sktwi1xtmkfgx8626",
        "items": [
          {
            "card_fragment": {
              "link_type": "Document"
            },
            "media": {},
            "eyebrow": "SEE OUR SPACES",
            "headline": "TOUR THE GRAND SPACES",
            "body": "Explore our venue virtually and discover the grand possibilities for your next event.",
            "link": {
              "id": "ZC5XThAAAB8A0yhs",
              "type": "tour_index_page",
              "tags": [],
              "lang": "en-us",
              "slug": "tour-index-page",
              "first_publication_date": "2023-04-06T05:28:38+0000",
              "last_publication_date": "2026-02-13T08:15:11+0000",
              "uid": "tour",
              "link_type": "Document",
              "key": "a4f2b9a8-4b4c-4bdc-93f1-359d46daf523",
              "isBroken": false
            },
            "theme": "Black/White",
            "size": "Large",
            "direction": null,
            "col_start": "Start 2",
            "col_span": "Span 5",
            "row_start": "Start 1",
            "row_span": "Span 3"
          },
          {
            "card_fragment": {
              "link_type": "Document"
            },
            "media": {},
            "eyebrow": "SEE OUR MENUS",
            "headline": "A taste of Grand",
            "body": "Our in-house catering team is dedicated to delivering delicious and innovative cuisine that will impress your guests. Our menu options are designed to be both delicious and visually stunning, ensuring that your event is a memorable one.",
            "link": {
              "id": "ZC5eyBAAAB8A0zOo",
              "type": "page",
              "tags": [],
              "lang": "en-us",
              "slug": "menus-at-the-grand",
              "first_publication_date": "2023-04-06T05:55:45+0000",
              "last_publication_date": "2026-02-13T08:13:17+0000",
              "uid": "menus",
              "data": {
                "title": "Menus at The Grand"
              },
              "link_type": "Document",
              "key": "e1f555a5-6831-49ec-b927-77f5a9701c42",
              "isBroken": false
            },
            "theme": "Creme/Black",
            "size": "Large",
            "direction": null,
            "col_start": "Start 7",
            "col_span": "Span 5",
            "row_start": "Start 1",
            "row_span": "Span 3"
          }
        ],
        "primary": {
          "section_id": "discover",
          "headline": "Discover more and\nmore Grand.",
          "body": null,
          "theme": "White",
          "top_spacer": "Large",
          "bottom_spacer": "Large"
        },
        "id": "tile_grid$26bb0da6-5e14-48c0-880e-568c6b2a8a79",
        "slice_type": "tile_grid",
        "slice_label": null
      }
    ],
    "meta_title": null,
    "meta_description": null,
    "meta_image": {}
  }
} as unknown as Content.PageDocument;
